using BeeKingdom.HiveOperations;

namespace BeeKingdom.Tests;

public sealed class BuildingUpgradeServiceTests
{
    [Test] public void DisabledOptionsFailClosed(){var repo=new MemoryRepo();Assert.ThrowsAsync<InvalidOperationException>(()=>new BuildingUpgradeService(repo,new Clock(DateTimeOffset.UtcNow),new BuildingUpgradeOptions()).ReadAsync(Guid.NewGuid(),Guid.NewGuid()));}
    [Test] public async Task StartUsesServerCatalogAndDebitsAtomically(){var clock=new Clock(DateTimeOffset.UtcNow);var repo=new MemoryRepo();var (p,h)=Seed(repo);var s=new BuildingUpgradeService(repo,clock,Options());var r=await s.StartAsync(p,h,"wax_workshop",new(0,"start-1"));Assert.That(r.Succeeded,Is.True);Assert.That(r.Response!.Receipt.Code,Is.EqualTo("game.building_upgrade_started"));Assert.That(r.Response.Receipt.FromLevel,Is.EqualTo(1));Assert.That(r.Response.Receipt.ToLevel,Is.EqualTo(2));var state=await repo.ReadAsync(p,h);Assert.That(state!.Resources["honey"].Amount,Is.EqualTo(80));Assert.That(state.Resources["pollen"].Amount,Is.EqualTo(40));}
    [Test] public async Task BusyAndIdempotencyConflictDoNotMutate(){var clock=new Clock(DateTimeOffset.UtcNow);var repo=new MemoryRepo();var (p,h)=Seed(repo);var s=new BuildingUpgradeService(repo,clock,Options());var first=await s.StartAsync(p,h,"wax_workshop",new(0,"same"));Assert.That(first.Response!.Receipt.IdempotencyKey,Is.EqualTo("same"));Assert.That((await s.StartAsync(p,h,"wax_workshop",new(1,"other"))).Code,Is.EqualTo("game.construction_busy"));var replay=await s.StartAsync(p,h,"wax_workshop",new(0,"same"));Assert.That(replay.Code,Is.EqualTo("game.building_upgrade_started"));Assert.That(replay.Response!.Receipt,Is.EqualTo(first.Response.Receipt));Assert.That((await s.StartAsync(p,h,"wax_workshop",new(1,"same"))).Code,Is.EqualTo("game.idempotency_conflict"));}
    [Test] public async Task CompleteRequiresServerTimeAndRaisesLevel(){var clock=new Clock(DateTimeOffset.UtcNow);var repo=new MemoryRepo();var (p,h)=Seed(repo);var s=new BuildingUpgradeService(repo,clock,Options());var start=await s.StartAsync(p,h,"wax_workshop",new(0,"start"));var op=start.Response!.Receipt.OperationId;Assert.That((await s.CompleteAsync(p,h,op,new(1,"complete"))).Code,Is.EqualTo("game.not_ready"));clock.Advance(TimeSpan.FromHours(1));var done=await s.CompleteAsync(p,h,op,new(1,"complete"));Assert.That(done.Succeeded,Is.True);Assert.That(done.Response!.Receipt.Code,Is.EqualTo("game.building_upgrade_completed"));Assert.That((await repo.ReadAsync(p,h))!.BuildingLevels["wax_workshop"],Is.EqualTo(2));}
    private static BuildingUpgradeOptions Options()=>new(){Enabled=true,CatalogVersion="phase-test-v1",Catalog=[new("wax_workshop",1,2,TimeSpan.FromHours(1),new Dictionary<string,long>{{"honey",20},{"pollen",60}})]};
    private static (Guid,Guid) Seed(MemoryRepo r){var p=Guid.NewGuid();var h=Guid.NewGuid();r.State=new(p,h,HiveStateMigrator.CurrentModelVersion,0,new Dictionary<string,ResourceBalance>{{"honey",new(100,200)},{"pollen",new(100,200)},{"wax",new(0,100)}},new Dictionary<string,int>{{"wax_workshop",1}},new(),new());return(p,h);}
    private sealed class Clock(DateTimeOffset now):IServerClock{public DateTimeOffset UtcNow{get;private set;}=now;public void Advance(TimeSpan t)=>UtcNow+=t;}
    private sealed class MemoryRepo:IHiveStateRepository{public PlayerHiveState? State;public Task<PlayerHiveState?> ReadAsync(Guid p,Guid h,CancellationToken ct=default)=>Task.FromResult(State?.PlayerId==p&&State.HiveId==h?State:null);public Task<PlayerHiveState> ExecuteAtomicallyAsync(Guid p,Guid h,Func<PlayerHiveState,PlayerHiveState> m,CancellationToken ct=default){State ??= new(p,h,HiveStateMigrator.CurrentModelVersion,0,new(),new(),new(),new());State=m(State);return Task.FromResult(State);}public Task<IReadOnlyList<Guid>> ListHiveIdsAsync(Guid p,CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<Guid>>(State!=null&&State.PlayerId==p?new List<Guid>{State.HiveId}:new List<Guid>());public Task<IReadOnlyList<PlayerHiveState>> ListRecentlyActiveAsync(int limit,CancellationToken ct=default)=>Task.FromResult<IReadOnlyList<PlayerHiveState>>(State!=null?new List<PlayerHiveState>{State}:new List<PlayerHiveState>());}
}
