using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using BeeKingdom.Authentication.Providers;
using BeeKingdom.HiveOperations;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace BeeKingdom.Tests;
public sealed class CombatSquadReservationEndpointTests
{
    [Test] public async Task Commit_replay_after_release_long_max_both_routes_and_partition_isolation(){await using var f=Factory(true);using var c=f.CreateClient();var t=await Login(f,c);c.DefaultRequestHeaders.Authorization=new("Bearer",t);var auth=f.Services.GetRequiredService<BeeKingdom.Authentication.AuthenticationManager>();var p=auth.ValidateToken(t).PlayerId!.Value;var h=Guid.NewGuid();await f.Services.GetRequiredService<IHiveStateRepository>().ExecuteAtomicallyAsync(p,h,s=>s with{DoctrineRoster=new DoctrineRosterState(0,new Dictionary<string,long>{{"guardians",4},{"wingrunners",4},{"darters",4}},null,new()),SquadReservation=new SquadReservationState(0,12,new Dictionary<string,long>{{"guardians",0},{"wingrunners",0},{"darters",0}},null,new())});var q=new{guardians=1,wingrunners=0,darters=0};var first=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",new{expectedRevision=0,idempotencyKey="commit-x",quantities=q});var firstJson=JsonDocument.Parse(await first.Content.ReadAsStringAsync());var badCommit=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",new{expectedRevision=long.MaxValue,idempotencyKey="max-c",quantities=q});Assert.That(badCommit.StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));var release=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/release",new{expectedRevision=1,idempotencyKey="release-x"});Assert.That(release.StatusCode,Is.EqualTo(HttpStatusCode.OK));var replay=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",new{expectedRevision=0,idempotencyKey="commit-x",quantities=q});var replayJson=JsonDocument.Parse(await replay.Content.ReadAsStringAsync());Assert.That(replay.StatusCode,Is.EqualTo(HttpStatusCode.OK));Assert.That(replayJson.RootElement.GetProperty("receipt").GetRawText(),Is.EqualTo(firstJson.RootElement.GetProperty("receipt").GetRawText()));Assert.That(replayJson.RootElement.GetProperty("snapshot").GetProperty("reservationId").ValueKind,Is.EqualTo(JsonValueKind.Null));var badRelease=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/release",new{expectedRevision=long.MaxValue,idempotencyKey="max-r"});Assert.That(badRelease.StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));using var foreign=f.CreateClient();var ft=await Login(f,foreign);foreign.DefaultRequestHeaders.Authorization=new("Bearer",ft);Assert.That((await foreign.GetAsync($"/game/v1/hives/{h:D}/combat/squad-reservation")).StatusCode,Is.EqualTo(HttpStatusCode.NotFound));}
    [Test] public async Task Commit_release_replays_and_long_max_are_safe(){await using var f=Factory(true);using var c=f.CreateClient();var t=await Login(f,c);c.DefaultRequestHeaders.Authorization=new("Bearer",t);var p=f.Services.GetRequiredService<BeeKingdom.Authentication.AuthenticationManager>().ValidateToken(t).PlayerId!.Value;var h=Guid.NewGuid();await f.Services.GetRequiredService<IHiveStateRepository>().ExecuteAtomicallyAsync(p,h,s=>s with{DoctrineRoster=new DoctrineRosterState(0,new Dictionary<string,long>{{"guardians",4},{"wingrunners",4},{"darters",4}},null,new()),SquadReservation=new SquadReservationState(0,12,new Dictionary<string,long>{{"guardians",0},{"wingrunners",0},{"darters",0}},null,new())});var body=new{expectedRevision=0,idempotencyKey="same-1",quantities=new{guardians=1,wingrunners=0,darters=0}};var a=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",body);var aJson=JsonDocument.Parse(await a.Content.ReadAsStringAsync());var b=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",body);var bJson=JsonDocument.Parse(await b.Content.ReadAsStringAsync());Assert.That(a.StatusCode,Is.EqualTo(HttpStatusCode.OK));Assert.That(b.StatusCode,Is.EqualTo(HttpStatusCode.OK));Assert.That(bJson.RootElement.GetProperty("receipt").GetRawText(),Is.EqualTo(aJson.RootElement.GetProperty("receipt").GetRawText()));Assert.That(bJson.RootElement.ToString(),Does.Not.Contain("payloadHash"));var conflict=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",new{expectedRevision=0,idempotencyKey="same-1",quantities=new{guardians=2,wingrunners=0,darters=0}});Assert.That(conflict.StatusCode,Is.EqualTo(HttpStatusCode.Conflict));var max=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/release",new{expectedRevision=long.MaxValue,idempotencyKey="max"});Assert.That(max.StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));var rel=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/release",new{expectedRevision=1,idempotencyKey="rel-1"});Assert.That(rel.StatusCode,Is.EqualTo(HttpStatusCode.OK));var relJson=JsonDocument.Parse(await rel.Content.ReadAsStringAsync());var relReplay=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/release",new{expectedRevision=1,idempotencyKey="rel-1"});var relReplayJson=JsonDocument.Parse(await relReplay.Content.ReadAsStringAsync());Assert.That(relReplay.StatusCode,Is.EqualTo(HttpStatusCode.OK));Assert.That(relReplayJson.RootElement.GetProperty("receipt").GetRawText(),Is.EqualTo(relJson.RootElement.GetProperty("receipt").GetRawText()));}
    [Test] public async Task Closed_flag_returns_503_before_auth(){await using var f=Factory(false);using var c=f.CreateClient();var r=await c.GetAsync($"/game/v1/hives/{Guid.NewGuid():D}/combat/squad-reservation");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.ServiceUnavailable));}
    [Test] public async Task Enabled_requires_auth_and_validates_requests(){await using var f=Factory(true);using var c=f.CreateClient();Assert.That((await c.GetAsync($"/game/v1/hives/{Guid.NewGuid():D}/combat/squad-reservation")).StatusCode,Is.EqualTo(HttpStatusCode.Unauthorized));var t=await Login(f,c);c.DefaultRequestHeaders.Authorization=new("Bearer",t);var bad=await c.PostAsJsonAsync($"/game/v1/hives/{Guid.NewGuid():D}/combat/squad-reservation/commit",new{expectedRevision=-1,idempotencyKey="bad",quantities=new{guardians=1,wingrunners=0,darters=0}});Assert.That(bad.StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));}
    [Test] public async Task Enabled_commit_returns_public_receipt_without_secrets(){await using var f=Factory(true);using var c=f.CreateClient();var t=await Login(f,c);c.DefaultRequestHeaders.Authorization=new("Bearer",t);var p=f.Services.GetRequiredService<BeeKingdom.Authentication.AuthenticationManager>().ValidateToken(t).PlayerId!.Value;var h=Guid.NewGuid();await f.Services.GetRequiredService<IHiveStateRepository>().ExecuteAtomicallyAsync(p,h,s=>s with{DoctrineRoster=new DoctrineRosterState(0,new Dictionary<string,long>{{"guardians",4},{"wingrunners",4},{"darters",4}},null,new()),SquadReservation=new SquadReservationState(0,12,new Dictionary<string,long>{{"guardians",0},{"wingrunners",0},{"darters",0}},null,new())});var r=await c.PostAsJsonAsync($"/game/v1/hives/{h:D}/combat/squad-reservation/commit",new{expectedRevision=0,idempotencyKey="commit-1",quantities=new{guardians=1,wingrunners=0,darters=0}});Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.OK));using var d=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.That(d.RootElement.GetProperty("receipt").GetProperty("action").GetString(),Is.EqualTo("commit"));Assert.That(d.RootElement.GetProperty("receipt").GetProperty("idempotencyKey").GetString(),Is.EqualTo("commit-1"));Assert.That(d.RootElement.GetProperty("receipt").GetProperty("reservationRevisionBefore").GetInt64(),Is.EqualTo(0));Assert.That(d.RootElement.GetProperty("snapshot").GetProperty("reservationId").GetString(),Is.Not.Null);Assert.That(d.RootElement.ToString(),Does.Not.Contain("payloadHash"));}
    private static WebApplicationFactory<Program> Factory(bool enabled)=>new WebApplicationFactory<Program>().WithWebHostBuilder(b=>{b.UseSetting("environment","Development");b.ConfigureAppConfiguration((_,c)=>c.AddInMemoryCollection(new Dictionary<string,string?>{{"CombatSquadReservation:Enabled",enabled.ToString()}}));});
    private static async Task<string> Login(WebApplicationFactory<Program> f,HttpClient c){var e=$"squad-{Guid.NewGuid():N}@bee.test";f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(e,"secret");using var d=JsonDocument.Parse(await(await c.PostAsJsonAsync("/auth/login",new{email=e,password="secret",clientVersion="1",ipAddress="127.0.0.1",deviceIdentifier="squad",region="local"})).Content.ReadAsStringAsync());return d.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;}
}
