using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using BeeKingdom.Authentication.Providers;
using BeeKingdom.HiveOperations;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace BeeKingdom.Tests;
public sealed class HiveStockEndpointTests
{
    [Test] public async Task ClosedFlagReturns503BeforeAuth(){await using var f=Create(false);using var c=f.CreateClient();var r=await c.GetAsync($"/game/v1/hives/{Guid.NewGuid()}/hive-stock");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.ServiceUnavailable));}
    [Test] public async Task InvalidBearerReturns401WhenEnabled(){await using var f=Create(true);using var c=f.CreateClient();var r=await c.GetAsync($"/game/v1/hives/{Guid.NewGuid()}/hive-stock");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.Unauthorized));}
    [Test] public async Task EnabledReturnsAuthoritativeCamelCaseSnapshotAndRepeatedReadIsNonMutating(){await using var f=Create(true);using var c=f.CreateClient();var email=$"stock-{Guid.NewGuid():N}@bee.test";f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(email,"secret");var login=await c.PostAsJsonAsync("/auth/login",new{email,password="secret",clientVersion="1.0"});using var lj=JsonDocument.Parse(await login.Content.ReadAsStringAsync());var token=lj.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var player=f.Services.GetRequiredService<BeeKingdom.Authentication.AuthenticationManager>().ValidateToken(token).PlayerId!.Value;var hive=Guid.NewGuid();var repo=f.Services.GetRequiredService<IHiveStateRepository>();await repo.ExecuteAtomicallyAsync(player,hive,s=>s with{Resources=new Dictionary<string,ResourceBalance>{{"honey",new(10,100)},{"wax",new(20,100)},{"pollen",new(30,100)}},Research=new(new Dictionary<string,ResearchCompletion>(),null)});var before=await repo.ReadAsync(player,hive);var a=await c.GetAsync($"/game/v1/hives/{hive}/hive-stock");Assert.That(a.StatusCode,Is.EqualTo(HttpStatusCode.OK));using var j=JsonDocument.Parse(await a.Content.ReadAsStringAsync());Assert.That(j.RootElement.GetProperty("contractVersion").GetString(),Is.EqualTo("living-hive-stock-v1"));Assert.That(j.RootElement.GetProperty("resources").GetProperty("honey").GetProperty("amount").GetInt64(),Is.EqualTo(10));var b=await c.GetAsync($"/game/v1/hives/{hive}/hive-stock");Assert.That(b.StatusCode,Is.EqualTo(HttpStatusCode.OK));var after=await repo.ReadAsync(player,hive);Assert.That(after!.Revision,Is.EqualTo(before!.Revision));Assert.That(after.Resources,Is.EqualTo(before.Resources));Assert.That(after.Operations,Is.EqualTo(before.Operations));}
    [Test] public async Task DailyRoundEnabledMarksSnapshotReadOnceAndKeepsResourcesAndOperations(){await using var f=Create(true,true);using var c=f.CreateClient();var email=$"stock-daily-{Guid.NewGuid():N}@bee.test";f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(email,"secret");var login=await c.PostAsJsonAsync("/auth/login",new{email,password="secret",clientVersion="1.0"});using var lj=JsonDocument.Parse(await login.Content.ReadAsStringAsync());var token=lj.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var player=f.Services.GetRequiredService<BeeKingdom.Authentication.AuthenticationManager>().ValidateToken(token).PlayerId!.Value;var hive=Guid.NewGuid();var repo=f.Services.GetRequiredService<IHiveStateRepository>();await repo.ExecuteAtomicallyAsync(player,hive,s=>s with{Resources=new Dictionary<string,ResourceBalance>{{"honey",new(10,100)}, {"wax",new(20,100)}, {"pollen",new(30,100)}},Operations=new List<HiveOperation>(),Research=new(new Dictionary<string,ResearchCompletion>(),null)});var before=await repo.ReadAsync(player,hive);var first=await c.GetAsync($"/game/v1/hives/{hive}/hive-stock");Assert.That(first.StatusCode,Is.EqualTo(HttpStatusCode.OK));var afterFirst=await repo.ReadAsync(player,hive);Assert.That(afterFirst!.Revision,Is.EqualTo(before!.Revision+1));Assert.That(afterFirst.DailyRound!.SnapshotRead,Is.True);Assert.That(afterFirst.Resources,Is.EqualTo(before.Resources));Assert.That(afterFirst.Operations,Is.EqualTo(before.Operations));var second=await c.GetAsync($"/game/v1/hives/{hive}/hive-stock");Assert.That(second.StatusCode,Is.EqualTo(HttpStatusCode.OK));var afterSecond=await repo.ReadAsync(player,hive);Assert.That(afterSecond!.Revision,Is.EqualTo(afterFirst.Revision));Assert.That(afterSecond.DailyRound,Is.EqualTo(afterFirst.DailyRound));}
    private static WebApplicationFactory<Program> Create(bool enabled,bool daily=false)=>new WebApplicationFactory<Program>().WithWebHostBuilder(b=>{b.UseSetting("environment","Development");b.ConfigureAppConfiguration((_,c)=>c.AddInMemoryCollection(new Dictionary<string,string?>{{"HiveStockSnapshot:Enabled",enabled.ToString().ToLowerInvariant()},{"HiveStockSnapshot:CatalogVersion",enabled?"test-v1":""},{"HiveDailyRound:Enabled",daily.ToString().ToLowerInvariant()}}));});
}
