using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using BeeKingdom.Authentication;
using AuthenticationManager = BeeKingdom.Authentication.AuthenticationManager;
using BeeKingdom.Authentication.Providers;
using BeeKingdom.HiveOperations;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
namespace BeeKingdom.Tests;
public sealed class HiveOfflineProductionEndpointTests
{
 [Test] public async Task FeatureFlagOffReturns503BeforeAuthAndDoesNotTouchRepository(){await using var f=Create(false);using var c=f.CreateClient();Assert.That((await c.GetAsync($"/game/v1/hives/{Guid.NewGuid()}/offline-production")).StatusCode,Is.EqualTo(HttpStatusCode.ServiceUnavailable));}
 [Test] public async Task EnabledRoutesRequireBearerSession(){await using var f=Create(true);using var c=f.CreateClient();var id=Guid.NewGuid();Assert.That((await c.GetAsync($"/game/v1/hives/{id}/offline-production")).StatusCode,Is.EqualTo(HttpStatusCode.Unauthorized));Assert.That((await c.PostAsJsonAsync($"/game/v1/hives/{id}/offline-production/honey_storage/collect",new{expectedProductionRevision=0,idempotencyKey="x"})).StatusCode,Is.EqualTo(HttpStatusCode.Unauthorized));}
 [Test] public async Task InvalidHiveBuildingAndRequestReturn400GameInvalidRequest(){await using var f=Create(true);using var c=f.CreateClient();var token=await Login(f,c,$"offline-{Guid.NewGuid():N}@bee.test");c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);Assert.That((await c.GetAsync("/game/v1/hives/not-guid/offline-production")).StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));Assert.That((await c.PostAsJsonAsync($"/game/v1/hives/{Guid.NewGuid()}/offline-production/unknown/collect",new{expectedProductionRevision=-1,idempotencyKey=""})).StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));}
 [Test] public async Task GetReturnsAuthoritativeAccruedSnapshotAndPrivateNoStore(){await using var f=Create(true);using var c=f.CreateClient();var token=await Login(f,c,$"offline-read-{Guid.NewGuid():N}@bee.test");c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var r=await c.GetAsync($"/game/v1/hives/{Guid.NewGuid()}/offline-production");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.OK));Assert.That(r.Headers.CacheControl?.Private,Is.True);using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.That(j.RootElement.GetProperty("contractVersion").GetString(),Is.EqualTo(HiveOfflineProductionService.ContractVersion));}
 [Test] public async Task PostCollectsFloorPreservesFractionPersistsAndReplaysExact()
 {
  await using var f=Create(true); using var c=f.CreateClient(); var token=await Login(f,c,$"offline-collect-{Guid.NewGuid():N}@bee.test"); c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);
  var player=f.Services.GetRequiredService<AuthenticationManager>().ValidateToken(token).PlayerId.Value; var hive=Guid.NewGuid(); var repo=f.Services.GetRequiredService<IHiveStateRepository>();
  await repo.ExecuteAtomicallyAsync(player,hive,s=>s with { Resources=new Dictionary<string,ResourceBalance>{{"honey",new(0,100)},{"wax",new(0,100)},{"pollen",new(0,100)}}, OfflineProduction=new(DateTimeOffset.UtcNow.AddHours(1),new Dictionary<string,decimal>{{"honey_storage",1.5m},{"wax_workshop",0m},{"warehouse_cells",0m}},0,new Dictionary<string,OfflineProductionStoredReceipt>()) });
  var body=new { expectedProductionRevision=0, idempotencyKey="collect-1" }; var first=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",body); Assert.That(first.StatusCode,Is.EqualTo(HttpStatusCode.OK)); var firstJson=await first.Content.ReadAsStringAsync(); using var json=JsonDocument.Parse(firstJson); Assert.That(json.RootElement.GetProperty("receipt").GetProperty("creditedAmount").GetInt64(),Is.EqualTo(1)); Assert.That(json.RootElement.GetProperty("receipt").GetProperty("remainingPending").GetDecimal(),Is.EqualTo(.5m)); Assert.That((await repo.ReadAsync(player,hive))!.Resources["honey"].Amount,Is.EqualTo(1));
  var replay=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",body); Assert.That(replay.StatusCode,Is.EqualTo(HttpStatusCode.OK)); Assert.That(await replay.Content.ReadAsStringAsync(),Is.EqualTo(firstJson)); Assert.That((await repo.ReadAsync(player,hive))!.Resources["honey"].Amount,Is.EqualTo(1));
 }
 [Test] public async Task PostReturns409ForStaleRevisionAndIdempotencyConflictWithoutSecondCredit()
 {
  await using var f=Create(true); using var c=f.CreateClient(); var token=await Login(f,c,$"offline-conflict-{Guid.NewGuid():N}@bee.test"); c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token); var player=f.Services.GetRequiredService<AuthenticationManager>().ValidateToken(token).PlayerId.Value; var hive=Guid.NewGuid(); var repo=f.Services.GetRequiredService<IHiveStateRepository>(); await repo.ExecuteAtomicallyAsync(player,hive,s=>s with { Resources=new Dictionary<string,ResourceBalance>{{"honey",new(0,100)},{"wax",new(0,100)},{"pollen",new(0,100)}}, OfflineProduction=new(DateTimeOffset.UtcNow.AddHours(1),new Dictionary<string,decimal>{{"honey_storage",10m},{"wax_workshop",5m},{"warehouse_cells",0m}},0,new Dictionary<string,OfflineProductionStoredReceipt>()) });
  var success=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",new{expectedProductionRevision=0,idempotencyKey="shared"}); Assert.That(success.StatusCode,Is.EqualTo(HttpStatusCode.OK));
  var stale=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/wax_workshop/collect",new{expectedProductionRevision=0,idempotencyKey="stale"}); Assert.That(stale.StatusCode,Is.EqualTo(HttpStatusCode.Conflict)); Assert.That((await stale.Content.ReadAsStringAsync()),Does.Contain("game.production_conflict"));
  var conflict=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/wax_workshop/collect",new{expectedProductionRevision=1,idempotencyKey="shared"}); Assert.That(conflict.StatusCode,Is.EqualTo(HttpStatusCode.Conflict)); Assert.That((await conflict.Content.ReadAsStringAsync()),Does.Contain("game.idempotency_conflict"));
 var state=(await repo.ReadAsync(player,hive))!; Assert.That(state.Resources["honey"].Amount,Is.EqualTo(10)); Assert.That(state.Resources["wax"].Amount,Is.EqualTo(0)); Assert.That(state.OfflineProduction!.PendingByBuilding["wax_workshop"],Is.EqualTo(5m).Within(0.001m)); Assert.That(decimal.Floor(state.OfflineProduction.PendingByBuilding["wax_workshop"]),Is.EqualTo(5m)); Assert.That(state.OfflineProduction.Receipts.Count,Is.EqualTo(1)); Assert.That(state.OfflineProduction.Revision,Is.EqualTo(1));
 }
 [Test] public async Task PostCapacityFullKeepsStateAndSameHiveIsIsolatedByPlayer()
 {
  await using var f=Create(true); using var c=f.CreateClient(); var auth=f.Services.GetRequiredService<AuthenticationManager>(); var repo=f.Services.GetRequiredService<IHiveStateRepository>();
  var tokenA=await Login(f,c,$"offline-capacity-a-{Guid.NewGuid():N}@bee.test"); var playerA=auth.ValidateToken(tokenA).PlayerId.Value; var hive=Guid.NewGuid(); c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",tokenA);
  await repo.ExecuteAtomicallyAsync(playerA,hive,s=>s with { Resources=new Dictionary<string,ResourceBalance>{{"honey",new(100,100)}, {"wax",new(0,100)}, {"pollen",new(0,100)}}, OfflineProduction=new(DateTimeOffset.UtcNow.AddHours(1),new Dictionary<string,decimal>{{"honey_storage",5m},{"wax_workshop",0m},{"warehouse_cells",0m}},0,new Dictionary<string,OfflineProductionStoredReceipt>()) });
  var blocked=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",new{expectedProductionRevision=0,idempotencyKey="a-full"}); Assert.That(blocked.StatusCode,Is.EqualTo(HttpStatusCode.Conflict)); Assert.That(await blocked.Content.ReadAsStringAsync(),Does.Contain("game.resource_capacity_full"));
  var aState=(await repo.ReadAsync(playerA,hive))!; Assert.That(aState.Resources["honey"].Amount,Is.EqualTo(100)); Assert.That(aState.OfflineProduction!.PendingByBuilding["honey_storage"],Is.EqualTo(5m).Within(0.001m)); Assert.That(aState.OfflineProduction.Receipts.Count,Is.EqualTo(0)); Assert.That(aState.OfflineProduction.Revision,Is.EqualTo(0));
  var tokenB=await Login(f,c,$"offline-capacity-b-{Guid.NewGuid():N}@bee.test"); var playerB=auth.ValidateToken(tokenB).PlayerId.Value; c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",tokenB);
  await repo.ExecuteAtomicallyAsync(playerB,hive,s=>s with { Resources=new Dictionary<string,ResourceBalance>{{"honey",new(0,100)}, {"wax",new(0,100)}, {"pollen",new(0,100)}}, OfflineProduction=new(DateTimeOffset.UtcNow.AddHours(1),new Dictionary<string,decimal>{{"honey_storage",2.5m},{"wax_workshop",0m},{"warehouse_cells",0m}},0,new Dictionary<string,OfflineProductionStoredReceipt>()) });
  var accepted=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",new{expectedProductionRevision=0,idempotencyKey="b"}); Assert.That(accepted.StatusCode,Is.EqualTo(HttpStatusCode.OK)); using var json=JsonDocument.Parse(await accepted.Content.ReadAsStringAsync()); Assert.That(json.RootElement.GetProperty("receipt").GetProperty("playerId").GetGuid(),Is.EqualTo(playerB)); Assert.That(json.RootElement.GetProperty("receipt").GetProperty("creditedAmount").GetInt64(),Is.EqualTo(2)); Assert.That(json.RootElement.GetProperty("receipt").GetProperty("remainingPending").GetDecimal(),Is.EqualTo(.5m)); Assert.That(json.RootElement.GetProperty("receipt").GetProperty("resultingBalance").GetProperty("amount").GetInt64(),Is.EqualTo(2));
 aState=(await repo.ReadAsync(playerA,hive))!; var bState=(await repo.ReadAsync(playerB,hive))!; Assert.That(aState.Resources["honey"].Amount,Is.EqualTo(100)); Assert.That(aState.OfflineProduction!.PendingByBuilding["honey_storage"],Is.EqualTo(5m).Within(0.001m)); Assert.That(aState.OfflineProduction.Receipts.Count,Is.EqualTo(0)); Assert.That(bState.Resources["honey"].Amount,Is.EqualTo(2)); Assert.That(bState.OfflineProduction!.PendingByBuilding["honey_storage"],Is.EqualTo(.5m).Within(0.001m));
 }
 [Test] public async Task GetAccruesAtConfiguredTwoHourCapWithExactAuthoritativeEnvelope()
 {
  await using var f=Create(true); using var c=f.CreateClient(); var auth=f.Services.GetRequiredService<AuthenticationManager>(); var repo=f.Services.GetRequiredService<IHiveStateRepository>(); var token=await Login(f,c,$"offline-cap-{Guid.NewGuid():N}@bee.test"); var player=auth.ValidateToken(token).PlayerId.Value; var hive=Guid.NewGuid(); c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);
  await repo.ExecuteAtomicallyAsync(player,hive,s=>s with { Resources=new Dictionary<string,ResourceBalance>{{"honey",new(11,100)}, {"wax",new(12,100)}, {"pollen",new(13,100)}}, OfflineProduction=new(DateTimeOffset.UtcNow.AddDays(-3),new Dictionary<string,decimal>{{"honey_storage",0m},{"wax_workshop",0m},{"warehouse_cells",0m}},0,new Dictionary<string,OfflineProductionStoredReceipt>()) });
  var response=await c.GetAsync($"/game/v1/hives/{hive}/offline-production"); Assert.That(response.StatusCode,Is.EqualTo(HttpStatusCode.OK)); Assert.That(response.Headers.CacheControl?.Private,Is.True); Assert.That(response.Headers.CacheControl?.NoStore,Is.True); Assert.That(response.Headers.Pragma.ToString(),Does.Contain("no-cache")); using var json=JsonDocument.Parse(await response.Content.ReadAsStringAsync()); var root=json.RootElement;
  Assert.That(root.GetProperty("playerId").GetGuid(),Is.EqualTo(player)); Assert.That(root.GetProperty("hiveId").GetGuid(),Is.EqualTo(hive)); Assert.That(root.GetProperty("contractVersion").GetString(),Is.EqualTo(HiveOfflineProductionService.ContractVersion)); Assert.That(root.GetProperty("catalogVersion").GetString(),Is.EqualTo("test-v1")); Assert.That(root.GetProperty("productionRevision").GetInt64(),Is.EqualTo(0)); Assert.That(root.GetProperty("serverTimeUtc").GetDateTimeOffset().Offset,Is.EqualTo(TimeSpan.Zero)); Assert.That(root.GetProperty("productionAsOfUtc").GetDateTimeOffset().Offset,Is.EqualTo(TimeSpan.Zero)); Assert.That(root.GetProperty("maxRecognizedDuration").GetString(),Is.EqualTo("02:00:00"));
  var lines=root.GetProperty("lines"); Assert.That(lines.GetArrayLength(),Is.EqualTo(3)); var expected=new Dictionary<string,(string resource,decimal pending,decimal rate)>{{"honey_storage",("honey",20m,10m)},{"wax_workshop",("wax",10m,5m)},{"warehouse_cells",("pollen",16m,8m)}}; foreach(var line in lines.EnumerateArray()){var key=line.GetProperty("buildingKey").GetString()!; Assert.That(expected.ContainsKey(key),Is.True); var e=expected[key]; Assert.That(line.GetProperty("resourceKey").GetString(),Is.EqualTo(e.resource)); Assert.That(line.GetProperty("pendingAmount").GetDecimal(),Is.EqualTo(e.pending)); Assert.That(line.GetProperty("hourlyRate").GetDecimal(),Is.EqualTo(e.rate)); Assert.That(line.GetProperty("capacity").GetDecimal(),Is.EqualTo(1000000000m)); Assert.That(line.GetProperty("collectableWholeUnits").GetInt64(),Is.EqualTo((long)e.pending)); }
  var balances=root.GetProperty("balances"); Assert.That(balances.GetProperty("honey").GetProperty("amount").GetInt64(),Is.EqualTo(11)); Assert.That(balances.GetProperty("wax").GetProperty("amount").GetInt64(),Is.EqualTo(12)); Assert.That(balances.GetProperty("pollen").GetProperty("amount").GetInt64(),Is.EqualTo(13)); var state=(await repo.ReadAsync(player,hive))!; Assert.That(state.OfflineProduction!.Revision,Is.EqualTo(0)); Assert.That(state.OfflineProduction.ProductionAsOfUtc.Offset,Is.EqualTo(TimeSpan.Zero)); Assert.That(state.OfflineProduction.ProductionAsOfUtc,Is.GreaterThan(DateTimeOffset.UtcNow.AddMinutes(-1)));
 }
 [Test] public async Task DailyRoundEnabledCollectMarksOnceAndReplaysWithoutMutation()
 {
  await using var f=Create(true,true); using var c=f.CreateClient(); var token=await Login(f,c,$"offline-daily-{Guid.NewGuid():N}@bee.test"); c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token); var player=f.Services.GetRequiredService<AuthenticationManager>().ValidateToken(token).PlayerId.Value; var hive=Guid.NewGuid(); var repo=f.Services.GetRequiredService<IHiveStateRepository>(); await repo.ExecuteAtomicallyAsync(player,hive,s=>s with{Resources=new Dictionary<string,ResourceBalance>{{"honey",new(0,100)}, {"wax",new(0,100)}, {"pollen",new(0,100)}}, OfflineProduction=new(DateTimeOffset.UtcNow.AddHours(1),new Dictionary<string,decimal>{{"honey_storage",1.5m},{"wax_workshop",0m},{"warehouse_cells",0m}},0,new Dictionary<string,OfflineProductionStoredReceipt>())}); var seed=await repo.ReadAsync(player,hive); var body=new{expectedProductionRevision=0,idempotencyKey="offline-daily"}; var first=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",body); Assert.That(first.StatusCode,Is.EqualTo(HttpStatusCode.OK)); var state=await repo.ReadAsync(player,hive); Assert.That(state!.DailyRound!.CollectionReceived,Is.True); Assert.That(state.Revision,Is.EqualTo(seed!.Revision+1)); Assert.That(state.Resources["honey"].Amount,Is.EqualTo(1)); var replay=await c.PostAsJsonAsync($"/game/v1/hives/{hive}/offline-production/honey_storage/collect",body); Assert.That(replay.StatusCode,Is.EqualTo(HttpStatusCode.OK)); var after=await repo.ReadAsync(player,hive); Assert.That(after!.Revision,Is.EqualTo(state.Revision)); Assert.That(after.Resources["honey"].Amount,Is.EqualTo(1)); Assert.That(after.OfflineProduction!.PendingByBuilding["honey_storage"],Is.EqualTo(.5m)); Assert.That(after.DailyRound,Is.EqualTo(state.DailyRound));
 }
 private static WebApplicationFactory<Program> Create(bool enabled,bool daily=false){var d=new Dictionary<string,string?>{{"HiveOfflineProduction:Enabled",enabled.ToString().ToLowerInvariant()},{"HiveOfflineProduction:CatalogVersion",enabled?"test-v1":""},{"HiveOfflineProduction:MaxRecognizedDuration","0.02:00:00"},{"HiveDailyRound:Enabled",daily.ToString().ToLowerInvariant()}};if(enabled){d["HiveOfflineProduction:Catalog:0:BuildingKey"]="honey_storage";d["HiveOfflineProduction:Catalog:0:ResourceKey"]="honey";d["HiveOfflineProduction:Catalog:0:HourlyRate"]="10";d["HiveOfflineProduction:Catalog:0:Capacity"]="1000000000";d["HiveOfflineProduction:Catalog:1:BuildingKey"]="wax_workshop";d["HiveOfflineProduction:Catalog:1:ResourceKey"]="wax";d["HiveOfflineProduction:Catalog:1:HourlyRate"]="5";d["HiveOfflineProduction:Catalog:1:Capacity"]="1000000000";d["HiveOfflineProduction:Catalog:2:BuildingKey"]="warehouse_cells";d["HiveOfflineProduction:Catalog:2:ResourceKey"]="pollen";d["HiveOfflineProduction:Catalog:2:HourlyRate"]="8";d["HiveOfflineProduction:Catalog:2:Capacity"]="1000000000";}return new WebApplicationFactory<Program>().WithWebHostBuilder(b=>{b.UseSetting("environment","Development");b.ConfigureAppConfiguration((_,c)=>c.AddInMemoryCollection(d));});}
 private static async Task<string> Login(WebApplicationFactory<Program> f,HttpClient c,string email){f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(email,"secret");var r=await c.PostAsJsonAsync("/auth/login",new{email,password="secret",clientVersion="1.0"});using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync());return j.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;}
}
