using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using BeeKingdom.Authentication;
using AuthenticationManager = BeeKingdom.Authentication.AuthenticationManager;
using BeeKingdom.Authentication.Providers;
using BeeKingdom.HiveOperations;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace BeeKingdom.Tests;
public sealed class LivingHiveResearchEndpointTests
{
 [Test] public async Task ClosedFlagReturns503BeforeAuth(){await using var f=Create(false);using var c=f.CreateClient();var r=await c.GetAsync($"/game/v1/hives/{Guid.NewGuid()}/research");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.ServiceUnavailable));}
 [Test] public async Task EnabledRequiresBearer(){await using var f=Create(true);using var c=f.CreateClient();var r=await c.GetAsync($"/game/v1/hives/{Guid.NewGuid()}/research");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.Unauthorized));}
 [Test] public async Task EnabledGetUsesStructuredEffects(){await using var f=Create(true);using var c=f.CreateClient();var email=$"research-{Guid.NewGuid():N}@bee.test";f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(email,"secret");var login=await c.PostAsJsonAsync("/auth/login",new{email,password="secret",clientVersion="1.0"});using var auth=JsonDocument.Parse(await login.Content.ReadAsStringAsync());var token=auth.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var p=f.Services.GetRequiredService<AuthenticationManager>().ValidateToken(token).PlayerId!.Value;var h=Guid.NewGuid();await f.Services.GetRequiredService<IHiveStateRepository>().ExecuteAtomicallyAsync(p,h,s=>s with{Resources=new Dictionary<string,ResourceBalance>{{"honey",new(500,1000)},{"pollen",new(500,1000)},{"wax",new(0,1000)}}});var r=await c.GetAsync($"/game/v1/hives/{h}/research");Assert.That(r.StatusCode,Is.EqualTo(HttpStatusCode.OK));using var json=JsonDocument.Parse(await r.Content.ReadAsStringAsync());var offer=json.RootElement.GetProperty("offers")[0];Assert.That(offer.GetProperty("effects").GetProperty("honeyProductionBonusBps").GetInt32(),Is.EqualTo(200));Assert.That(offer.GetProperty("effects").GetProperty("waxCapacityBonusBps").GetInt32(),Is.EqualTo(0));}
 [Test] public async Task EnabledEmptyCatalogExposesNoOffersAndDoesNotMutate(){await using var f=Create(true,false);using var c=f.CreateClient();var email=$"research-empty-{Guid.NewGuid():N}@bee.test";f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(email,"secret");var login=await c.PostAsJsonAsync("/auth/login",new{email,password="secret",clientVersion="1.0"});using var auth=JsonDocument.Parse(await login.Content.ReadAsStringAsync());var token=auth.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var p=f.Services.GetRequiredService<AuthenticationManager>().ValidateToken(token).PlayerId!.Value;var h=Guid.NewGuid();await f.Services.GetRequiredService<IHiveStateRepository>().ExecuteAtomicallyAsync(p,h,s=>s with{Resources=new Dictionary<string,ResourceBalance>{{"honey",new(500,1000)},{"pollen",new(500,1000)},{"wax",new(0,1000)}}});var get=await c.GetAsync($"/game/v1/hives/{h}/research");Assert.That(get.StatusCode,Is.EqualTo(HttpStatusCode.OK));using var doc=JsonDocument.Parse(await get.Content.ReadAsStringAsync());Assert.That(doc.RootElement.GetProperty("offers").GetArrayLength(),Is.EqualTo(0));var start=await c.PostAsJsonAsync($"/game/v1/hives/{h}/research/foraging_routes_i/start",new{expectedRevision=0,idempotencyKey="empty-catalog"});Assert.That(start.StatusCode,Is.EqualTo(HttpStatusCode.BadRequest));var state=await f.Services.GetRequiredService<IHiveStateRepository>().ReadAsync(p,h);Assert.That(state,Is.Not.Null);Assert.That(state!.Research?.ActiveOperation,Is.Null);}
 [Test] public async Task StartWithDailyRoundMarksOnceAndReplaysWithoutSecondDebit(){await using var f=Create(true,true,true);using var c=f.CreateClient();var email=$"research-daily-{Guid.NewGuid():N}@bee.test";f.Services.GetRequiredService<IAccountCredentialStore>().CreateEmailAccount(email,"secret");var login=await c.PostAsJsonAsync("/auth/login",new{email,password="secret",clientVersion="1.0"});using var auth=JsonDocument.Parse(await login.Content.ReadAsStringAsync());var token=auth.RootElement.GetProperty("tokens").GetProperty("accessToken").GetString()!;c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var p=f.Services.GetRequiredService<AuthenticationManager>().ValidateToken(token).PlayerId!.Value;var h=Guid.NewGuid();var repo=f.Services.GetRequiredService<IHiveStateRepository>();await repo.ExecuteAtomicallyAsync(p,h,s=>s with{Resources=new Dictionary<string,ResourceBalance>{{"honey",new(500,1000)},{"pollen",new(500,1000)},{"wax",new(0,1000)}},Research=new(new Dictionary<string,ResearchCompletion>(),null)});var seed=await repo.ReadAsync(p,h);var body=new{expectedRevision=seed!.Revision,idempotencyKey="research-daily"};var first=await c.PostAsJsonAsync($"/game/v1/hives/{h}/research/foraging_routes_i/start",body);Assert.That(first.StatusCode,Is.EqualTo(HttpStatusCode.OK));var state=await repo.ReadAsync(p,h);Assert.That(state!.DailyRound!.OperationLaunched,Is.True);Assert.That(state.Revision,Is.EqualTo(seed.Revision+1));Assert.That(state.Resources["honey"].Amount,Is.EqualTo(260));Assert.That(state.Resources["pollen"].Amount,Is.EqualTo(410));var replay=await c.PostAsJsonAsync($"/game/v1/hives/{h}/research/foraging_routes_i/start",body);Assert.That(replay.StatusCode,Is.EqualTo(HttpStatusCode.OK));var after=await repo.ReadAsync(p,h);Assert.That(after!.Revision,Is.EqualTo(state.Revision));Assert.That(after.Resources["honey"].Amount,Is.EqualTo(260));Assert.That(after.DailyRound,Is.EqualTo(state.DailyRound));}
 private static WebApplicationFactory<Program> Create(bool enabled, bool withCatalog=true,bool daily=false){var d=new Dictionary<string,string?>{{"LivingHiveResearch:Enabled",enabled.ToString().ToLowerInvariant()},{"LivingHiveResearch:CatalogVersion",enabled&&withCatalog?"phase-test-v1":""},{"HiveDailyRound:Enabled",daily.ToString().ToLowerInvariant()}}; if(enabled&&withCatalog){d["LivingHiveResearch:Catalog:0"]="foraging_routes_i";d["LivingHiveResearch:Catalog:1"]="tempered_combs_i";} return new WebApplicationFactory<Program>().WithWebHostBuilder(b=>{b.UseSetting("environment","Development");b.ConfigureAppConfiguration((_,c)=>c.AddInMemoryCollection(d));});}
}
