using System;
using System.Collections.Generic;
using System.Linq;

namespace BeeKingdom.Colony
{
    public enum ActivationReadinessDiagnosticCode { MissingRequiredCoverage, MissingExplanation, MissingServerBoundary, ForbiddenOfficialClaim, MissingEvidence, MissingTeamLane, Bee521Premature }
    public enum PostMilestoneStabilityVerdict { StableForNextReadinessLot, StableWithReserves, BlockedByRegression, BlockedByLiveClaim }
    public enum MobileNavigationAuditVerdict { Acceptable, NeedsUiClarification, BlockedByMissingBackPath, BlockedByLiveConfusion }
    public enum HiveActionActivationReadiness { ReadyForDesign, NeedsUiClarification, NeedsServerSpecification, BlockedByEconomyRisk, BlockedByQaRisk }
    public enum ServerCommandReadinessVerdict { ReadyForServerReview, BlockedByImplementationLeak, BlockedByMissingQuestions }
    public enum ResourceEconomyBoundaryVerdict { PreviewSafe, NeedsPlayerClarification, BlockedByOfficialEconomyClaim }
    public enum ConstructionUpgradeBoundaryVerdict { PreviewSafe, NeedsPrerequisiteClarification, BlockedByActivationClaim }
    public enum WorkforceBoundaryVerdict { PreviewSafe, NeedsSuggestionClarification, BlockedByOfficialMutationClaim }
    public enum SocialActivationBoundaryVerdict { PreviewSafe, NeedsDisclosureClarification, BlockedByLiveSocialClaim }
    public enum WorldScoutingBoundaryVerdict { PreviewSafe, NeedsReturnClarification, BlockedByLiveMapClaim }
    public enum DefenseCombatBoundaryVerdict { PreviewSafe, NeedsToneClarification, BlockedByCombatClaim }
    public enum PlayerProfileReadinessVerdict { PreviewSafe, NeedsAccountClarification, BlockedByOfficialAccountClaim }
    public enum NotificationInboxBoundaryVerdict { PreviewSafe, NeedsEmptyStateClarification, BlockedByDeliveryClaim }
    public enum EventParticipationBoundaryVerdict { PreviewSafe, NeedsPrerequisiteClarification, BlockedByLiveOpsClaim }
    public enum TradeMarketBoundaryVerdict { PreviewSafe, NeedsMarketClarification, BlockedByMarketClaim }
    public enum ResearchGeneticsBoundaryVerdict { PreviewSafe, NeedsBalanceReview, BlockedByOfficialEffectClaim }
    public enum OnboardingPersistenceDecisionVerdict { StorageForbiddenNow, ReadyForFutureDecision, BlockedByPrivacyRisk }
    public enum AccessibilityLocalizationVerdict { ReadyForReview, NeedsCopyRevision, BlockedByLiveVerbRisk }
    public enum PerformanceBudgetPreviewVerdict { ReadyForPreview, NeedsMitigation, BlockedByBenchmarkClaim }
    public enum Bee600DemoRoadmapVerdict { ReadyForBEE600Planning, ReadyWithReserves, BlockedByLiveDemoClaim }
    public enum ActivationReadinessLotVerdict { ReadyForArchitectValidation, ReadyWithOpenReserves, NeedsTeamRevision, BlockedByLiveClaim, BlockedByHiddenServerService, BlockedByMissingEvidence, BlockedByBee521Premature }
    public enum Bee521BlockerStatus { BlockedUntilArchitectValidation, StillBlockedAfterRevision, ReleasedByFutureArchitectDecision }

    public sealed class PostMilestoneInvariant { public PostMilestoneInvariant(string invariantId, string playerSurface, string requiredBehavior, string regressionSignal) { InvariantId = invariantId ?? string.Empty; PlayerSurface = playerSurface ?? string.Empty; RequiredBehavior = requiredBehavior ?? string.Empty; RegressionSignal = regressionSignal ?? string.Empty; } public string InvariantId { get; } public string PlayerSurface { get; } public string RequiredBehavior { get; } public string RegressionSignal { get; } }
    public sealed class PostMilestoneReserve { public PostMilestoneReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class PlayableSlicePostMilestoneStabilization
    {
        private static readonly string[] Required = { "HomeAlwaysReachable", "HiveStateReadable", "OnePrimaryIntentVisible", "BlockedActionExplained", "Demo500ReserveShownInternally", "NoLiveRuntimeClaim" };
        public PlayableSlicePostMilestoneStabilization(string id, IReadOnlyList<PostMilestoneInvariant> invariants, IReadOnlyList<PostMilestoneReserve> reserves) { Id = ColonyIntegrationIds.Require(id); Invariants = invariants ?? Array.Empty<PostMilestoneInvariant>(); Reserves = reserves ?? Array.Empty<PostMilestoneReserve>(); Verdict = EvaluateVerdict(); }
        public string Id { get; } public IReadOnlyList<PostMilestoneInvariant> Invariants { get; } public IReadOnlyList<PostMilestoneReserve> Reserves { get; } public PostMilestoneStabilityVerdict Verdict { get; }
        private PostMilestoneStabilityVerdict EvaluateVerdict() { if (Required.Any(r => Invariants.All(i => !ActivationReadinessText.Same(i.InvariantId, r)))) return PostMilestoneStabilityVerdict.BlockedByRegression; if (Invariants.Any(i => ActivationReadinessText.Contains(i.RegressionSignal, "live"))) return PostMilestoneStabilityVerdict.BlockedByLiveClaim; return Reserves.Count > 0 ? PostMilestoneStabilityVerdict.StableWithReserves : PostMilestoneStabilityVerdict.StableForNextReadinessLot; }
    }

    public sealed class MobileRouteFriction { public MobileRouteFriction(string routeId, string entryPoint, string exitPath, string frictionReason, int severity) { RouteId = routeId ?? string.Empty; EntryPoint = entryPoint ?? string.Empty; ExitPath = exitPath ?? string.Empty; FrictionReason = frictionReason ?? string.Empty; Severity = severity; } public string RouteId { get; } public string EntryPoint { get; } public string ExitPath { get; } public string FrictionReason { get; } public int Severity { get; } }
    public sealed class MobileNavigationRecommendation { public MobileNavigationRecommendation(string recommendationId, string text) { RecommendationId = recommendationId ?? string.Empty; Text = text ?? string.Empty; } public string RecommendationId { get; } public string Text { get; } }
    public sealed class MobileNavigationFrictionAudit
    {
        public MobileNavigationFrictionAudit(string id, IReadOnlyList<MobileRouteFriction> routeFrictions, IReadOnlyList<MobileNavigationRecommendation> recommendations) { Id = ColonyIntegrationIds.Require(id); RouteFrictions = routeFrictions ?? Array.Empty<MobileRouteFriction>(); Recommendations = recommendations ?? Array.Empty<MobileNavigationRecommendation>(); Verdict = EvaluateVerdict(); }
        public string Id { get; } public IReadOnlyList<MobileRouteFriction> RouteFrictions { get; } public IReadOnlyList<MobileNavigationRecommendation> Recommendations { get; } public MobileNavigationAuditVerdict Verdict { get; }
        private MobileNavigationAuditVerdict EvaluateVerdict() { if (RouteFrictions.Any(f => string.IsNullOrWhiteSpace(f.ExitPath) || ActivationReadinessText.Contains(f.FrictionReason, "MissingBackPath"))) return MobileNavigationAuditVerdict.BlockedByMissingBackPath; if (RouteFrictions.Any(f => ActivationReadinessText.Contains(f.FrictionReason, "live") || ActivationReadinessText.Contains(f.FrictionReason, "DuplicatePrimaryAction"))) return MobileNavigationAuditVerdict.BlockedByLiveConfusion; return RouteFrictions.Any(f => f.Severity >= 3) || Recommendations.Count > 0 ? MobileNavigationAuditVerdict.NeedsUiClarification : MobileNavigationAuditVerdict.Acceptable; }
    }

    public sealed class HiveActionActivationCandidate { public HiveActionActivationCandidate(string actionId, string playerIntent, string requiredPreviewProof, string futureAuthorityOwner, string activationRisk) { ActionId = actionId ?? string.Empty; PlayerIntent = playerIntent ?? string.Empty; RequiredPreviewProof = requiredPreviewProof ?? string.Empty; FutureAuthorityOwner = futureAuthorityOwner ?? string.Empty; ActivationRisk = activationRisk ?? string.Empty; } public string ActionId { get; } public string PlayerIntent { get; } public string RequiredPreviewProof { get; } public string FutureAuthorityOwner { get; } public string ActivationRisk { get; } }
    public sealed class HiveActionActivationBlocker { public HiveActionActivationBlocker(string actionId, string reason) { ActionId = actionId ?? string.Empty; Reason = reason ?? string.Empty; } public string ActionId { get; } public string Reason { get; } }
    public sealed class HiveActionActivationCandidateRegistry
    {
        private static readonly string[] Required = { "UpgradeRoom", "PlaceConstruction", "QueueProduction", "AssignWorker", "ResolveShortage", "PrepareDefense", "SelectResearch", "ReviewRecapAction" };
        public HiveActionActivationCandidateRegistry(string id, IReadOnlyList<HiveActionActivationCandidate> candidates, IReadOnlyList<HiveActionActivationBlocker> blockers) { Id = ColonyIntegrationIds.Require(id); Candidates = candidates ?? Array.Empty<HiveActionActivationCandidate>(); Blockers = blockers ?? Array.Empty<HiveActionActivationBlocker>(); Readiness = EvaluateReadiness(); }
        public string Id { get; } public IReadOnlyList<HiveActionActivationCandidate> Candidates { get; } public IReadOnlyList<HiveActionActivationBlocker> Blockers { get; } public HiveActionActivationReadiness Readiness { get; }
        private HiveActionActivationReadiness EvaluateReadiness() { if (Required.Any(r => Candidates.All(c => !ActivationReadinessText.Same(c.ActionId, r)))) return HiveActionActivationReadiness.NeedsUiClarification; if (Candidates.Any(c => string.IsNullOrWhiteSpace(c.FutureAuthorityOwner))) return HiveActionActivationReadiness.NeedsServerSpecification; if (Blockers.Any(b => ActivationReadinessText.Contains(b.Reason, "economy"))) return HiveActionActivationReadiness.BlockedByEconomyRisk; if (Blockers.Count > 0) return HiveActionActivationReadiness.BlockedByQaRisk; return HiveActionActivationReadiness.ReadyForDesign; }
    }

    public sealed class FutureCommandReadinessRow { public FutureCommandReadinessRow(string candidateActionId, string futureCommandName, string requiredValidationQuestion, string rejectionReasonToDefine, bool implementationForbiddenNow) { CandidateActionId = candidateActionId ?? string.Empty; FutureCommandName = futureCommandName ?? string.Empty; RequiredValidationQuestion = requiredValidationQuestion ?? string.Empty; RejectionReasonToDefine = rejectionReasonToDefine ?? string.Empty; ImplementationForbiddenNow = implementationForbiddenNow; } public string CandidateActionId { get; } public string FutureCommandName { get; } public string RequiredValidationQuestion { get; } public string RejectionReasonToDefine { get; } public bool ImplementationForbiddenNow { get; } }
    public sealed class ServerReadinessExclusion { public ServerReadinessExclusion(string exclusionId, string reason) { ExclusionId = exclusionId ?? string.Empty; Reason = reason ?? string.Empty; } public string ExclusionId { get; } public string Reason { get; } }
    public sealed class ServerCommandReadinessChecklist { public ServerCommandReadinessChecklist(string id, IReadOnlyList<FutureCommandReadinessRow> rows, IReadOnlyList<ServerReadinessExclusion> exclusions) { Id = ColonyIntegrationIds.Require(id); Rows = rows ?? Array.Empty<FutureCommandReadinessRow>(); Exclusions = exclusions ?? Array.Empty<ServerReadinessExclusion>(); Verdict = Rows.Any(r => !r.ImplementationForbiddenNow) ? ServerCommandReadinessVerdict.BlockedByImplementationLeak : Rows.Any(r => string.IsNullOrWhiteSpace(r.RequiredValidationQuestion) || string.IsNullOrWhiteSpace(r.RejectionReasonToDefine)) ? ServerCommandReadinessVerdict.BlockedByMissingQuestions : ServerCommandReadinessVerdict.ReadyForServerReview; } public string Id { get; } public IReadOnlyList<FutureCommandReadinessRow> Rows { get; } public IReadOnlyList<ServerReadinessExclusion> Exclusions { get; } public ServerCommandReadinessVerdict Verdict { get; } }

    public sealed class ResourceBoundaryRule { public ResourceBoundaryRule(string resourceId, string previewMeaning, string forbiddenOfficialMeaning, string requiredPlayerExplanation) { ResourceId = resourceId ?? string.Empty; PreviewMeaning = previewMeaning ?? string.Empty; ForbiddenOfficialMeaning = forbiddenOfficialMeaning ?? string.Empty; RequiredPlayerExplanation = requiredPlayerExplanation ?? string.Empty; } public string ResourceId { get; } public string PreviewMeaning { get; } public string ForbiddenOfficialMeaning { get; } public string RequiredPlayerExplanation { get; } }
    public sealed class ResourcePreviewScenario { public ResourcePreviewScenario(string scenarioId, string expectedExplanation) { ScenarioId = scenarioId ?? string.Empty; ExpectedExplanation = expectedExplanation ?? string.Empty; } public string ScenarioId { get; } public string ExpectedExplanation { get; } }
    public sealed class ResourceEconomyActivationBoundary { public ResourceEconomyActivationBoundary(string id, IReadOnlyList<ResourceBoundaryRule> rules, IReadOnlyList<ResourcePreviewScenario> previewScenarios) { Id = ColonyIntegrationIds.Require(id); Rules = rules ?? Array.Empty<ResourceBoundaryRule>(); PreviewScenarios = previewScenarios ?? Array.Empty<ResourcePreviewScenario>(); Verdict = Rules.Any(r => ActivationReadinessText.Contains(r.ForbiddenOfficialMeaning, "official") || ActivationReadinessText.Contains(r.ForbiddenOfficialMeaning, "depense")) ? ResourceEconomyBoundaryVerdict.PreviewSafe : ResourceEconomyBoundaryVerdict.NeedsPlayerClarification; if (Rules.Any(r => ActivationReadinessText.Contains(r.PreviewMeaning, "official"))) Verdict = ResourceEconomyBoundaryVerdict.BlockedByOfficialEconomyClaim; } public string Id { get; } public IReadOnlyList<ResourceBoundaryRule> Rules { get; } public IReadOnlyList<ResourcePreviewScenario> PreviewScenarios { get; } public ResourceEconomyBoundaryVerdict Verdict { get; } }

    public sealed class ConstructionUpgradeCandidate { public ConstructionUpgradeCandidate(string roomId, string upgradeId, string previewBenefit, string missingRequirementText, string futureAuthorityNeed) { RoomId = roomId ?? string.Empty; UpgradeId = upgradeId ?? string.Empty; PreviewBenefit = previewBenefit ?? string.Empty; MissingRequirementText = missingRequirementText ?? string.Empty; FutureAuthorityNeed = futureAuthorityNeed ?? string.Empty; } public string RoomId { get; } public string UpgradeId { get; } public string PreviewBenefit { get; } public string MissingRequirementText { get; } public string FutureAuthorityNeed { get; } }
    public sealed class ConstructionActivationRule { public ConstructionActivationRule(string ruleId, string forbiddenActivationClaim) { RuleId = ruleId ?? string.Empty; ForbiddenActivationClaim = forbiddenActivationClaim ?? string.Empty; } public string RuleId { get; } public string ForbiddenActivationClaim { get; } }
    public sealed class ConstructionUpgradeActivationBoundary { public ConstructionUpgradeActivationBoundary(string id, IReadOnlyList<ConstructionUpgradeCandidate> upgradeCandidates, IReadOnlyList<ConstructionActivationRule> activationRules) { Id = ColonyIntegrationIds.Require(id); UpgradeCandidates = upgradeCandidates ?? Array.Empty<ConstructionUpgradeCandidate>(); ActivationRules = activationRules ?? Array.Empty<ConstructionActivationRule>(); Verdict = UpgradeCandidates.Any(c => string.IsNullOrWhiteSpace(c.MissingRequirementText)) ? ConstructionUpgradeBoundaryVerdict.NeedsPrerequisiteClarification : ActivationRules.Any(r => ActivationReadinessText.Contains(r.ForbiddenActivationClaim, "active")) ? ConstructionUpgradeBoundaryVerdict.BlockedByActivationClaim : ConstructionUpgradeBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<ConstructionUpgradeCandidate> UpgradeCandidates { get; } public IReadOnlyList<ConstructionActivationRule> ActivationRules { get; } public ConstructionUpgradeBoundaryVerdict Verdict { get; } }

    public sealed class WorkforceNeedPreview { public WorkforceNeedPreview(string needId, string beeRole, int previewRequiredCount, string blockerText, string officialMutationForbiddenReason) { NeedId = needId ?? string.Empty; BeeRole = beeRole ?? string.Empty; PreviewRequiredCount = previewRequiredCount; BlockerText = blockerText ?? string.Empty; OfficialMutationForbiddenReason = officialMutationForbiddenReason ?? string.Empty; } public string NeedId { get; } public string BeeRole { get; } public int PreviewRequiredCount { get; } public string BlockerText { get; } public string OfficialMutationForbiddenReason { get; } }
    public sealed class WorkforceAssignmentSuggestion { public WorkforceAssignmentSuggestion(string suggestionId, string previewImpact, bool mutatesOfficialPopulation = false) { SuggestionId = suggestionId ?? string.Empty; PreviewImpact = previewImpact ?? string.Empty; MutatesOfficialPopulation = mutatesOfficialPopulation; } public string SuggestionId { get; } public string PreviewImpact { get; } public bool MutatesOfficialPopulation { get; } }
    public sealed class WorkforceAssignmentActivationBoundary { public WorkforceAssignmentActivationBoundary(string id, IReadOnlyList<WorkforceNeedPreview> needs, IReadOnlyList<WorkforceAssignmentSuggestion> suggestions) { Id = ColonyIntegrationIds.Require(id); Needs = needs ?? Array.Empty<WorkforceNeedPreview>(); Suggestions = suggestions ?? Array.Empty<WorkforceAssignmentSuggestion>(); Verdict = Suggestions.Any(s => s.MutatesOfficialPopulation) ? WorkforceBoundaryVerdict.BlockedByOfficialMutationClaim : Suggestions.Count == 0 || Needs.Any(n => string.IsNullOrWhiteSpace(n.BlockerText)) ? WorkforceBoundaryVerdict.NeedsSuggestionClarification : WorkforceBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<WorkforceNeedPreview> Needs { get; } public IReadOnlyList<WorkforceAssignmentSuggestion> Suggestions { get; } public WorkforceBoundaryVerdict Verdict { get; } }

    public sealed class SocialPreviewSurfaceRule { public SocialPreviewSurfaceRule(string surfaceId, string previewCapability, string forbiddenLiveCapability, string requiredDisclosureText) { SurfaceId = surfaceId ?? string.Empty; PreviewCapability = previewCapability ?? string.Empty; ForbiddenLiveCapability = forbiddenLiveCapability ?? string.Empty; RequiredDisclosureText = requiredDisclosureText ?? string.Empty; } public string SurfaceId { get; } public string PreviewCapability { get; } public string ForbiddenLiveCapability { get; } public string RequiredDisclosureText { get; } }
    public sealed class SocialLiveClaimRisk { public SocialLiveClaimRisk(string riskId, string description, bool liveClaim) { RiskId = riskId ?? string.Empty; Description = description ?? string.Empty; LiveClaim = liveClaim; } public string RiskId { get; } public string Description { get; } public bool LiveClaim { get; } }
    public sealed class AllianceCommunicationActivationBoundary { public AllianceCommunicationActivationBoundary(string id, IReadOnlyList<SocialPreviewSurfaceRule> surfaceRules, IReadOnlyList<SocialLiveClaimRisk> liveClaimRisks) { Id = ColonyIntegrationIds.Require(id); SurfaceRules = surfaceRules ?? Array.Empty<SocialPreviewSurfaceRule>(); LiveClaimRisks = liveClaimRisks ?? Array.Empty<SocialLiveClaimRisk>(); Verdict = LiveClaimRisks.Any(r => r.LiveClaim) ? SocialActivationBoundaryVerdict.BlockedByLiveSocialClaim : SurfaceRules.Any(r => string.IsNullOrWhiteSpace(r.RequiredDisclosureText)) ? SocialActivationBoundaryVerdict.NeedsDisclosureClarification : SocialActivationBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<SocialPreviewSurfaceRule> SurfaceRules { get; } public IReadOnlyList<SocialLiveClaimRisk> LiveClaimRisks { get; } public SocialActivationBoundaryVerdict Verdict { get; } }

    public sealed class ScoutingReportPreview { public ScoutingReportPreview(string reportId, string regionHint, string resourceHypothesis, string riskHint, string returnToHivePrompt) { ReportId = reportId ?? string.Empty; RegionHint = regionHint ?? string.Empty; ResourceHypothesis = resourceHypothesis ?? string.Empty; RiskHint = riskHint ?? string.Empty; ReturnToHivePrompt = returnToHivePrompt ?? string.Empty; } public string ReportId { get; } public string RegionHint { get; } public string ResourceHypothesis { get; } public string RiskHint { get; } public string ReturnToHivePrompt { get; } }
    public sealed class ScoutingOfficialClaimBlocker { public ScoutingOfficialClaimBlocker(string blockerId, string forbiddenClaim) { BlockerId = blockerId ?? string.Empty; ForbiddenClaim = forbiddenClaim ?? string.Empty; } public string BlockerId { get; } public string ForbiddenClaim { get; } }
    public sealed class WorldScoutingReportActivationBoundary { public WorldScoutingReportActivationBoundary(string id, IReadOnlyList<ScoutingReportPreview> reports, IReadOnlyList<ScoutingOfficialClaimBlocker> claimBlockers) { Id = ColonyIntegrationIds.Require(id); Reports = reports ?? Array.Empty<ScoutingReportPreview>(); ClaimBlockers = claimBlockers ?? Array.Empty<ScoutingOfficialClaimBlocker>(); Verdict = ClaimBlockers.Any(b => ActivationReadinessText.Contains(b.ForbiddenClaim, "live map")) ? WorldScoutingBoundaryVerdict.BlockedByLiveMapClaim : Reports.Any(r => string.IsNullOrWhiteSpace(r.ReturnToHivePrompt)) ? WorldScoutingBoundaryVerdict.NeedsReturnClarification : WorldScoutingBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<ScoutingReportPreview> Reports { get; } public IReadOnlyList<ScoutingOfficialClaimBlocker> ClaimBlockers { get; } public WorldScoutingBoundaryVerdict Verdict { get; } }

    public sealed class DefenseReadinessSignal { public DefenseReadinessSignal(string signalId, string defensiveMeaning, string playerAdvicePreview, string forbiddenCombatMeaning) { SignalId = signalId ?? string.Empty; DefensiveMeaning = defensiveMeaning ?? string.Empty; PlayerAdvicePreview = playerAdvicePreview ?? string.Empty; ForbiddenCombatMeaning = forbiddenCombatMeaning ?? string.Empty; } public string SignalId { get; } public string DefensiveMeaning { get; } public string PlayerAdvicePreview { get; } public string ForbiddenCombatMeaning { get; } }
    public sealed class CombatLiveClaimBlocker { public CombatLiveClaimBlocker(string blockerId, string claim, bool combatClaim) { BlockerId = blockerId ?? string.Empty; Claim = claim ?? string.Empty; CombatClaim = combatClaim; } public string BlockerId { get; } public string Claim { get; } public bool CombatClaim { get; } }
    public sealed class DefenseCombatActivationBoundary { public DefenseCombatActivationBoundary(string id, IReadOnlyList<DefenseReadinessSignal> readinessSignals, IReadOnlyList<CombatLiveClaimBlocker> claimBlockers) { Id = ColonyIntegrationIds.Require(id); ReadinessSignals = readinessSignals ?? Array.Empty<DefenseReadinessSignal>(); ClaimBlockers = claimBlockers ?? Array.Empty<CombatLiveClaimBlocker>(); Verdict = ClaimBlockers.Any(b => b.CombatClaim) ? DefenseCombatBoundaryVerdict.BlockedByCombatClaim : ReadinessSignals.Any(s => string.IsNullOrWhiteSpace(s.PlayerAdvicePreview)) ? DefenseCombatBoundaryVerdict.NeedsToneClarification : DefenseCombatBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<DefenseReadinessSignal> ReadinessSignals { get; } public IReadOnlyList<CombatLiveClaimBlocker> ClaimBlockers { get; } public DefenseCombatBoundaryVerdict Verdict { get; } }

    public sealed class PlayerProfilePreviewField { public PlayerProfilePreviewField(string fieldId, string previewValueMeaning, string forbiddenOfficialMeaning, string futureServerQuestion) { FieldId = fieldId ?? string.Empty; PreviewValueMeaning = previewValueMeaning ?? string.Empty; ForbiddenOfficialMeaning = forbiddenOfficialMeaning ?? string.Empty; FutureServerQuestion = futureServerQuestion ?? string.Empty; } public string FieldId { get; } public string PreviewValueMeaning { get; } public string ForbiddenOfficialMeaning { get; } public string FutureServerQuestion { get; } }
    public sealed class AccountAuthorityBlocker { public AccountAuthorityBlocker(string blockerId, string officialAccountClaim, bool accountClaim) { BlockerId = blockerId ?? string.Empty; OfficialAccountClaim = officialAccountClaim ?? string.Empty; AccountClaim = accountClaim; } public string BlockerId { get; } public string OfficialAccountClaim { get; } public bool AccountClaim { get; } }
    public sealed class PlayerAccountProfileReadinessPreview { public PlayerAccountProfileReadinessPreview(string id, IReadOnlyList<PlayerProfilePreviewField> fields, IReadOnlyList<AccountAuthorityBlocker> authorityBlockers) { Id = ColonyIntegrationIds.Require(id); Fields = fields ?? Array.Empty<PlayerProfilePreviewField>(); AuthorityBlockers = authorityBlockers ?? Array.Empty<AccountAuthorityBlocker>(); Verdict = AuthorityBlockers.Any(b => b.AccountClaim) ? PlayerProfileReadinessVerdict.BlockedByOfficialAccountClaim : Fields.Any(f => string.IsNullOrWhiteSpace(f.FutureServerQuestion)) ? PlayerProfileReadinessVerdict.NeedsAccountClarification : PlayerProfileReadinessVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<PlayerProfilePreviewField> Fields { get; } public IReadOnlyList<AccountAuthorityBlocker> AuthorityBlockers { get; } public PlayerProfileReadinessVerdict Verdict { get; } }

    public sealed class InboxPreviewMessageRule { public InboxPreviewMessageRule(string messageKind, string previewPurpose, string allowedVisualState, string forbiddenDeliveryClaim) { MessageKind = messageKind ?? string.Empty; PreviewPurpose = previewPurpose ?? string.Empty; AllowedVisualState = allowedVisualState ?? string.Empty; ForbiddenDeliveryClaim = forbiddenDeliveryClaim ?? string.Empty; } public string MessageKind { get; } public string PreviewPurpose { get; } public string AllowedVisualState { get; } public string ForbiddenDeliveryClaim { get; } }
    public sealed class NotificationDeliveryBlocker { public NotificationDeliveryBlocker(string blockerId, string deliveryClaim, bool liveDeliveryClaim) { BlockerId = blockerId ?? string.Empty; DeliveryClaim = deliveryClaim ?? string.Empty; LiveDeliveryClaim = liveDeliveryClaim; } public string BlockerId { get; } public string DeliveryClaim { get; } public bool LiveDeliveryClaim { get; } }
    public sealed class NotificationInboxActivationBoundary { public NotificationInboxActivationBoundary(string id, IReadOnlyList<InboxPreviewMessageRule> messageRules, IReadOnlyList<NotificationDeliveryBlocker> deliveryBlockers) { Id = ColonyIntegrationIds.Require(id); MessageRules = messageRules ?? Array.Empty<InboxPreviewMessageRule>(); DeliveryBlockers = deliveryBlockers ?? Array.Empty<NotificationDeliveryBlocker>(); Verdict = DeliveryBlockers.Any(b => b.LiveDeliveryClaim) ? NotificationInboxBoundaryVerdict.BlockedByDeliveryClaim : MessageRules.Any(r => ActivationReadinessText.Contains(r.MessageKind, "empty") && string.IsNullOrWhiteSpace(r.AllowedVisualState)) ? NotificationInboxBoundaryVerdict.NeedsEmptyStateClarification : NotificationInboxBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<InboxPreviewMessageRule> MessageRules { get; } public IReadOnlyList<NotificationDeliveryBlocker> DeliveryBlockers { get; } public NotificationInboxBoundaryVerdict Verdict { get; } }

    public sealed class EventParticipationPreviewCard { public EventParticipationPreviewCard(string eventId, string narrativeContext, string previewPrerequisite, string nonOfficialNextStep, string forbiddenLiveOpsClaim) { EventId = eventId ?? string.Empty; NarrativeContext = narrativeContext ?? string.Empty; PreviewPrerequisite = previewPrerequisite ?? string.Empty; NonOfficialNextStep = nonOfficialNextStep ?? string.Empty; ForbiddenLiveOpsClaim = forbiddenLiveOpsClaim ?? string.Empty; } public string EventId { get; } public string NarrativeContext { get; } public string PreviewPrerequisite { get; } public string NonOfficialNextStep { get; } public string ForbiddenLiveOpsClaim { get; } }
    public sealed class LiveOpsClaimBlocker { public LiveOpsClaimBlocker(string blockerId, bool liveOpsClaim) { BlockerId = blockerId ?? string.Empty; LiveOpsClaim = liveOpsClaim; } public string BlockerId { get; } public bool LiveOpsClaim { get; } }
    public sealed class EventParticipationActivationBoundary { public EventParticipationActivationBoundary(string id, IReadOnlyList<EventParticipationPreviewCard> cards, IReadOnlyList<LiveOpsClaimBlocker> claimBlockers) { Id = ColonyIntegrationIds.Require(id); Cards = cards ?? Array.Empty<EventParticipationPreviewCard>(); ClaimBlockers = claimBlockers ?? Array.Empty<LiveOpsClaimBlocker>(); Verdict = ClaimBlockers.Any(b => b.LiveOpsClaim) ? EventParticipationBoundaryVerdict.BlockedByLiveOpsClaim : Cards.Any(c => string.IsNullOrWhiteSpace(c.PreviewPrerequisite)) ? EventParticipationBoundaryVerdict.NeedsPrerequisiteClarification : EventParticipationBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<EventParticipationPreviewCard> Cards { get; } public IReadOnlyList<LiveOpsClaimBlocker> ClaimBlockers { get; } public EventParticipationBoundaryVerdict Verdict { get; } }

    public sealed class TradeOpportunityPreview { public TradeOpportunityPreview(string opportunityId, string resourceFocus, string estimatedBenefitText, string routeRiskPreview, string forbiddenMarketClaim) { OpportunityId = opportunityId ?? string.Empty; ResourceFocus = resourceFocus ?? string.Empty; EstimatedBenefitText = estimatedBenefitText ?? string.Empty; RouteRiskPreview = routeRiskPreview ?? string.Empty; ForbiddenMarketClaim = forbiddenMarketClaim ?? string.Empty; } public string OpportunityId { get; } public string ResourceFocus { get; } public string EstimatedBenefitText { get; } public string RouteRiskPreview { get; } public string ForbiddenMarketClaim { get; } }
    public sealed class MarketOfficialClaimBlocker { public MarketOfficialClaimBlocker(string blockerId, bool marketClaim) { BlockerId = blockerId ?? string.Empty; MarketClaim = marketClaim; } public string BlockerId { get; } public bool MarketClaim { get; } }
    public sealed class TradeMarketActivationBoundary { public TradeMarketActivationBoundary(string id, IReadOnlyList<TradeOpportunityPreview> opportunities, IReadOnlyList<MarketOfficialClaimBlocker> claimBlockers) { Id = ColonyIntegrationIds.Require(id); Opportunities = opportunities ?? Array.Empty<TradeOpportunityPreview>(); ClaimBlockers = claimBlockers ?? Array.Empty<MarketOfficialClaimBlocker>(); Verdict = ClaimBlockers.Any(b => b.MarketClaim) ? TradeMarketBoundaryVerdict.BlockedByMarketClaim : Opportunities.Any(o => string.IsNullOrWhiteSpace(o.ForbiddenMarketClaim)) ? TradeMarketBoundaryVerdict.NeedsMarketClarification : TradeMarketBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<TradeOpportunityPreview> Opportunities { get; } public IReadOnlyList<MarketOfficialClaimBlocker> ClaimBlockers { get; } public TradeMarketBoundaryVerdict Verdict { get; } }

    public sealed class ResearchGeneticsPreviewChoice { public ResearchGeneticsPreviewChoice(string choiceId, string branchName, string previewEffectText, string missingPrerequisite, string forbiddenOfficialEffect) { ChoiceId = choiceId ?? string.Empty; BranchName = branchName ?? string.Empty; PreviewEffectText = previewEffectText ?? string.Empty; MissingPrerequisite = missingPrerequisite ?? string.Empty; ForbiddenOfficialEffect = forbiddenOfficialEffect ?? string.Empty; } public string ChoiceId { get; } public string BranchName { get; } public string PreviewEffectText { get; } public string MissingPrerequisite { get; } public string ForbiddenOfficialEffect { get; } }
    public sealed class ResearchBalanceRisk { public ResearchBalanceRisk(string riskId, string description, bool officialEffectClaim = false) { RiskId = riskId ?? string.Empty; Description = description ?? string.Empty; OfficialEffectClaim = officialEffectClaim; } public string RiskId { get; } public string Description { get; } public bool OfficialEffectClaim { get; } }
    public sealed class ResearchGeneticsActivationBoundary { public ResearchGeneticsActivationBoundary(string id, IReadOnlyList<ResearchGeneticsPreviewChoice> choices, IReadOnlyList<ResearchBalanceRisk> balanceRisks) { Id = ColonyIntegrationIds.Require(id); Choices = choices ?? Array.Empty<ResearchGeneticsPreviewChoice>(); BalanceRisks = balanceRisks ?? Array.Empty<ResearchBalanceRisk>(); Verdict = BalanceRisks.Any(r => r.OfficialEffectClaim) ? ResearchGeneticsBoundaryVerdict.BlockedByOfficialEffectClaim : BalanceRisks.Count > 0 ? ResearchGeneticsBoundaryVerdict.NeedsBalanceReview : ResearchGeneticsBoundaryVerdict.PreviewSafe; } public string Id { get; } public IReadOnlyList<ResearchGeneticsPreviewChoice> Choices { get; } public IReadOnlyList<ResearchBalanceRisk> BalanceRisks { get; } public ResearchGeneticsBoundaryVerdict Verdict { get; } }

    public sealed class OnboardingPersistenceCandidate { public OnboardingPersistenceCandidate(string candidateId, string playerValue, string futureStorageQuestion, string privacyRisk, string currentStatus) { CandidateId = candidateId ?? string.Empty; PlayerValue = playerValue ?? string.Empty; FutureStorageQuestion = futureStorageQuestion ?? string.Empty; PrivacyRisk = privacyRisk ?? string.Empty; CurrentStatus = currentStatus ?? string.Empty; } public string CandidateId { get; } public string PlayerValue { get; } public string FutureStorageQuestion { get; } public string PrivacyRisk { get; } public string CurrentStatus { get; } }
    public sealed class OnboardingPersistenceExclusion { public OnboardingPersistenceExclusion(string exclusionId, string reason) { ExclusionId = exclusionId ?? string.Empty; Reason = reason ?? string.Empty; } public string ExclusionId { get; } public string Reason { get; } }
    public sealed class OnboardingPersistenceDecision { public OnboardingPersistenceDecision(string id, IReadOnlyList<OnboardingPersistenceCandidate> candidates, IReadOnlyList<OnboardingPersistenceExclusion> exclusions) { Id = ColonyIntegrationIds.Require(id); Candidates = candidates ?? Array.Empty<OnboardingPersistenceCandidate>(); Exclusions = exclusions ?? Array.Empty<OnboardingPersistenceExclusion>(); Verdict = Candidates.Any(c => ActivationReadinessText.Contains(c.CurrentStatus, "RejectedSensitiveData")) ? OnboardingPersistenceDecisionVerdict.BlockedByPrivacyRisk : OnboardingPersistenceDecisionVerdict.StorageForbiddenNow; } public string Id { get; } public IReadOnlyList<OnboardingPersistenceCandidate> Candidates { get; } public IReadOnlyList<OnboardingPersistenceExclusion> Exclusions { get; } public OnboardingPersistenceDecisionVerdict Verdict { get; } }

    public sealed class AccessibilityLocalizationRule { public AccessibilityLocalizationRule(string ruleId, string surfaceFamily, string requirement, string failureExample) { RuleId = ruleId ?? string.Empty; SurfaceFamily = surfaceFamily ?? string.Empty; Requirement = requirement ?? string.Empty; FailureExample = failureExample ?? string.Empty; } public string RuleId { get; } public string SurfaceFamily { get; } public string Requirement { get; } public string FailureExample { get; } }
    public sealed class LocalizationTermRisk { public LocalizationTermRisk(string term, string risk, bool liveVerbRisk = false) { Term = term ?? string.Empty; Risk = risk ?? string.Empty; LiveVerbRisk = liveVerbRisk; } public string Term { get; } public string Risk { get; } public bool LiveVerbRisk { get; } }
    public sealed class AccessibilityLocalizationReadiness { public AccessibilityLocalizationReadiness(string id, IReadOnlyList<AccessibilityLocalizationRule> rules, IReadOnlyList<LocalizationTermRisk> termRisks) { Id = ColonyIntegrationIds.Require(id); Rules = rules ?? Array.Empty<AccessibilityLocalizationRule>(); TermRisks = termRisks ?? Array.Empty<LocalizationTermRisk>(); Verdict = TermRisks.Any(t => t.LiveVerbRisk) ? AccessibilityLocalizationVerdict.BlockedByLiveVerbRisk : Rules.Any(r => string.IsNullOrWhiteSpace(r.FailureExample)) ? AccessibilityLocalizationVerdict.NeedsCopyRevision : AccessibilityLocalizationVerdict.ReadyForReview; } public string Id { get; } public IReadOnlyList<AccessibilityLocalizationRule> Rules { get; } public IReadOnlyList<LocalizationTermRisk> TermRisks { get; } public AccessibilityLocalizationVerdict Verdict { get; } }

    public sealed class PerformanceBudgetPreviewRule { public PerformanceBudgetPreviewRule(string ruleId, string surfaceFamily, string budgetStatement, string degradationSignal) { RuleId = ruleId ?? string.Empty; SurfaceFamily = surfaceFamily ?? string.Empty; BudgetStatement = budgetStatement ?? string.Empty; DegradationSignal = degradationSignal ?? string.Empty; } public string RuleId { get; } public string SurfaceFamily { get; } public string BudgetStatement { get; } public string DegradationSignal { get; } }
    public sealed class PerformanceBudgetRisk { public PerformanceBudgetRisk(string riskId, string mitigation, bool benchmarkClaim = false) { RiskId = riskId ?? string.Empty; Mitigation = mitigation ?? string.Empty; BenchmarkClaim = benchmarkClaim; } public string RiskId { get; } public string Mitigation { get; } public bool BenchmarkClaim { get; } }
    public sealed class PlayableSlicePerformanceBudgetPreview { public PlayableSlicePerformanceBudgetPreview(string id, IReadOnlyList<PerformanceBudgetPreviewRule> rules, IReadOnlyList<PerformanceBudgetRisk> risks) { Id = ColonyIntegrationIds.Require(id); Rules = rules ?? Array.Empty<PerformanceBudgetPreviewRule>(); Risks = risks ?? Array.Empty<PerformanceBudgetRisk>(); Verdict = Risks.Any(r => r.BenchmarkClaim) ? PerformanceBudgetPreviewVerdict.BlockedByBenchmarkClaim : Risks.Count > 0 ? PerformanceBudgetPreviewVerdict.NeedsMitigation : PerformanceBudgetPreviewVerdict.ReadyForPreview; } public string Id { get; } public IReadOnlyList<PerformanceBudgetPreviewRule> Rules { get; } public IReadOnlyList<PerformanceBudgetRisk> Risks { get; } public PerformanceBudgetPreviewVerdict Verdict { get; } }

    public sealed class Bee600DemoProofCandidate { public Bee600DemoProofCandidate(string candidateId, string sourceBeeRange, string narrativeProofNeed, string forbiddenClaimDuringDemo, bool liveClaim = false) { CandidateId = candidateId ?? string.Empty; SourceBeeRange = sourceBeeRange ?? string.Empty; NarrativeProofNeed = narrativeProofNeed ?? string.Empty; ForbiddenClaimDuringDemo = forbiddenClaimDuringDemo ?? string.Empty; LiveClaim = liveClaim; } public string CandidateId { get; } public string SourceBeeRange { get; } public string NarrativeProofNeed { get; } public string ForbiddenClaimDuringDemo { get; } public bool LiveClaim { get; } }
    public sealed class Bee600DemoReserve { public Bee600DemoReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class Bee600DemoRoadmapAccumulator { public Bee600DemoRoadmapAccumulator(string id, IReadOnlyList<Bee600DemoProofCandidate> proofCandidates, IReadOnlyList<Bee600DemoReserve> reserves) { Id = ColonyIntegrationIds.Require(id); ProofCandidates = proofCandidates ?? Array.Empty<Bee600DemoProofCandidate>(); Reserves = reserves ?? Array.Empty<Bee600DemoReserve>(); Verdict = ProofCandidates.Any(p => p.LiveClaim || string.IsNullOrWhiteSpace(p.ForbiddenClaimDuringDemo)) ? Bee600DemoRoadmapVerdict.BlockedByLiveDemoClaim : Reserves.Count > 0 ? Bee600DemoRoadmapVerdict.ReadyWithReserves : Bee600DemoRoadmapVerdict.ReadyForBEE600Planning; } public string Id { get; } public IReadOnlyList<Bee600DemoProofCandidate> ProofCandidates { get; } public IReadOnlyList<Bee600DemoReserve> Reserves { get; } public Bee600DemoRoadmapVerdict Verdict { get; } }

    public sealed class ActivationClosureLedgerRow { public ActivationClosureLedgerRow(string sourceBee, string closureQuestion, string evidencePointer, string refusalTrigger, string ownerLane) { SourceBee = sourceBee ?? string.Empty; ClosureQuestion = closureQuestion ?? string.Empty; EvidencePointer = evidencePointer ?? string.Empty; RefusalTrigger = refusalTrigger ?? string.Empty; OwnerLane = ownerLane ?? string.Empty; } public string SourceBee { get; } public string ClosureQuestion { get; } public string EvidencePointer { get; } public string RefusalTrigger { get; } public string OwnerLane { get; } }
    public sealed class ActivationClosureTeamLane { public ActivationClosureTeamLane(string laneId, bool assigned) { LaneId = laneId ?? string.Empty; Assigned = assigned; } public string LaneId { get; } public bool Assigned { get; } }
    public sealed class ActivationClosureReserve { public ActivationClosureReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class ActivationReadinessLotClosureGate
    {
        private static readonly string[] RequiredLanes = { "BuilderImplementation", "ServerImpactReview", "UiMobileReview", "QaLotValidation", "Demo600Followup", "ArchitectDecision" };
        public ActivationReadinessLotClosureGate(string id, IReadOnlyList<ActivationClosureLedgerRow> ledgerRows, IReadOnlyList<ActivationClosureTeamLane> teamLanes, IReadOnlyList<ActivationClosureReserve> openReserves, Bee521BlockerStatus bee521Status) { Id = ColonyIntegrationIds.Require(id); LedgerRows = ledgerRows ?? Array.Empty<ActivationClosureLedgerRow>(); TeamLanes = teamLanes ?? Array.Empty<ActivationClosureTeamLane>(); OpenReserves = openReserves ?? Array.Empty<ActivationClosureReserve>(); Bee521Status = bee521Status; Verdict = EvaluateVerdict(); }
        public string Id { get; } public IReadOnlyList<ActivationClosureLedgerRow> LedgerRows { get; } public IReadOnlyList<ActivationClosureTeamLane> TeamLanes { get; } public IReadOnlyList<ActivationClosureReserve> OpenReserves { get; } public ActivationReadinessLotVerdict Verdict { get; } public Bee521BlockerStatus Bee521Status { get; }
        private ActivationReadinessLotVerdict EvaluateVerdict()
        {
            if (Bee521Status == Bee521BlockerStatus.ReleasedByFutureArchitectDecision) return ActivationReadinessLotVerdict.BlockedByBee521Premature;
            for (int bee = 501; bee <= 519; bee++) if (LedgerRows.All(r => !ActivationReadinessText.Same(r.SourceBee, "BEE-" + bee))) return ActivationReadinessLotVerdict.BlockedByMissingEvidence;
            if (RequiredLanes.Any(lane => TeamLanes.All(t => !ActivationReadinessText.Same(t.LaneId, lane) || !t.Assigned))) return ActivationReadinessLotVerdict.NeedsTeamRevision;
            if (LedgerRows.Any(r => string.IsNullOrWhiteSpace(r.EvidencePointer))) return ActivationReadinessLotVerdict.BlockedByMissingEvidence;
            if (LedgerRows.Any(r => ActivationReadinessText.Contains(r.RefusalTrigger, "feature live") || ActivationReadinessText.Contains(r.RefusalTrigger, "production readiness") || ActivationReadinessText.Contains(r.RefusalTrigger, "sauvegarde officielle"))) return ActivationReadinessLotVerdict.BlockedByLiveClaim;
            if (LedgerRows.Any(r => ActivationReadinessText.Contains(r.RefusalTrigger, "service serveur deduit"))) return ActivationReadinessLotVerdict.BlockedByHiddenServerService;
            return OpenReserves.Count > 0 ? ActivationReadinessLotVerdict.ReadyWithOpenReserves : ActivationReadinessLotVerdict.ReadyForArchitectValidation;
        }
    }

    public sealed class PostMilestoneInvariantRegistered { public PostMilestoneInvariantRegistered(string invariantId) { InvariantId = invariantId ?? string.Empty; } public string InvariantId { get; } }
    public sealed class PostMilestoneRegressionDetected { public PostMilestoneRegressionDetected(string invariantId) { InvariantId = invariantId ?? string.Empty; } public string InvariantId { get; } }
    public sealed class Bee500ReserveStillVisible { public Bee500ReserveStillVisible(string reserveId) { ReserveId = reserveId ?? string.Empty; } public string ReserveId { get; } }
    public sealed class ActivationClosureLedgerSealed { public ActivationClosureLedgerSealed(string gateId) { GateId = gateId ?? string.Empty; } public string GateId { get; } }
    public sealed class ClosureTeamLaneAssigned { public ClosureTeamLaneAssigned(string laneId) { LaneId = laneId ?? string.Empty; } public string LaneId { get; } }
    public sealed class Bee521BlockerConfirmed { public Bee521BlockerConfirmed(Bee521BlockerStatus status) { Status = status; } public Bee521BlockerStatus Status { get; } }

    public sealed class ActivationReadinessDiagnostics { public ActivationReadinessDiagnostics(IReadOnlyList<ActivationReadinessDiagnosticCode> findings) { Findings = findings ?? Array.Empty<ActivationReadinessDiagnosticCode>(); } public IReadOnlyList<ActivationReadinessDiagnosticCode> Findings { get; } public bool Contains(ActivationReadinessDiagnosticCode code) { return Findings.Contains(code); } }
    internal static class ActivationReadinessText
    {
        public static bool Same(string left, string right) { return string.Equals(left, right, StringComparison.OrdinalIgnoreCase); }
        public static bool Contains(string text, string value) { return (text ?? string.Empty).IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0; }
    }
}
