using System;
using System.Collections.Generic;
using System.Linq;

namespace BeeKingdom.Colony
{
    public enum ArtPassReadinessVerdict { Ready, ReadyWithReserves, MissingWorkstream, Bee581Premature }
    public enum ResourceHudDensityMode { Compact, Comfortable, Expanded }
    public enum TouchNavigationVerdict { Ready, MissingTarget, UnsafeArea, TouchConflict }
    public enum MicrocopyVerdict { Ready, MissingEntry, ForbiddenClaimFound }
    public enum ArtPassAccessibilityVerdict { Ready, ContrastIssue, ColorOnlySignal, TextFitIssue }
    public enum DemoCaptureVerdict { ReadyForFutureDemo, MissingShot, MissingAnnotation }
    public enum NonAuthoritativeVerdict { SafeForPreview, MissingClaimReview, ForbiddenImplicationFound }
    public enum ArtPassGateVerdict { ReadyForArchitectReview, ReadyWithReserves, BlockedByMissingRow, BlockedByServerClaim, BlockedByBee581Premature }
    public enum Bee581BlockerStatus { BlockedUntilArtPassValidation, ReadyForArchitectReview, ReleasedByFutureArchitectDecision }

    public sealed class ArtPassReserveRow { public ArtPassReserveRow(string reserveId, string ownerLane, bool addressed) { ReserveId = reserveId ?? string.Empty; OwnerLane = ownerLane ?? string.Empty; Addressed = addressed; } public string ReserveId { get; } public string OwnerLane { get; } public bool Addressed { get; } }
    public sealed class ArtPassWorkstream { public ArtPassWorkstream(string workstreamId, string expectedEvidence) { WorkstreamId = workstreamId ?? string.Empty; ExpectedEvidence = expectedEvidence ?? string.Empty; } public string WorkstreamId { get; } public string ExpectedEvidence { get; } }
    public sealed class HiveProductUiArtPassIntake
    {
        private static readonly string[] Required = { "ResourceHud", "TouchNavigation", "DetailPanel", "VisualStates", "ZoneIcons", "AssetSet", "HiveAmbience", "MobilePortrait", "NonAuthoritativeDisclosure" };
        public HiveProductUiArtPassIntake(IReadOnlyList<ArtPassReserveRow> reserves, IReadOnlyList<ArtPassWorkstream> workstreams) { Reserves = reserves ?? Array.Empty<ArtPassReserveRow>(); Workstreams = workstreams ?? Array.Empty<ArtPassWorkstream>(); Verdict = Required.Any(r => Workstreams.All(w => !ArtPassText.Same(w.WorkstreamId, r))) ? ArtPassReadinessVerdict.MissingWorkstream : Reserves.Any(r => !r.Addressed) ? ArtPassReadinessVerdict.ReadyWithReserves : ArtPassReadinessVerdict.Ready; }
        public IReadOnlyList<ArtPassReserveRow> Reserves { get; } public IReadOnlyList<ArtPassWorkstream> Workstreams { get; } public ArtPassReadinessVerdict Verdict { get; }
    }

    public sealed class ResourceIconSpec { public ResourceIconSpec(string iconId, string silhouette, int sizePx, string shortLabel, bool previewDisclosure) { IconId = iconId ?? string.Empty; Silhouette = silhouette ?? string.Empty; SizePx = sizePx; ShortLabel = shortLabel ?? string.Empty; PreviewDisclosure = previewDisclosure; } public string IconId { get; } public string Silhouette { get; } public int SizePx { get; } public string ShortLabel { get; } public bool PreviewDisclosure { get; } }
    public sealed class ResourceHudIconRefinement { public ResourceHudIconRefinement(IReadOnlyList<ResourceIconSpec> iconSpecs, ResourceHudDensityMode densityMode, string previewDisclosure) { IconSpecs = iconSpecs ?? Array.Empty<ResourceIconSpec>(); DensityMode = densityMode; PreviewDisclosure = previewDisclosure ?? string.Empty; IsComplete = Required.All(r => IconSpecs.Any(i => ArtPassText.Same(i.IconId, r) && i.PreviewDisclosure && i.SizePx >= 24)) && !string.IsNullOrWhiteSpace(PreviewDisclosure); } private static readonly string[] Required = { "HoneyDrop", "WaxBlock", "PollenGrain", "BeePopulation", "StorageCapacity" }; public IReadOnlyList<ResourceIconSpec> IconSpecs { get; } public ResourceHudDensityMode DensityMode { get; } public string PreviewDisclosure { get; } public bool IsComplete { get; } }
    public sealed class MaterialChipSpec { public MaterialChipSpec(string materialId, string role, int scanPriority, string accentId, bool passive) { MaterialId = materialId ?? string.Empty; Role = role ?? string.Empty; ScanPriority = scanPriority; AccentId = accentId ?? string.Empty; Passive = passive; } public string MaterialId { get; } public string Role { get; } public int ScanPriority { get; } public string AccentId { get; } public bool Passive { get; } }
    public sealed class MaterialChipRule { public MaterialChipRule(string ruleId, string description) { RuleId = ruleId ?? string.Empty; Description = description ?? string.Empty; } public string RuleId { get; } public string Description { get; } }
    public sealed class MaterialResourceChipHierarchy { public MaterialResourceChipHierarchy(MaterialChipSpec honey, MaterialChipSpec wax, MaterialChipSpec pollen, IReadOnlyList<MaterialChipRule> scanRules) { Honey = honey; Wax = wax; Pollen = pollen; ScanRules = scanRules ?? Array.Empty<MaterialChipRule>(); IsReadable = honey != null && wax != null && pollen != null && honey.Passive && wax.Passive && pollen.Passive && honey.ScanPriority < wax.ScanPriority && wax.ScanPriority < pollen.ScanPriority; } public MaterialChipSpec Honey { get; } public MaterialChipSpec Wax { get; } public MaterialChipSpec Pollen { get; } public IReadOnlyList<MaterialChipRule> ScanRules { get; } public bool IsReadable { get; } }

    public sealed class TouchTargetSpec { public TouchTargetSpec(string targetId, int minSizePx, int marginPx, bool conflictsWithGesture = false) { TargetId = targetId ?? string.Empty; MinSizePx = minSizePx; MarginPx = marginPx; ConflictsWithGesture = conflictsWithGesture; } public string TargetId { get; } public int MinSizePx { get; } public int MarginPx { get; } public bool ConflictsWithGesture { get; } }
    public sealed class SafeAreaPolicy { public SafeAreaPolicy(bool respectsTop, bool respectsBottom, bool respectsSides) { RespectsTop = respectsTop; RespectsBottom = respectsBottom; RespectsSides = respectsSides; } public bool RespectsTop { get; } public bool RespectsBottom { get; } public bool RespectsSides { get; } public bool IsSafe => RespectsTop && RespectsBottom && RespectsSides; }
    public sealed class TouchNavigationTargetMap { public TouchNavigationTargetMap(IReadOnlyList<TouchTargetSpec> targets, SafeAreaPolicy safeArea) { Targets = targets ?? Array.Empty<TouchTargetSpec>(); SafeArea = safeArea; Verdict = Evaluate(); } private static readonly string[] Required = { "BackHome", "ResourceHudInfo", "ZoneFilter", "CellSelect", "DetailClose", "DetailPrimaryPreview" }; public IReadOnlyList<TouchTargetSpec> Targets { get; } public SafeAreaPolicy SafeArea { get; } public TouchNavigationVerdict Verdict { get; } private TouchNavigationVerdict Evaluate() { if (SafeArea == null || !SafeArea.IsSafe) return TouchNavigationVerdict.UnsafeArea; if (Required.Any(r => Targets.All(t => !ArtPassText.Same(t.TargetId, r)))) return TouchNavigationVerdict.MissingTarget; if (Targets.Any(t => t.MinSizePx < 44 || t.ConflictsWithGesture)) return TouchNavigationVerdict.TouchConflict; return TouchNavigationVerdict.Ready; } }
    public sealed class ThumbRailItem { public ThumbRailItem(string itemId, string label, string iconId, bool passivePreview) { ItemId = itemId ?? string.Empty; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; PassivePreview = passivePreview; } public string ItemId { get; } public string Label { get; } public string IconId { get; } public bool PassivePreview { get; } }
    public sealed class ThumbRailCollapseRule { public ThumbRailCollapseRule(string ruleId, bool keepsHomeVisible) { RuleId = ruleId ?? string.Empty; KeepsHomeVisible = keepsHomeVisible; } public string RuleId { get; } public bool KeepsHomeVisible { get; } }
    public sealed class BottomThumbRail { public BottomThumbRail(ThumbRailItem homeAnchor, ThumbRailItem zoneLens, ThumbRailItem resourceLens, ThumbRailItem detailToggle, ThumbRailItem previewBadge, ThumbRailCollapseRule collapseRule) { HomeAnchor = homeAnchor; ZoneLens = zoneLens; ResourceLens = resourceLens; DetailToggle = detailToggle; PreviewBadge = previewBadge; CollapseRule = collapseRule; IsReady = Items().All(i => i != null && i.PassivePreview && !string.IsNullOrWhiteSpace(i.IconId)) && collapseRule != null && collapseRule.KeepsHomeVisible; } public ThumbRailItem HomeAnchor { get; } public ThumbRailItem ZoneLens { get; } public ThumbRailItem ResourceLens { get; } public ThumbRailItem DetailToggle { get; } public ThumbRailItem PreviewBadge { get; } public ThumbRailCollapseRule CollapseRule { get; } public bool IsReady { get; } private IEnumerable<ThumbRailItem> Items() { yield return HomeAnchor; yield return ZoneLens; yield return ResourceLens; yield return DetailToggle; yield return PreviewBadge; } }

    public sealed class DetailPanelHeader { public DetailPanelHeader(string selectedCellName, string zoneRole) { SelectedCellName = selectedCellName ?? string.Empty; ZoneRole = zoneRole ?? string.Empty; } public string SelectedCellName { get; } public string ZoneRole { get; } }
    public sealed class DetailPanelStateBlock { public DetailPanelStateBlock(string visualState, string stateTokenId) { VisualState = visualState ?? string.Empty; StateTokenId = stateTokenId ?? string.Empty; } public string VisualState { get; } public string StateTokenId { get; } }
    public sealed class DetailPanelPreviewBlock { public DetailPanelPreviewBlock(string previewDisclosure, string localMeaning) { PreviewDisclosure = previewDisclosure ?? string.Empty; LocalMeaning = localMeaning ?? string.Empty; } public string PreviewDisclosure { get; } public string LocalMeaning { get; } }
    public sealed class DetailPanelActionRow { public DetailPanelActionRow(string closeControlLabel, string primaryPreviewLabel, bool officialAction) { CloseControlLabel = closeControlLabel ?? string.Empty; PrimaryPreviewLabel = primaryPreviewLabel ?? string.Empty; OfficialAction = officialAction; } public string CloseControlLabel { get; } public string PrimaryPreviewLabel { get; } public bool OfficialAction { get; } }
    public sealed class HiveDetailPanelComposition { public HiveDetailPanelComposition(DetailPanelHeader header, DetailPanelStateBlock stateBlock, DetailPanelPreviewBlock previewBlock, DetailPanelActionRow actionRow) { Header = header; StateBlock = stateBlock; PreviewBlock = previewBlock; ActionRow = actionRow; IsPolished = header != null && stateBlock != null && previewBlock != null && actionRow != null && !actionRow.OfficialAction && !string.IsNullOrWhiteSpace(actionRow.CloseControlLabel); } public DetailPanelHeader Header { get; } public DetailPanelStateBlock StateBlock { get; } public DetailPanelPreviewBlock PreviewBlock { get; } public DetailPanelActionRow ActionRow { get; } public bool IsPolished { get; } }
    public sealed class DetailCopyEntry { public DetailCopyEntry(string entryId, string playerText) { EntryId = entryId ?? string.Empty; PlayerText = playerText ?? string.Empty; } public string EntryId { get; } public string PlayerText { get; } }
    public sealed class ForbiddenClaimPattern { public ForbiddenClaimPattern(string pattern, string reason) { Pattern = pattern ?? string.Empty; Reason = reason ?? string.Empty; } public string Pattern { get; } public string Reason { get; } }
    public sealed class DetailPanelMicrocopyCatalog { public DetailPanelMicrocopyCatalog(IReadOnlyList<DetailCopyEntry> allowedEntries, IReadOnlyList<ForbiddenClaimPattern> forbiddenClaims) { AllowedEntries = allowedEntries ?? Array.Empty<DetailCopyEntry>(); ForbiddenClaims = forbiddenClaims ?? Array.Empty<ForbiddenClaimPattern>(); Verdict = Evaluate(); } private static readonly string[] Required = { "PreviewRole", "LocalEstimate", "ServerRequired", "LockedFuture", "NoOfficialAction" }; public IReadOnlyList<DetailCopyEntry> AllowedEntries { get; } public IReadOnlyList<ForbiddenClaimPattern> ForbiddenClaims { get; } public MicrocopyVerdict Verdict { get; } private MicrocopyVerdict Evaluate() { if (Required.Any(r => AllowedEntries.All(e => !ArtPassText.Same(e.EntryId, r)))) return MicrocopyVerdict.MissingEntry; if (ForbiddenClaims.Any(f => AllowedEntries.Any(e => ArtPassText.Contains(e.PlayerText, f.Pattern)))) return MicrocopyVerdict.ForbiddenClaimFound; return MicrocopyVerdict.Ready; } }

    public sealed class VisualStateToken { public VisualStateToken(string tokenId, string shape, string iconId, string borderId, bool colorOnly = false) { TokenId = tokenId ?? string.Empty; Shape = shape ?? string.Empty; IconId = iconId ?? string.Empty; BorderId = borderId ?? string.Empty; ColorOnly = colorOnly; } public string TokenId { get; } public string Shape { get; } public string IconId { get; } public string BorderId { get; } public bool ColorOnly { get; } }
    public sealed class StateTokenAccessibilityRule { public StateTokenAccessibilityRule(string ruleId, bool satisfied) { RuleId = ruleId ?? string.Empty; Satisfied = satisfied; } public string RuleId { get; } public bool Satisfied { get; } }
    public sealed class HiveVisualStateTokenSet { public HiveVisualStateTokenSet(VisualStateToken selected, VisualStateToken locked, VisualStateToken serverRequired, VisualStateToken preview, IReadOnlyList<StateTokenAccessibilityRule> accessibilityRules) { Selected = selected; Locked = locked; ServerRequired = serverRequired; Preview = preview; AccessibilityRules = accessibilityRules ?? Array.Empty<StateTokenAccessibilityRule>(); IsAccessible = Tokens().All(t => t != null && !t.ColorOnly && !string.IsNullOrWhiteSpace(t.IconId) && !string.IsNullOrWhiteSpace(t.BorderId)) && AccessibilityRules.All(r => r.Satisfied); } public VisualStateToken Selected { get; } public VisualStateToken Locked { get; } public VisualStateToken ServerRequired { get; } public VisualStateToken Preview { get; } public IReadOnlyList<StateTokenAccessibilityRule> AccessibilityRules { get; } public bool IsAccessible { get; } private IEnumerable<VisualStateToken> Tokens() { yield return Selected; yield return Locked; yield return ServerRequired; yield return Preview; } }
    public sealed class ZoneIconSpec { public ZoneIconSpec(string zoneId, string silhouette, string compactLabel, bool inactiveVariant) { ZoneId = zoneId ?? string.Empty; Silhouette = silhouette ?? string.Empty; CompactLabel = compactLabel ?? string.Empty; InactiveVariant = inactiveVariant; } public string ZoneId { get; } public string Silhouette { get; } public string CompactLabel { get; } public bool InactiveVariant { get; } }
    public sealed class ZoneIconUsageRule { public ZoneIconUsageRule(string ruleId, string description) { RuleId = ruleId ?? string.Empty; Description = description ?? string.Empty; } public string RuleId { get; } public string Description { get; } }
    public sealed class HiveZoneIconSet { public HiveZoneIconSet(ZoneIconSpec nursery, ZoneIconSpec storage, ZoneIconSpec defense, ZoneIconSpec research, IReadOnlyList<ZoneIconUsageRule> usageRules) { Nursery = nursery; Storage = storage; Defense = defense; Research = research; UsageRules = usageRules ?? Array.Empty<ZoneIconUsageRule>(); IsComplete = Icons().All(i => i != null && i.InactiveVariant && !string.IsNullOrWhiteSpace(i.Silhouette)); } public ZoneIconSpec Nursery { get; } public ZoneIconSpec Storage { get; } public ZoneIconSpec Defense { get; } public ZoneIconSpec Research { get; } public IReadOnlyList<ZoneIconUsageRule> UsageRules { get; } public bool IsComplete { get; } private IEnumerable<ZoneIconSpec> Icons() { yield return Nursery; yield return Storage; yield return Defense; yield return Research; } }

    public sealed class AmbiencePalette { public AmbiencePalette(string waxTone, string honeyTone, string neutralContrast, string zoneAccent) { WaxTone = waxTone ?? string.Empty; HoneyTone = honeyTone ?? string.Empty; NeutralContrast = neutralContrast ?? string.Empty; ZoneAccent = zoneAccent ?? string.Empty; } public string WaxTone { get; } public string HoneyTone { get; } public string NeutralContrast { get; } public string ZoneAccent { get; } }
    public sealed class TextureTreatment { public TextureTreatment(string textureId, bool subtle) { TextureId = textureId ?? string.Empty; Subtle = subtle; } public string TextureId { get; } public bool Subtle { get; } }
    public sealed class DepthTreatment { public DepthTreatment(string depthId, bool separatesBoard) { DepthId = depthId ?? string.Empty; SeparatesBoard = separatesBoard; } public string DepthId { get; } public bool SeparatesBoard { get; } }
    public sealed class ReadabilityGuard { public ReadabilityGuard(bool protectsHud, bool protectsCells, bool protectsPanel) { ProtectsHud = protectsHud; ProtectsCells = protectsCells; ProtectsPanel = protectsPanel; } public bool ProtectsHud { get; } public bool ProtectsCells { get; } public bool ProtectsPanel { get; } public bool IsSafe => ProtectsHud && ProtectsCells && ProtectsPanel; }
    public sealed class HiveWaxAmbienceLayer { public HiveWaxAmbienceLayer(AmbiencePalette palette, TextureTreatment waxTexture, DepthTreatment depth, ReadabilityGuard readabilityGuard) { Palette = palette; WaxTexture = waxTexture; Depth = depth; ReadabilityGuard = readabilityGuard; IsReady = palette != null && waxTexture != null && waxTexture.Subtle && depth != null && depth.SeparatesBoard && readabilityGuard != null && readabilityGuard.IsSafe; } public AmbiencePalette Palette { get; } public TextureTreatment WaxTexture { get; } public DepthTreatment Depth { get; } public ReadabilityGuard ReadabilityGuard { get; } public bool IsReady { get; } }
    public sealed class BorderTreatment { public BorderTreatment(string treatmentId, bool visible) { TreatmentId = treatmentId ?? string.Empty; Visible = visible; } public string TreatmentId { get; } public bool Visible { get; } }
    public sealed class ShadowTreatment { public ShadowTreatment(string shadowId, bool subtle) { ShadowId = shadowId ?? string.Empty; Subtle = subtle; } public string ShadowId { get; } public bool Subtle { get; } }
    public sealed class HighlightTreatment { public HighlightTreatment(string highlightId, bool readable) { HighlightId = highlightId ?? string.Empty; Readable = readable; } public string HighlightId { get; } public bool Readable { get; } }
    public sealed class HexCellDepthTreatment { public HexCellDepthTreatment(BorderTreatment normalBorder, BorderTreatment selectedBorder, ShadowTreatment cellShadow, HighlightTreatment waxHighlight) { NormalBorder = normalBorder; SelectedBorder = selectedBorder; CellShadow = cellShadow; WaxHighlight = waxHighlight; IsReady = normalBorder != null && normalBorder.Visible && selectedBorder != null && selectedBorder.Visible && cellShadow != null && cellShadow.Subtle && waxHighlight != null && waxHighlight.Readable; } public BorderTreatment NormalBorder { get; } public BorderTreatment SelectedBorder { get; } public ShadowTreatment CellShadow { get; } public HighlightTreatment WaxHighlight { get; } public bool IsReady { get; } }

    public sealed class AssetManifestEntry { public AssetManifestEntry(string assetId, string category, string usage, bool previewStatus) { AssetId = assetId ?? string.Empty; Category = category ?? string.Empty; Usage = usage ?? string.Empty; PreviewStatus = previewStatus; } public string AssetId { get; } public string Category { get; } public string Usage { get; } public bool PreviewStatus { get; } }
    public sealed class AssetNamingPolicy { public AssetNamingPolicy(string prefix, bool rejectsGenericNames) { Prefix = prefix ?? string.Empty; RejectsGenericNames = rejectsGenericNames; } public string Prefix { get; } public bool RejectsGenericNames { get; } }
    public sealed class AssetPreviewStatus { public AssetPreviewStatus(string label, bool finalClaim) { Label = label ?? string.Empty; FinalClaim = finalClaim; } public string Label { get; } public bool FinalClaim { get; } }
    public sealed class HiveArtPassAssetManifest { public HiveArtPassAssetManifest(IReadOnlyList<AssetManifestEntry> entries, AssetNamingPolicy namingPolicy, AssetPreviewStatus previewStatus) { Entries = entries ?? Array.Empty<AssetManifestEntry>(); NamingPolicy = namingPolicy; PreviewStatus = previewStatus; IsValid = Categories.All(c => Entries.Any(e => ArtPassText.Same(e.Category, c) && e.PreviewStatus)) && namingPolicy != null && namingPolicy.RejectsGenericNames && previewStatus != null && !previewStatus.FinalClaim; } private static readonly string[] Categories = { "ResourceIcons", "ZoneIcons", "StateBadges", "WaxTextures", "RailIcons", "PanelChrome" }; public IReadOnlyList<AssetManifestEntry> Entries { get; } public AssetNamingPolicy NamingPolicy { get; } public AssetPreviewStatus PreviewStatus { get; } public bool IsValid { get; } }
    public sealed class SafeAreaInsets { public SafeAreaInsets(int top, int bottom, int left, int right) { Top = top; Bottom = bottom; Left = left; Right = right; } public int Top { get; } public int Bottom { get; } public int Left { get; } public int Right { get; } public bool IsValid => Top >= 0 && Bottom >= 0 && Left >= 0 && Right >= 0; }
    public sealed class PortraitStackOrder { public PortraitStackOrder(string top, string middle, string detail, string bottom) { Top = top ?? string.Empty; Middle = middle ?? string.Empty; Detail = detail ?? string.Empty; Bottom = bottom ?? string.Empty; } public string Top { get; } public string Middle { get; } public string Detail { get; } public string Bottom { get; } }
    public sealed class PortraitOverlapRule { public PortraitOverlapRule(string ruleId, bool passes) { RuleId = ruleId ?? string.Empty; Passes = passes; } public string RuleId { get; } public bool Passes { get; } }
    public enum PortraitReadabilityVerdict { Ready, MissingStack, OverlapDetected, InvalidSafeArea }
    public sealed class MobilePortraitHiveLayoutPolicy { public MobilePortraitHiveLayoutPolicy(SafeAreaInsets safeArea, PortraitStackOrder stackOrder, IReadOnlyList<PortraitOverlapRule> overlapRules) { SafeArea = safeArea; StackOrder = stackOrder; OverlapRules = overlapRules ?? Array.Empty<PortraitOverlapRule>(); Verdict = safeArea == null || !safeArea.IsValid ? PortraitReadabilityVerdict.InvalidSafeArea : stackOrder == null || string.IsNullOrWhiteSpace(stackOrder.Top) || string.IsNullOrWhiteSpace(stackOrder.Bottom) ? PortraitReadabilityVerdict.MissingStack : OverlapRules.Any(r => !r.Passes) ? PortraitReadabilityVerdict.OverlapDetected : PortraitReadabilityVerdict.Ready; } public SafeAreaInsets SafeArea { get; } public PortraitStackOrder StackOrder { get; } public IReadOnlyList<PortraitOverlapRule> OverlapRules { get; } public PortraitReadabilityVerdict Verdict { get; } }

    public sealed class PressStateToken { public PressStateToken(string tokenId, string visualResponse, bool officialConfirmation) { TokenId = tokenId ?? string.Empty; VisualResponse = visualResponse ?? string.Empty; OfficialConfirmation = officialConfirmation; } public string TokenId { get; } public string VisualResponse { get; } public bool OfficialConfirmation { get; } }
    public sealed class TactileFeedbackLanguage { public TactileFeedbackLanguage(PressStateToken pressed, PressStateToken released, PressStateToken refusedPreview, PressStateToken focusShift) { Pressed = pressed; Released = released; RefusedPreview = refusedPreview; FocusShift = focusShift; IsSafe = Tokens().All(t => t != null && !t.OfficialConfirmation && !string.IsNullOrWhiteSpace(t.VisualResponse)); } public PressStateToken Pressed { get; } public PressStateToken Released { get; } public PressStateToken RefusedPreview { get; } public PressStateToken FocusShift { get; } public bool IsSafe { get; } private IEnumerable<PressStateToken> Tokens() { yield return Pressed; yield return Released; yield return RefusedPreview; yield return FocusShift; } }
    public sealed class CellArtTreatment { public CellArtTreatment(string treatmentId, string visualTreatment, bool impliesBuildAction) { TreatmentId = treatmentId ?? string.Empty; VisualTreatment = visualTreatment ?? string.Empty; ImpliesBuildAction = impliesBuildAction; } public string TreatmentId { get; } public string VisualTreatment { get; } public bool ImpliesBuildAction { get; } }
    public sealed class FutureRoomClaimRule { public FutureRoomClaimRule(string ruleId, bool forbidsCostTimerReward) { RuleId = ruleId ?? string.Empty; ForbidsCostTimerReward = forbidsCostTimerReward; } public string RuleId { get; } public bool ForbidsCostTimerReward { get; } }
    public sealed class FutureRoomArtTreatment { public FutureRoomArtTreatment(CellArtTreatment empty, CellArtTreatment locked, CellArtTreatment futureRoom, IReadOnlyList<FutureRoomClaimRule> claimRules) { Empty = empty; Locked = locked; FutureRoom = futureRoom; ClaimRules = claimRules ?? Array.Empty<FutureRoomClaimRule>(); IsSafe = Treatments().All(t => t != null && !t.ImpliesBuildAction && !string.IsNullOrWhiteSpace(t.VisualTreatment)) && ClaimRules.All(r => r.ForbidsCostTimerReward); } public CellArtTreatment Empty { get; } public CellArtTreatment Locked { get; } public CellArtTreatment FutureRoom { get; } public IReadOnlyList<FutureRoomClaimRule> ClaimRules { get; } public bool IsSafe { get; } private IEnumerable<CellArtTreatment> Treatments() { yield return Empty; yield return Locked; yield return FutureRoom; } }

    public sealed class ContrastRule { public ContrastRule(string surfaceId, float ratio, bool passes) { SurfaceId = surfaceId ?? string.Empty; Ratio = ratio; Passes = passes; } public string SurfaceId { get; } public float Ratio { get; } public bool Passes { get; } }
    public sealed class SymbolPairingRule { public SymbolPairingRule(string symbolId, bool hasLabel, bool familiarShape) { SymbolId = symbolId ?? string.Empty; HasLabel = hasLabel; FamiliarShape = familiarShape; } public string SymbolId { get; } public bool HasLabel { get; } public bool FamiliarShape { get; } }
    public sealed class TextFitPolicy { public TextFitPolicy(bool noCutText, bool compactLabels) { NoCutText = noCutText; CompactLabels = compactLabels; } public bool NoCutText { get; } public bool CompactLabels { get; } }
    public sealed class HiveArtPassAccessibilityRules { public HiveArtPassAccessibilityRules(IReadOnlyList<ContrastRule> contrastRules, IReadOnlyList<SymbolPairingRule> symbolPairings, TextFitPolicy textFit) { ContrastRules = contrastRules ?? Array.Empty<ContrastRule>(); SymbolPairings = symbolPairings ?? Array.Empty<SymbolPairingRule>(); TextFit = textFit; Verdict = ContrastRules.Any(r => !r.Passes || r.Ratio < 3f) ? ArtPassAccessibilityVerdict.ContrastIssue : SymbolPairings.Any(s => !s.HasLabel && !s.FamiliarShape) ? ArtPassAccessibilityVerdict.ColorOnlySignal : textFit == null || !textFit.NoCutText ? ArtPassAccessibilityVerdict.TextFitIssue : ArtPassAccessibilityVerdict.Ready; } public IReadOnlyList<ContrastRule> ContrastRules { get; } public IReadOnlyList<SymbolPairingRule> SymbolPairings { get; } public TextFitPolicy TextFit { get; } public ArtPassAccessibilityVerdict Verdict { get; } }

    public sealed class CaptureShotRequirement { public CaptureShotRequirement(string shotId, bool required) { ShotId = shotId ?? string.Empty; Required = required; } public string ShotId { get; } public bool Required { get; } }
    public sealed class CaptureAnnotationRule { public CaptureAnnotationRule(string ruleId, bool visibleLimit) { RuleId = ruleId ?? string.Empty; VisibleLimit = visibleLimit; } public string RuleId { get; } public bool VisibleLimit { get; } }
    public sealed class ArtPassDemoCaptureRequirements { public ArtPassDemoCaptureRequirements(IReadOnlyList<CaptureShotRequirement> requiredShots, IReadOnlyList<CaptureAnnotationRule> annotationRules) { RequiredShots = requiredShots ?? Array.Empty<CaptureShotRequirement>(); AnnotationRules = annotationRules ?? Array.Empty<CaptureAnnotationRule>(); Verdict = Shots.Any(s => RequiredShots.All(r => !ArtPassText.Same(r.ShotId, s) || !r.Required)) ? DemoCaptureVerdict.MissingShot : AnnotationRules.Count == 0 || AnnotationRules.Any(r => !r.VisibleLimit) ? DemoCaptureVerdict.MissingAnnotation : DemoCaptureVerdict.ReadyForFutureDemo; } private static readonly string[] Shots = { "DesktopOverview", "MobilePortrait", "DetailPanelOpen", "ResourceHudCloseRead", "StateTokenSample" }; public IReadOnlyList<CaptureShotRequirement> RequiredShots { get; } public IReadOnlyList<CaptureAnnotationRule> AnnotationRules { get; } public DemoCaptureVerdict Verdict { get; } }
    public sealed class PlayerPrompt { public PlayerPrompt(string promptId, bool runnable) { PromptId = promptId ?? string.Empty; Runnable = runnable; } public string PromptId { get; } public bool Runnable { get; } }
    public sealed class ExpectedAnswer { public ExpectedAnswer(string promptId, string answer) { PromptId = promptId ?? string.Empty; Answer = answer ?? string.Empty; } public string PromptId { get; } public string Answer { get; } }
    public sealed class ReadabilityBlocker { public ReadabilityBlocker(string blockerId, bool active) { BlockerId = blockerId ?? string.Empty; Active = active; } public string BlockerId { get; } public bool Active { get; } }
    public sealed class ArtPassQaReadabilityProtocol { public ArtPassQaReadabilityProtocol(IReadOnlyList<PlayerPrompt> prompts, IReadOnlyList<ExpectedAnswer> expectedAnswers, IReadOnlyList<ReadabilityBlocker> blockers) { Prompts = prompts ?? Array.Empty<PlayerPrompt>(); ExpectedAnswers = expectedAnswers ?? Array.Empty<ExpectedAnswer>(); Blockers = blockers ?? Array.Empty<ReadabilityBlocker>(); IsReady = Required.All(r => Prompts.Any(p => ArtPassText.Same(p.PromptId, r) && p.Runnable) && ExpectedAnswers.Any(a => ArtPassText.Same(a.PromptId, r))) && Blockers.All(b => !b.Active); } private static readonly string[] Required = { "FindHud", "IdentifyTwoZoneIcons", "ReadSelectionState", "ClosePanel", "SayWhatIsPreview", "RecognizeHivePortrait" }; public IReadOnlyList<PlayerPrompt> Prompts { get; } public IReadOnlyList<ExpectedAnswer> ExpectedAnswers { get; } public IReadOnlyList<ReadabilityBlocker> Blockers { get; } public bool IsReady { get; } }
    public sealed class DisplayedDataClaim { public DisplayedDataClaim(string claimId, string surface, bool reviewed) { ClaimId = claimId ?? string.Empty; Surface = surface ?? string.Empty; Reviewed = reviewed; } public string ClaimId { get; } public string Surface { get; } public bool Reviewed { get; } }
    public sealed class ForbiddenServerImplication { public ForbiddenServerImplication(string implicationId, bool detected) { ImplicationId = implicationId ?? string.Empty; Detected = detected; } public string ImplicationId { get; } public bool Detected { get; } }
    public sealed class ArtPassNonAuthoritativeGuard { public ArtPassNonAuthoritativeGuard(IReadOnlyList<DisplayedDataClaim> claimsReviewed, IReadOnlyList<ForbiddenServerImplication> forbiddenImplications) { ClaimsReviewed = claimsReviewed ?? Array.Empty<DisplayedDataClaim>(); ForbiddenImplications = forbiddenImplications ?? Array.Empty<ForbiddenServerImplication>(); Verdict = Required.Any(r => ClaimsReviewed.All(c => !ArtPassText.Same(c.ClaimId, r) || !c.Reviewed)) ? NonAuthoritativeVerdict.MissingClaimReview : ForbiddenImplications.Any(i => i.Detected) ? NonAuthoritativeVerdict.ForbiddenImplicationFound : NonAuthoritativeVerdict.SafeForPreview; } private static readonly string[] Required = { "Resources", "Capacity", "FutureRoom", "ServerRequired", "LockedState", "PreviewAction", "TactileFeedback" }; public IReadOnlyList<DisplayedDataClaim> ClaimsReviewed { get; } public IReadOnlyList<ForbiddenServerImplication> ForbiddenImplications { get; } public NonAuthoritativeVerdict Verdict { get; } }
    public sealed class ArtPassGateRow { public ArtPassGateRow(string rowId, bool passed, string evidence) { RowId = rowId ?? string.Empty; Passed = passed; Evidence = evidence ?? string.Empty; } public string RowId { get; } public bool Passed { get; } public string Evidence { get; } }
    public sealed class ArtPassRemainingReserve { public ArtPassRemainingReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class HiveProductUiArtPassGate { public HiveProductUiArtPassGate(IReadOnlyList<ArtPassGateRow> gateRows, IReadOnlyList<ArtPassRemainingReserve> remainingReserves, Bee581BlockerStatus bee581Status) { GateRows = gateRows ?? Array.Empty<ArtPassGateRow>(); RemainingReserves = remainingReserves ?? Array.Empty<ArtPassRemainingReserve>(); Bee581Status = bee581Status; Verdict = Evaluate(); } private static readonly string[] Required = { "Intake", "ResourceHud", "MaterialHierarchy", "TouchTargets", "ThumbRail", "DetailPanel", "Microcopy", "StateTokens", "ZoneIcons", "Ambience", "CellDepth", "AssetManifest", "MobilePortrait", "TactileFeedback", "FutureRooms", "Accessibility", "DemoCapture", "QaReadability", "ServerGuard" }; public IReadOnlyList<ArtPassGateRow> GateRows { get; } public IReadOnlyList<ArtPassRemainingReserve> RemainingReserves { get; } public ArtPassGateVerdict Verdict { get; } public Bee581BlockerStatus Bee581Status { get; } private ArtPassGateVerdict Evaluate() { if (Bee581Status == Bee581BlockerStatus.ReleasedByFutureArchitectDecision) return ArtPassGateVerdict.BlockedByBee581Premature; if (Required.Any(r => GateRows.All(x => !ArtPassText.Same(x.RowId, r) || !x.Passed))) return ArtPassGateVerdict.BlockedByMissingRow; if (GateRows.Any(r => ArtPassText.Contains(r.Evidence, "server official"))) return ArtPassGateVerdict.BlockedByServerClaim; return RemainingReserves.Count > 0 ? ArtPassGateVerdict.ReadyWithReserves : ArtPassGateVerdict.ReadyForArchitectReview; } }
    public static class HiveProductUiArtPassEvents { public const string HiveArtPassReserveRegistered = "HiveArtPassReserveRegistered"; public const string ResourceHudIconRefined = "ResourceHudIconRefined"; public const string BottomThumbRailRendered = "BottomThumbRailRendered"; public const string HiveArtPassGateSealed = "HiveArtPassGateSealed"; public const string Bee581BlockerConfirmed = "Bee581BlockerConfirmed"; }
    internal static class ArtPassText { public static bool Same(string left, string right) => string.Equals(left, right, StringComparison.OrdinalIgnoreCase); public static bool Contains(string source, string token) => !string.IsNullOrEmpty(source) && !string.IsNullOrEmpty(token) && source.IndexOf(token, StringComparison.OrdinalIgnoreCase) >= 0; }
}
