using System;
using System.Collections.Generic;
using System.Linq;

namespace BeeKingdom.Colony
{
    public enum HiveProductFoundationVerdict { ReadyForPreviewBuild, ReadyWithProductReserves, BlockedByMissingVisualRequirement, BlockedByProductionClaim, BlockedByBee561Premature }
    public enum HiveCellStateKind { EmptyPreview, OccupiedPreview, Locked, UpgradeCandidate, ServerRequired, Selected, SoftAlert }
    public enum HiveCellLanguageVerdict { Ready, MissingRequiredState, MissingLegend, ColorOnlyRisk }
    public enum HiveZoneLayoutVerdict { Ready, MissingRequiredZone, MissingPreviewDisclosure }
    public enum ResourceHudVerdict { Ready, MissingChip, MissingIcon, MissingNonAuthoritativeBadge }
    public enum HiveNavigationRailVerdict { Ready, MissingBottomRail, MissingRoute, LockedWithoutExplanation }
    public enum HiveRoomPreviewVerdict { Ready, MissingRoom, OfficialConstructionClaim }
    public enum HiveVisualStateVerdict { Ready, MissingRule, StateMisuseDetected }
    public enum HiveMobileFramingVerdict { Ready, MissingRule, CriticalOverlap }
    public enum HivePreviewAssetVerdict { Ready, MissingFamily, TextOnlyRejected, CriticalAssetMissing }
    public enum HiveProgressionLayerVerdict { Ready, MissingLayer, OfficialProgressionClaim }
    public enum DemoReferenceComparisonVerdict { ReadyForDemoReview, NonEmptyOnlyRejected, MissingComparisonRow }
    public enum UiVisualGapVerdict { AcceptableFoundation, AcceptableWithMajorReserves, Refused }
    public enum QaPlayerReadabilityVerdict { ReadyForObservation, FailedByMisread, MissingPrompt }
    public enum HiveDataAuthorityVerdict { SafeForPreview, MissingDataRow, ServerClaimViolation }
    public enum HiveProductRegressionVerdict { Protected, MissingEvidence, BlockingRegressionPresent }
    public enum HiveViewProductGateVerdict { ReadyForArchitectReview, ReadyWithProductReserves, BlockedByMissingEvidence, BlockedByServerClaim, BlockedByRegression, BlockedByBee561Premature }
    public enum Bee561BlockerStatus { BlockedUntilTeamValidation, ReadyForArchitectReview, ReleasedByFutureArchitectDecision }

    public sealed class HiveProductVisualRequirement { public HiveProductVisualRequirement(string requirementId, string playerValue, bool satisfied, bool productionClaim = false) { RequirementId = requirementId ?? string.Empty; PlayerValue = playerValue ?? string.Empty; Satisfied = satisfied; ProductionClaim = productionClaim; } public string RequirementId { get; } public string PlayerValue { get; } public bool Satisfied { get; } public bool ProductionClaim { get; } }
    public sealed class HiveProductReserve { public HiveProductReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class HiveViewProductUiFoundationIntake { public HiveViewProductUiFoundationIntake(IReadOnlyList<HiveProductVisualRequirement> requirements, IReadOnlyList<HiveProductReserve> openReserves) { Requirements = requirements ?? Array.Empty<HiveProductVisualRequirement>(); OpenReserves = openReserves ?? Array.Empty<HiveProductReserve>(); Verdict = Evaluate(); } private static readonly string[] Required = { "MainHive", "HexStructure", "Cells", "FunctionalZones", "IconHud", "Navigation", "Selection", "DetailPanel", "VisualStates", "DemoComparison" }; public IReadOnlyList<HiveProductVisualRequirement> Requirements { get; } public IReadOnlyList<HiveProductReserve> OpenReserves { get; } public HiveProductFoundationVerdict Verdict { get; } private HiveProductFoundationVerdict Evaluate() { if (Requirements.Any(r => r.ProductionClaim)) return HiveProductFoundationVerdict.BlockedByProductionClaim; if (Required.Any(r => Requirements.All(x => !HiveProductText.Same(x.RequirementId, r) || !x.Satisfied))) return HiveProductFoundationVerdict.BlockedByMissingVisualRequirement; return OpenReserves.Count > 0 ? HiveProductFoundationVerdict.ReadyWithProductReserves : HiveProductFoundationVerdict.ReadyForPreviewBuild; } }

    public sealed class HiveHexCell { public HiveHexCell(string cellId, int q, int r, string zoneId, HiveCellStateKind state) { CellId = cellId ?? string.Empty; Q = q; R = r; ZoneId = zoneId ?? string.Empty; State = state; } public string CellId { get; } public int Q { get; } public int R { get; } public string ZoneId { get; } public HiveCellStateKind State { get; } }
    public sealed class HiveGridFraming { public HiveGridFraming(float hudMargin, float navigationReserve, bool mobileSafe) { HudMargin = hudMargin; NavigationReserve = navigationReserve; MobileSafe = mobileSafe; } public float HudMargin { get; } public float NavigationReserve { get; } public bool MobileSafe { get; } }
    public sealed class HexagonalHiveSpatialGrid { public HexagonalHiveSpatialGrid(int ringCount, IReadOnlyList<HiveHexCell> cells, HiveGridFraming framing) { RingCount = ringCount; Cells = cells ?? Array.Empty<HiveHexCell>(); Framing = framing; IsRenderable = ringCount >= 2 && Cells.Count >= 19 && framing != null && framing.MobileSafe; } public int RingCount { get; } public IReadOnlyList<HiveHexCell> Cells { get; } public HiveGridFraming Framing { get; } public bool IsRenderable { get; } }

    public sealed class HiveCellVisualState { public HiveCellVisualState(HiveCellStateKind state, string label, string iconId, bool usesNonColorCue) { State = state; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; UsesNonColorCue = usesNonColorCue; } public HiveCellStateKind State { get; } public string Label { get; } public string IconId { get; } public bool UsesNonColorCue { get; } }
    public sealed class HiveCellLegendItem { public HiveCellLegendItem(HiveCellStateKind state, string meaning) { State = state; Meaning = meaning ?? string.Empty; } public HiveCellStateKind State { get; } public string Meaning { get; } }
    public sealed class HiveCellVisualLanguage { public HiveCellVisualLanguage(IReadOnlyList<HiveCellVisualState> states, IReadOnlyList<HiveCellLegendItem> legend) { States = states ?? Array.Empty<HiveCellVisualState>(); Legend = legend ?? Array.Empty<HiveCellLegendItem>(); Verdict = Evaluate(); } private static readonly HiveCellStateKind[] Required = { HiveCellStateKind.EmptyPreview, HiveCellStateKind.OccupiedPreview, HiveCellStateKind.Locked, HiveCellStateKind.UpgradeCandidate, HiveCellStateKind.ServerRequired }; public IReadOnlyList<HiveCellVisualState> States { get; } public IReadOnlyList<HiveCellLegendItem> Legend { get; } public HiveCellLanguageVerdict Verdict { get; } private HiveCellLanguageVerdict Evaluate() { if (Required.Any(r => States.All(s => s.State != r))) return HiveCellLanguageVerdict.MissingRequiredState; if (Required.Any(r => Legend.All(l => l.State != r))) return HiveCellLanguageVerdict.MissingLegend; if (States.Any(s => !s.UsesNonColorCue)) return HiveCellLanguageVerdict.ColorOnlyRisk; return HiveCellLanguageVerdict.Ready; } }

    public sealed class HiveFunctionalZone { public HiveFunctionalZone(string zoneId, string label, string iconId, string previewDisclosure) { ZoneId = zoneId ?? string.Empty; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; PreviewDisclosure = previewDisclosure ?? string.Empty; } public string ZoneId { get; } public string Label { get; } public string IconId { get; } public string PreviewDisclosure { get; } }
    public sealed class HiveFunctionalZoneLayout { public HiveFunctionalZoneLayout(IReadOnlyList<HiveFunctionalZone> zones) { Zones = zones ?? Array.Empty<HiveFunctionalZone>(); Verdict = Evaluate(); } private static readonly string[] Required = { "Storage", "Nursery", "Production", "Defense", "Research", "SocialGate" }; public IReadOnlyList<HiveFunctionalZone> Zones { get; } public HiveZoneLayoutVerdict Verdict { get; } private HiveZoneLayoutVerdict Evaluate() { if (Required.Any(r => Zones.All(z => !HiveProductText.Same(z.ZoneId, r)))) return HiveZoneLayoutVerdict.MissingRequiredZone; if (Zones.Any(z => string.IsNullOrWhiteSpace(z.PreviewDisclosure))) return HiveZoneLayoutVerdict.MissingPreviewDisclosure; return HiveZoneLayoutVerdict.Ready; } }

    public sealed class HiveResourceHudChip { public HiveResourceHudChip(string resourceId, string label, string iconId, string displayValue, string sourceLabel) { ResourceId = resourceId ?? string.Empty; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; DisplayValue = displayValue ?? string.Empty; SourceLabel = sourceLabel ?? string.Empty; } public string ResourceId { get; } public string Label { get; } public string IconId { get; } public string DisplayValue { get; } public string SourceLabel { get; } }
    public sealed class IconizedResourceHudForHiveView { public IconizedResourceHudForHiveView(IReadOnlyList<HiveResourceHudChip> chips, string nonAuthoritativeBadge) { Chips = chips ?? Array.Empty<HiveResourceHudChip>(); NonAuthoritativeBadge = nonAuthoritativeBadge ?? string.Empty; Verdict = Evaluate(); } private static readonly string[] Required = { "Honey", "Wax", "Pollen", "Bees", "Capacity" }; public IReadOnlyList<HiveResourceHudChip> Chips { get; } public string NonAuthoritativeBadge { get; } public ResourceHudVerdict Verdict { get; } private ResourceHudVerdict Evaluate() { if (Required.Any(r => Chips.All(c => !HiveProductText.Same(c.ResourceId, r)))) return ResourceHudVerdict.MissingChip; if (Chips.Any(c => string.IsNullOrWhiteSpace(c.IconId))) return ResourceHudVerdict.MissingIcon; return string.IsNullOrWhiteSpace(NonAuthoritativeBadge) ? ResourceHudVerdict.MissingNonAuthoritativeBadge : ResourceHudVerdict.Ready; } }
    public sealed class HiveNavRailEntry { public HiveNavRailEntry(string entryId, string label, string iconId, string lockedExplanation) { EntryId = entryId ?? string.Empty; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; LockedExplanation = lockedExplanation ?? string.Empty; } public string EntryId { get; } public string Label { get; } public string IconId { get; } public string LockedExplanation { get; } }
    public sealed class HiveViewProductNavigationRails { public HiveViewProductNavigationRails(IReadOnlyList<HiveNavRailEntry> bottomRail, IReadOnlyList<HiveNavRailEntry> sideRail) { BottomRail = bottomRail ?? Array.Empty<HiveNavRailEntry>(); SideRail = sideRail ?? Array.Empty<HiveNavRailEntry>(); Verdict = Evaluate(); } private static readonly string[] Required = { "Hive", "Actions", "World", "Alliance", "Army", "Research" }; public IReadOnlyList<HiveNavRailEntry> BottomRail { get; } public IReadOnlyList<HiveNavRailEntry> SideRail { get; } public HiveNavigationRailVerdict Verdict { get; } private HiveNavigationRailVerdict Evaluate() { if (BottomRail.Count == 0) return HiveNavigationRailVerdict.MissingBottomRail; if (Required.Any(r => BottomRail.Concat(SideRail).All(e => !HiveProductText.Same(e.EntryId, r)))) return HiveNavigationRailVerdict.MissingRoute; if (BottomRail.Concat(SideRail).Any(e => HiveProductText.Contains(e.Label, "locked") && string.IsNullOrWhiteSpace(e.LockedExplanation))) return HiveNavigationRailVerdict.LockedWithoutExplanation; return HiveNavigationRailVerdict.Ready; } }

    public sealed class HiveRoomPreviewSlot { public HiveRoomPreviewSlot(string roomId, string cellId, string label, string iconId, string previewState, bool officialConstructionClaim = false) { RoomId = roomId ?? string.Empty; CellId = cellId ?? string.Empty; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; PreviewState = previewState ?? string.Empty; OfficialConstructionClaim = officialConstructionClaim; } public string RoomId { get; } public string CellId { get; } public string Label { get; } public string IconId { get; } public string PreviewState { get; } public bool OfficialConstructionClaim { get; } }
    public sealed class HiveRoomPlacementRule { public HiveRoomPlacementRule(string ruleId, string explanation) { RuleId = ruleId ?? string.Empty; Explanation = explanation ?? string.Empty; } public string RuleId { get; } public string Explanation { get; } }
    public sealed class HiveBuildingSlotRoomPreview { public HiveBuildingSlotRoomPreview(IReadOnlyList<HiveRoomPreviewSlot> roomSlots, IReadOnlyList<HiveRoomPlacementRule> placementRules) { RoomSlots = roomSlots ?? Array.Empty<HiveRoomPreviewSlot>(); PlacementRules = placementRules ?? Array.Empty<HiveRoomPlacementRule>(); Verdict = Evaluate(); } private static readonly string[] Required = { "StorageRoom", "NurseryRoom", "WorkshopRoom", "DefensePost", "ResearchCell" }; public IReadOnlyList<HiveRoomPreviewSlot> RoomSlots { get; } public IReadOnlyList<HiveRoomPlacementRule> PlacementRules { get; } public HiveRoomPreviewVerdict Verdict { get; } private HiveRoomPreviewVerdict Evaluate() { if (RoomSlots.Any(r => r.OfficialConstructionClaim)) return HiveRoomPreviewVerdict.OfficialConstructionClaim; if (Required.Any(r => RoomSlots.All(s => !HiveProductText.Same(s.RoomId, r)))) return HiveRoomPreviewVerdict.MissingRoom; return HiveRoomPreviewVerdict.Ready; } }
    public sealed class HiveFocusFeedback { public HiveFocusFeedback(string feedbackId, string description, bool nonColorCue) { FeedbackId = feedbackId ?? string.Empty; Description = description ?? string.Empty; NonColorCue = nonColorCue; } public string FeedbackId { get; } public string Description { get; } public bool NonColorCue { get; } }
    public sealed class HiveCellSelectionFocus { public HiveCellSelectionFocus(string focusedCellId, string focusReason, IReadOnlyList<HiveFocusFeedback> feedbacks) { FocusedCellId = focusedCellId ?? string.Empty; FocusReason = focusReason ?? string.Empty; Feedbacks = feedbacks ?? Array.Empty<HiveFocusFeedback>(); IsVisible = !string.IsNullOrWhiteSpace(FocusedCellId) && Feedbacks.Count >= 4 && Feedbacks.All(f => f.NonColorCue); } public string FocusedCellId { get; } public string FocusReason { get; } public IReadOnlyList<HiveFocusFeedback> Feedbacks { get; } public bool IsVisible { get; } }

    public sealed class HiveCellPanelHeader { public HiveCellPanelHeader(string roomName, string cellId, string iconId) { RoomName = roomName ?? string.Empty; CellId = cellId ?? string.Empty; IconId = iconId ?? string.Empty; } public string RoomName { get; } public string CellId { get; } public string IconId { get; } }
    public sealed class HiveCellPanelFact { public HiveCellPanelFact(string factId, string playerText) { FactId = factId ?? string.Empty; PlayerText = playerText ?? string.Empty; } public string FactId { get; } public string PlayerText { get; } }
    public sealed class HiveCellPanelConstraint { public HiveCellPanelConstraint(string constraintId, string playerText) { ConstraintId = constraintId ?? string.Empty; PlayerText = playerText ?? string.Empty; } public string ConstraintId { get; } public string PlayerText { get; } }
    public sealed class HiveCellPanelAuthorityNote { public HiveCellPanelAuthorityNote(string text, bool nonAuthoritative) { Text = text ?? string.Empty; NonAuthoritative = nonAuthoritative; } public string Text { get; } public bool NonAuthoritative { get; } }
    public sealed class HiveCellDetailPlayerPanel { public HiveCellDetailPlayerPanel(HiveCellPanelHeader header, IReadOnlyList<HiveCellPanelFact> facts, IReadOnlyList<HiveCellPanelConstraint> constraints, HiveCellPanelAuthorityNote authorityNote) { Header = header; Facts = facts ?? Array.Empty<HiveCellPanelFact>(); Constraints = constraints ?? Array.Empty<HiveCellPanelConstraint>(); AuthorityNote = authorityNote; IsReadable = header != null && Facts.Count >= 3 && Constraints.Count >= 2 && authorityNote != null && authorityNote.NonAuthoritative; } public HiveCellPanelHeader Header { get; } public IReadOnlyList<HiveCellPanelFact> Facts { get; } public IReadOnlyList<HiveCellPanelConstraint> Constraints { get; } public HiveCellPanelAuthorityNote AuthorityNote { get; } public bool IsReadable { get; } }

    public sealed class HiveVisualStateRule { public HiveVisualStateRule(string stateId, string appliesTo, string iconId, bool nonColorCue) { StateId = stateId ?? string.Empty; AppliesTo = appliesTo ?? string.Empty; IconId = iconId ?? string.Empty; NonColorCue = nonColorCue; } public string StateId { get; } public string AppliesTo { get; } public string IconId { get; } public bool NonColorCue { get; } }
    public sealed class HiveVisualStateMisuse { public HiveVisualStateMisuse(string misuseId, string description) { MisuseId = misuseId ?? string.Empty; Description = description ?? string.Empty; } public string MisuseId { get; } public string Description { get; } }
    public sealed class HiveViewVisualStateLanguage { public HiveViewVisualStateLanguage(IReadOnlyList<HiveVisualStateRule> rules, IReadOnlyList<HiveVisualStateMisuse> misuses) { Rules = rules ?? Array.Empty<HiveVisualStateRule>(); Misuses = misuses ?? Array.Empty<HiveVisualStateMisuse>(); Verdict = Evaluate(); } private static readonly string[] Required = { "Normal", "Locked", "Preview", "ServerRequired", "Selected", "SoftAlert" }; public IReadOnlyList<HiveVisualStateRule> Rules { get; } public IReadOnlyList<HiveVisualStateMisuse> Misuses { get; } public HiveVisualStateVerdict Verdict { get; } private HiveVisualStateVerdict Evaluate() { if (Required.Any(r => Rules.All(x => !HiveProductText.Same(x.StateId, r)))) return HiveVisualStateVerdict.MissingRule; if (Misuses.Count > 0) return HiveVisualStateVerdict.StateMisuseDetected; return Rules.Any(r => !r.NonColorCue) ? HiveVisualStateVerdict.StateMisuseDetected : HiveVisualStateVerdict.Ready; } }
    public sealed class HiveMobileSafeArea { public HiveMobileSafeArea(float top, float bottom, float left, float right) { Top = top; Bottom = bottom; Left = left; Right = right; } public float Top { get; } public float Bottom { get; } public float Left { get; } public float Right { get; } public bool IsValid => Top >= 0f && Bottom >= 0f && Left >= 0f && Right >= 0f; }
    public sealed class HiveMobileLayoutRule { public HiveMobileLayoutRule(string ruleId, bool satisfied, string failure = "") { RuleId = ruleId ?? string.Empty; Satisfied = satisfied; Failure = failure ?? string.Empty; } public string RuleId { get; } public bool Satisfied { get; } public string Failure { get; } }
    public sealed class MobilePortraitHiveViewFraming { public MobilePortraitHiveViewFraming(HiveMobileSafeArea safeArea, IReadOnlyList<HiveMobileLayoutRule> layoutRules) { SafeArea = safeArea; LayoutRules = layoutRules ?? Array.Empty<HiveMobileLayoutRule>(); Verdict = Evaluate(); } private static readonly string[] Required = { "CentralGrid", "TopHud", "BottomRail", "RetractableDetail", "CompactLabels", "TouchSelection", "NoCutText" }; public HiveMobileSafeArea SafeArea { get; } public IReadOnlyList<HiveMobileLayoutRule> LayoutRules { get; } public HiveMobileFramingVerdict Verdict { get; } private HiveMobileFramingVerdict Evaluate() { if (safeMissing()) return HiveMobileFramingVerdict.CriticalOverlap; if (Required.Any(r => LayoutRules.All(x => !HiveProductText.Same(x.RuleId, r)))) return HiveMobileFramingVerdict.MissingRule; return LayoutRules.Any(r => !r.Satisfied) ? HiveMobileFramingVerdict.CriticalOverlap : HiveMobileFramingVerdict.Ready; bool safeMissing() => SafeArea == null || !SafeArea.IsValid; } }

    public sealed class HiveAssetFamily { public HiveAssetFamily(string familyId, string usage, bool available, bool textOnly = false) { FamilyId = familyId ?? string.Empty; Usage = usage ?? string.Empty; Available = available; TextOnly = textOnly; } public string FamilyId { get; } public string Usage { get; } public bool Available { get; } public bool TextOnly { get; } }
    public sealed class HiveAssetReplacementRule { public HiveAssetReplacementRule(string familyId, string replacementPath) { FamilyId = familyId ?? string.Empty; ReplacementPath = replacementPath ?? string.Empty; } public string FamilyId { get; } public string ReplacementPath { get; } }
    public sealed class ProfessionalPreviewAssetSetForHiveView { public ProfessionalPreviewAssetSetForHiveView(IReadOnlyList<HiveAssetFamily> families, IReadOnlyList<HiveAssetReplacementRule> replacementRules) { Families = families ?? Array.Empty<HiveAssetFamily>(); ReplacementRules = replacementRules ?? Array.Empty<HiveAssetReplacementRule>(); Verdict = Evaluate(); } private static readonly string[] Required = { "CellShapes", "RoomPictograms", "ResourceGlyphs", "StatusBadges", "PanelFrames", "NavigationMarks", "SelectionEffects", "BackgroundTextures" }; public IReadOnlyList<HiveAssetFamily> Families { get; } public IReadOnlyList<HiveAssetReplacementRule> ReplacementRules { get; } public HivePreviewAssetVerdict Verdict { get; } private HivePreviewAssetVerdict Evaluate() { if (Families.Any(f => f.TextOnly)) return HivePreviewAssetVerdict.TextOnlyRejected; if (Required.Any(r => Families.All(f => !HiveProductText.Same(f.FamilyId, r)))) return HivePreviewAssetVerdict.MissingFamily; if (Families.Any(f => !f.Available)) return HivePreviewAssetVerdict.CriticalAssetMissing; return HivePreviewAssetVerdict.Ready; } }
    public sealed class HiveProgressionLayer { public HiveProgressionLayer(string layerId, string visualDifference, bool officialClaim = false) { LayerId = layerId ?? string.Empty; VisualDifference = visualDifference ?? string.Empty; OfficialClaim = officialClaim; } public string LayerId { get; } public string VisualDifference { get; } public bool OfficialClaim { get; } }
    public sealed class HiveProgressionVisualLayers { public HiveProgressionVisualLayers(IReadOnlyList<HiveProgressionLayer> layers, string officialProgressionForbiddenClaim) { Layers = layers ?? Array.Empty<HiveProgressionLayer>(); OfficialProgressionForbiddenClaim = officialProgressionForbiddenClaim ?? string.Empty; Verdict = Evaluate(); } private static readonly string[] Required = { "EarlyHive", "GrowingHive", "FortifiedHive" }; public IReadOnlyList<HiveProgressionLayer> Layers { get; } public string OfficialProgressionForbiddenClaim { get; } public HiveProgressionLayerVerdict Verdict { get; } private HiveProgressionLayerVerdict Evaluate() { if (Layers.Any(l => l.OfficialClaim)) return HiveProgressionLayerVerdict.OfficialProgressionClaim; if (Required.Any(r => Layers.All(l => !HiveProductText.Same(l.LayerId, r)))) return HiveProgressionLayerVerdict.MissingLayer; return HiveProgressionLayerVerdict.Ready; } }

    public sealed class DemoVisualComparisonRow { public DemoVisualComparisonRow(string rowId, bool compared, string gap) { RowId = rowId ?? string.Empty; Compared = compared; Gap = gap ?? string.Empty; } public string RowId { get; } public bool Compared { get; } public string Gap { get; } }
    public sealed class DemoReferenceComparisonContract { public DemoReferenceComparisonContract(string referenceId, IReadOnlyList<DemoVisualComparisonRow> rows) { ReferenceId = referenceId ?? string.Empty; Rows = rows ?? Array.Empty<DemoVisualComparisonRow>(); Verdict = Evaluate(); } private static readonly string[] Required = { "CentralHive", "Hexagons", "Cells", "Zones", "HudIcons", "Navigation", "Selection", "DetailPanel", "Mobile", "Assets" }; public string ReferenceId { get; } public IReadOnlyList<DemoVisualComparisonRow> Rows { get; } public DemoReferenceComparisonVerdict Verdict { get; } private DemoReferenceComparisonVerdict Evaluate() { if (HiveProductText.Contains(ReferenceId, "non-empty")) return DemoReferenceComparisonVerdict.NonEmptyOnlyRejected; if (Required.Any(r => Rows.All(x => !HiveProductText.Same(x.RowId, r) || !x.Compared))) return DemoReferenceComparisonVerdict.MissingComparisonRow; return DemoReferenceComparisonVerdict.ReadyForDemoReview; } }
    public sealed class UiVisualScoreRow { public UiVisualScoreRow(string axisId, int score, string note) { AxisId = axisId ?? string.Empty; Score = score; Note = note ?? string.Empty; } public string AxisId { get; } public int Score { get; } public string Note { get; } }
    public sealed class UiVisualPriorityFix { public UiVisualPriorityFix(string fixId, string description) { FixId = fixId ?? string.Empty; Description = description ?? string.Empty; } public string FixId { get; } public string Description { get; } }
    public sealed class UiVisualGapReviewChecklist { public UiVisualGapReviewChecklist(IReadOnlyList<UiVisualScoreRow> scoreRows, IReadOnlyList<UiVisualPriorityFix> priorityFixes) { ScoreRows = scoreRows ?? Array.Empty<UiVisualScoreRow>(); PriorityFixes = priorityFixes ?? Array.Empty<UiVisualPriorityFix>(); Verdict = ScoreRows.Any(s => s.Score <= 1) ? UiVisualGapVerdict.Refused : ScoreRows.Any(s => s.Score <= 3) || PriorityFixes.Count >= 3 ? UiVisualGapVerdict.AcceptableWithMajorReserves : UiVisualGapVerdict.AcceptableFoundation; } public IReadOnlyList<UiVisualScoreRow> ScoreRows { get; } public IReadOnlyList<UiVisualPriorityFix> PriorityFixes { get; } public UiVisualGapVerdict Verdict { get; } }
    public sealed class QaObservationPrompt { public QaObservationPrompt(string promptId, string expectedAnswer, bool runnable) { PromptId = promptId ?? string.Empty; ExpectedAnswer = expectedAnswer ?? string.Empty; Runnable = runnable; } public string PromptId { get; } public string ExpectedAnswer { get; } public bool Runnable { get; } }
    public sealed class QaMisreadPattern { public QaMisreadPattern(string patternId, string description, bool failed) { PatternId = patternId ?? string.Empty; Description = description ?? string.Empty; Failed = failed; } public string PatternId { get; } public string Description { get; } public bool Failed { get; } }
    public sealed class QaPlayerReadabilityValidation { public QaPlayerReadabilityValidation(IReadOnlyList<QaObservationPrompt> observationPrompts, IReadOnlyList<QaMisreadPattern> misreadPatterns) { ObservationPrompts = observationPrompts ?? Array.Empty<QaObservationPrompt>(); MisreadPatterns = misreadPatterns ?? Array.Empty<QaMisreadPattern>(); Verdict = ObservationPrompts.Count < 7 || ObservationPrompts.Any(p => !p.Runnable) ? QaPlayerReadabilityVerdict.MissingPrompt : MisreadPatterns.Any(m => m.Failed) ? QaPlayerReadabilityVerdict.FailedByMisread : QaPlayerReadabilityVerdict.ReadyForObservation; } public IReadOnlyList<QaObservationPrompt> ObservationPrompts { get; } public IReadOnlyList<QaMisreadPattern> MisreadPatterns { get; } public QaPlayerReadabilityVerdict Verdict { get; } }

    public sealed class HiveDisplayedDataRow { public HiveDisplayedDataRow(string dataId, string source, string authorityStatus, bool serverTruthClaim) { DataId = dataId ?? string.Empty; Source = source ?? string.Empty; AuthorityStatus = authorityStatus ?? string.Empty; ServerTruthClaim = serverTruthClaim; } public string DataId { get; } public string Source { get; } public string AuthorityStatus { get; } public bool ServerTruthClaim { get; } }
    public sealed class HiveServerClaimViolation { public HiveServerClaimViolation(string violationId, string description) { ViolationId = violationId ?? string.Empty; Description = description ?? string.Empty; } public string ViolationId { get; } public string Description { get; } }
    public sealed class ServerNonAuthoritativeHiveViewDataGuard { public ServerNonAuthoritativeHiveViewDataGuard(IReadOnlyList<HiveDisplayedDataRow> rows, IReadOnlyList<HiveServerClaimViolation> violations) { Rows = rows ?? Array.Empty<HiveDisplayedDataRow>(); Violations = violations ?? Array.Empty<HiveServerClaimViolation>(); Verdict = Rows.Count < 8 ? HiveDataAuthorityVerdict.MissingDataRow : Rows.Any(r => r.ServerTruthClaim) || Violations.Count > 0 ? HiveDataAuthorityVerdict.ServerClaimViolation : HiveDataAuthorityVerdict.SafeForPreview; } public IReadOnlyList<HiveDisplayedDataRow> Rows { get; } public IReadOnlyList<HiveServerClaimViolation> Violations { get; } public HiveDataAuthorityVerdict Verdict { get; } }
    public sealed class BuilderHiveViewRuntimeProofPackage { public BuilderHiveViewRuntimeProofPackage(string sceneName, string hiveViewRootName, IReadOnlyList<string> assetIds, IReadOnlyList<string> evidenceFiles) { SceneName = sceneName ?? string.Empty; HiveViewRootName = hiveViewRootName ?? string.Empty; AssetIds = assetIds ?? Array.Empty<string>(); EvidenceFiles = evidenceFiles ?? Array.Empty<string>(); IsComplete = !string.IsNullOrWhiteSpace(SceneName) && !string.IsNullOrWhiteSpace(HiveViewRootName) && AssetIds.Count >= 8 && EvidenceFiles.Count >= 3; } public string SceneName { get; } public string HiveViewRootName { get; } public IReadOnlyList<string> AssetIds { get; } public IReadOnlyList<string> EvidenceFiles { get; } public bool IsComplete { get; } }
    public sealed class HiveProductRegressionCondition { public HiveProductRegressionCondition(string conditionId, bool blocking) { ConditionId = conditionId ?? string.Empty; Blocking = blocking; } public string ConditionId { get; } public bool Blocking { get; } }
    public sealed class HiveProductRegressionEvidence { public HiveProductRegressionEvidence(string evidenceId, bool present) { EvidenceId = evidenceId ?? string.Empty; Present = present; } public string EvidenceId { get; } public bool Present { get; } }
    public sealed class HiveViewProductRegressionRule { public HiveViewProductRegressionRule(IReadOnlyList<HiveProductRegressionCondition> blockingConditions, IReadOnlyList<HiveProductRegressionEvidence> evidence) { BlockingConditions = blockingConditions ?? Array.Empty<HiveProductRegressionCondition>(); Evidence = evidence ?? Array.Empty<HiveProductRegressionEvidence>(); Verdict = BlockingConditions.Any(c => c.Blocking) ? HiveProductRegressionVerdict.BlockingRegressionPresent : Evidence.Count < 8 || Evidence.Any(e => !e.Present) ? HiveProductRegressionVerdict.MissingEvidence : HiveProductRegressionVerdict.Protected; } public IReadOnlyList<HiveProductRegressionCondition> BlockingConditions { get; } public IReadOnlyList<HiveProductRegressionEvidence> Evidence { get; } public HiveProductRegressionVerdict Verdict { get; } }
    public sealed class HiveViewDecisionLedgerRow { public HiveViewDecisionLedgerRow(string rowId, bool passed, string evidence) { RowId = rowId ?? string.Empty; Passed = passed; Evidence = evidence ?? string.Empty; } public string RowId { get; } public bool Passed { get; } public string Evidence { get; } }
    public sealed class HiveViewProductReserve { public HiveViewProductReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class HiveViewProductUiFoundationGate { public HiveViewProductUiFoundationGate(IReadOnlyList<HiveViewDecisionLedgerRow> decisionLedger, IReadOnlyList<HiveViewProductReserve> productReserves, Bee561BlockerStatus bee561Status) { DecisionLedger = decisionLedger ?? Array.Empty<HiveViewDecisionLedgerRow>(); ProductReserves = productReserves ?? Array.Empty<HiveViewProductReserve>(); Bee561Status = bee561Status; Verdict = Evaluate(); } private static readonly string[] Required = { "VisualFoundation", "HexGrid", "CellLanguage", "FunctionalZones", "IconHud", "Navigation", "RoomSlots", "Selection", "DetailDrawer", "StateLanguage", "MobileFrame", "AssetLibrary", "ProgressionLayers", "DemoComparison", "UiScorecard", "QaObservation", "ServerGuard", "BuilderProof", "RegressionRule" }; public IReadOnlyList<HiveViewDecisionLedgerRow> DecisionLedger { get; } public IReadOnlyList<HiveViewProductReserve> ProductReserves { get; } public HiveViewProductGateVerdict Verdict { get; } public Bee561BlockerStatus Bee561Status { get; } private HiveViewProductGateVerdict Evaluate() { if (Bee561Status == Bee561BlockerStatus.ReleasedByFutureArchitectDecision) return HiveViewProductGateVerdict.BlockedByBee561Premature; if (Required.Any(r => DecisionLedger.All(x => !HiveProductText.Same(x.RowId, r) || !x.Passed))) return HiveViewProductGateVerdict.BlockedByMissingEvidence; if (DecisionLedger.Any(r => HiveProductText.Contains(r.Evidence, "server official"))) return HiveViewProductGateVerdict.BlockedByServerClaim; if (DecisionLedger.Any(r => HiveProductText.Contains(r.Evidence, "regression"))) return HiveViewProductGateVerdict.BlockedByRegression; return ProductReserves.Count > 0 ? HiveViewProductGateVerdict.ReadyWithProductReserves : HiveViewProductGateVerdict.ReadyForArchitectReview; } }
    public static class HiveViewProductUiFoundationEvents { public const string HiveProductFoundationIntakeOpened = "HiveProductFoundationIntakeOpened"; public const string HiveHexGridRendered = "HiveHexGridRendered"; public const string HiveCellFocused = "HiveCellFocused"; public const string HiveViewDecisionLedgerSealed = "HiveViewDecisionLedgerSealed"; public const string Bee561BlockerConfirmed = "Bee561BlockerConfirmed"; }
    internal static class HiveProductText { public static bool Same(string left, string right) => string.Equals(left, right, StringComparison.OrdinalIgnoreCase); public static bool Contains(string source, string token) => !string.IsNullOrEmpty(source) && !string.IsNullOrEmpty(token) && source.IndexOf(token, StringComparison.OrdinalIgnoreCase) >= 0; }
}
