using System;
using System.Collections.Generic;
using System.Linq;

namespace BeeKingdom.Colony
{
    public enum Bee600GateStatus { PreparingEvidence, ReadyForReview, Blocked }
    public enum AssetReplacementVerdict { Ready, MissingReplacement, MissingFallback }
    public enum PortraitEvidenceVerdict { Ready, MissingCheck, DeviceReserveRequired }
    public enum VisualShotListVerdict { Ready, MissingShot, MissingFailureRule }
    public enum ResourceHudCaptureMode { OverviewAndPortrait, CloseRead, ReducedView }
    public enum ResourceHudReadabilityVerdict { Ready, MissingRule, OfficialBalanceRisk }
    public enum GestureClarityVerdict { Ready, MissingPath, MissingFeedback }
    public enum AtmosphereVerdict { Ready, TooHeavy, ReadabilityRisk }
    public enum ZoneIconRecognitionVerdict { Ready, MissingZone, MissingVariant, Ambiguous }
    public enum DeviceAccessibilityVerdict { Ready, ReadyWithDeviceReserve, Failed }
    public enum FirstSessionVerdict { Ready, MissingStep, MissingCheckpoint }
    public enum NonClaimDisclosureVerdict { Ready, MissingRow, ForbiddenClaim }
    public enum DemoEvidenceVerdict { ReadyForDemo, MissingStep, MissingManifest }
    public enum UiScorecardVerdict { Ready, NeedsReview, Blocked }
    public enum ServerClaimAuditVerdict { SafeForVisualEvidence, MissingCheck, ForbiddenSignal }
    public enum BuilderEvidenceVerdict { ReadyForDemo, MissingArtifact, ReserveOnly }
    public enum RegressionLockVerdict { Clear, Blocked, ClearWithReserves }
    public enum CrossTeamVisualVerdict { ReadyForGate, WaitingForTeams, Blocked }
    public enum VisualMilestoneDecision { AwaitingArchitectReview, PassWithReserves, Blocked }
    public enum Bee601BlockerStatus { BlockedUntilBee600Validation, ReadyForFutureArchitectDecision }

    public sealed class ArtPass2Reserve { public ArtPass2Reserve(string reserveId, string mappedBee, bool addressed) { ReserveId = reserveId ?? string.Empty; MappedBee = mappedBee ?? string.Empty; Addressed = addressed; } public string ReserveId { get; } public string MappedBee { get; } public bool Addressed { get; } }
    public sealed class VisualEvidenceTarget { public VisualEvidenceTarget(string targetId, string owningBee, bool required) { TargetId = targetId ?? string.Empty; OwningBee = owningBee ?? string.Empty; Required = required; } public string TargetId { get; } public string OwningBee { get; } public bool Required { get; } }
    public sealed class HiveProductUiArtPass2Intake { private static readonly string[] Required = { "FinalAssets", "MobileDevicePortrait", "DedicatedCapture", "AccessibilityDeviceAudit", "UiScorecard", "QaReadability", "ServerNonClaims", "BuilderBundle" }; public HiveProductUiArtPass2Intake(IReadOnlyList<ArtPass2Reserve> reserves, IReadOnlyList<VisualEvidenceTarget> evidenceTargets, Bee600GateStatus bee600Gate) { Reserves = reserves ?? Array.Empty<ArtPass2Reserve>(); EvidenceTargets = evidenceTargets ?? Array.Empty<VisualEvidenceTarget>(); Bee600Gate = Required.All(r => EvidenceTargets.Any(t => Text600.Same(t.TargetId, r) && t.Required)) ? bee600Gate : Bee600GateStatus.Blocked; } public IReadOnlyList<ArtPass2Reserve> Reserves { get; } public IReadOnlyList<VisualEvidenceTarget> EvidenceTargets { get; } public Bee600GateStatus Bee600Gate { get; } }

    public sealed class AssetReplacementRow { public AssetReplacementRow(string category, string sourceAsset, string targetAsset, string mobileVariant) { Category = category ?? string.Empty; SourceAsset = sourceAsset ?? string.Empty; TargetAsset = targetAsset ?? string.Empty; MobileVariant = mobileVariant ?? string.Empty; } public string Category { get; } public string SourceAsset { get; } public string TargetAsset { get; } public string MobileVariant { get; } public bool HasReplacement => !string.IsNullOrWhiteSpace(TargetAsset) && !string.IsNullOrWhiteSpace(MobileVariant); }
    public sealed class AssetFallbackRule { public AssetFallbackRule(string category, bool keepsReadability) { Category = category ?? string.Empty; KeepsReadability = keepsReadability; } public string Category { get; } public bool KeepsReadability { get; } }
    public sealed class FinalHiveAssetReplacementPlan { private static readonly string[] Categories = { "ResourceIcons", "ZoneIcons", "StateBadges", "WaxTexture", "CellBorders", "DetailPanelChrome", "BottomRailIcons" }; public FinalHiveAssetReplacementPlan(IReadOnlyList<AssetReplacementRow> replacements, IReadOnlyList<AssetFallbackRule> fallbackRules) { Replacements = replacements ?? Array.Empty<AssetReplacementRow>(); FallbackRules = fallbackRules ?? Array.Empty<AssetFallbackRule>(); Verdict = Categories.Any(c => Replacements.All(r => !Text600.Same(r.Category, c) || !r.HasReplacement)) ? AssetReplacementVerdict.MissingReplacement : Categories.Any(c => FallbackRules.All(r => !Text600.Same(r.Category, c) || !r.KeepsReadability)) ? AssetReplacementVerdict.MissingFallback : AssetReplacementVerdict.Ready; } public IReadOnlyList<AssetReplacementRow> Replacements { get; } public IReadOnlyList<AssetFallbackRule> FallbackRules { get; } public AssetReplacementVerdict Verdict { get; } }

    public sealed class PortraitEvidenceShot { public PortraitEvidenceShot(string shotId, string deviceProfile, bool realDeviceAvailable) { ShotId = shotId ?? string.Empty; DeviceProfile = deviceProfile ?? string.Empty; RealDeviceAvailable = realDeviceAvailable; } public string ShotId { get; } public string DeviceProfile { get; } public bool RealDeviceAvailable { get; } }
    public sealed class PortraitReadabilityCheck { public PortraitReadabilityCheck(string checkId, bool passes) { CheckId = checkId ?? string.Empty; Passes = passes; } public string CheckId { get; } public bool Passes { get; } }
    public sealed class MobileDevicePortraitEvidence { private static readonly string[] Required = { "HudVisible", "HiveVisible", "RailAccessible", "PanelCollapsible", "SelectionReadable", "PreviewDisclosureVisible" }; public MobileDevicePortraitEvidence(PortraitEvidenceShot requiredShot, IReadOnlyList<PortraitReadabilityCheck> checks) { RequiredShot = requiredShot; Checks = checks ?? Array.Empty<PortraitReadabilityCheck>(); Verdict = Required.Any(r => Checks.All(c => !Text600.Same(c.CheckId, r) || !c.Passes)) ? PortraitEvidenceVerdict.MissingCheck : requiredShot == null || !requiredShot.RealDeviceAvailable ? PortraitEvidenceVerdict.DeviceReserveRequired : PortraitEvidenceVerdict.Ready; } public PortraitEvidenceShot RequiredShot { get; } public IReadOnlyList<PortraitReadabilityCheck> Checks { get; } public PortraitEvidenceVerdict Verdict { get; } }

    public sealed class VisualShotSpec { public VisualShotSpec(string shotId, string content, bool annotated) { ShotId = shotId ?? string.Empty; Content = content ?? string.Empty; Annotated = annotated; } public string ShotId { get; } public string Content { get; } public bool Annotated { get; } }
    public sealed class VisualShotFailureRule { public VisualShotFailureRule(string shotId, string refusalReason) { ShotId = shotId ?? string.Empty; RefusalReason = refusalReason ?? string.Empty; } public string ShotId { get; } public string RefusalReason { get; } }
    public sealed class Bee600VisualShotList { private static readonly string[] Required = { "OverviewDesktop", "MobilePortrait", "DetailOpen", "HudCloseRead", "StateTokenSample", "EmptyLockedFutureRoom", "AccessibilityReducedView" }; public Bee600VisualShotList(IReadOnlyList<VisualShotSpec> requiredShots, IReadOnlyList<VisualShotFailureRule> failureRules) { RequiredShots = requiredShots ?? Array.Empty<VisualShotSpec>(); FailureRules = failureRules ?? Array.Empty<VisualShotFailureRule>(); Verdict = Required.Any(r => RequiredShots.All(s => !Text600.Same(s.ShotId, r) || !s.Annotated)) ? VisualShotListVerdict.MissingShot : Required.Any(r => FailureRules.All(f => !Text600.Same(f.ShotId, r))) ? VisualShotListVerdict.MissingFailureRule : VisualShotListVerdict.Ready; } public IReadOnlyList<VisualShotSpec> RequiredShots { get; } public IReadOnlyList<VisualShotFailureRule> FailureRules { get; } public VisualShotListVerdict Verdict { get; } }

    public sealed class ResourceChipReadabilityRule { public ResourceChipReadabilityRule(string ruleId, bool passes, bool officialBalanceRisk = false) { RuleId = ruleId ?? string.Empty; Passes = passes; OfficialBalanceRisk = officialBalanceRisk; } public string RuleId { get; } public bool Passes { get; } public bool OfficialBalanceRisk { get; } }
    public sealed class ResourceHudFinalReadability { private static readonly string[] Required = { "RecognizableIcon", "ShortLabel", "UnofficialValue", "LocalBadge", "StableOrder", "Contrast" }; public ResourceHudFinalReadability(IReadOnlyList<ResourceChipReadabilityRule> rules, ResourceHudCaptureMode captureMode) { Rules = rules ?? Array.Empty<ResourceChipReadabilityRule>(); CaptureMode = captureMode; Verdict = Rules.Any(r => r.OfficialBalanceRisk) ? ResourceHudReadabilityVerdict.OfficialBalanceRisk : Required.Any(r => Rules.All(x => !Text600.Same(x.RuleId, r) || !x.Passes)) ? ResourceHudReadabilityVerdict.MissingRule : ResourceHudReadabilityVerdict.Ready; } public IReadOnlyList<ResourceChipReadabilityRule> Rules { get; } public ResourceHudCaptureMode CaptureMode { get; } public ResourceHudReadabilityVerdict Verdict { get; } }

    public sealed class PanelSpacingRule { public PanelSpacingRule(string areaId, int minPixels, bool passes) { AreaId = areaId ?? string.Empty; MinPixels = minPixels; Passes = passes; } public string AreaId { get; } public int MinPixels { get; } public bool Passes { get; } }
    public sealed class PanelTextFitRule { public PanelTextFitRule(bool nameFits, bool disclosureFits, bool closeVisible) { NameFits = nameFits; DisclosureFits = disclosureFits; CloseVisible = closeVisible; } public bool NameFits { get; } public bool DisclosureFits { get; } public bool CloseVisible { get; } public bool Passes => NameFits && DisclosureFits && CloseVisible; }
    public sealed class DetailPanelFinalHierarchy { public DetailPanelFinalHierarchy(PanelSpacingRule headerSpacing, PanelSpacingRule stateSpacing, PanelSpacingRule disclosureSpacing, PanelTextFitRule textFit) { HeaderSpacing = headerSpacing; StateSpacing = stateSpacing; DisclosureSpacing = disclosureSpacing; TextFit = textFit; IsReady = new[] { headerSpacing, stateSpacing, disclosureSpacing }.All(r => r != null && r.Passes && r.MinPixels >= 8) && textFit != null && textFit.Passes; } public PanelSpacingRule HeaderSpacing { get; } public PanelSpacingRule StateSpacing { get; } public PanelSpacingRule DisclosureSpacing { get; } public PanelTextFitRule TextFit { get; } public bool IsReady { get; } }

    public sealed class GesturePath { public GesturePath(string pathId, string feedback, bool previewOnly) { PathId = pathId ?? string.Empty; Feedback = feedback ?? string.Empty; PreviewOnly = previewOnly; } public string PathId { get; } public string Feedback { get; } public bool PreviewOnly { get; } }
    public sealed class RailCoherenceRule { public RailCoherenceRule(string ruleId, bool passes) { RuleId = ruleId ?? string.Empty; Passes = passes; } public string RuleId { get; } public bool Passes { get; } }
    public sealed class GesturePathClarityMap { private static readonly string[] Required = { "SelectCell", "OpenDetail", "CloseDetail", "ReturnHome", "SwitchLens", "ReadPreview" }; public GesturePathClarityMap(IReadOnlyList<GesturePath> paths, IReadOnlyList<RailCoherenceRule> railRules) { Paths = paths ?? Array.Empty<GesturePath>(); RailRules = railRules ?? Array.Empty<RailCoherenceRule>(); Verdict = Required.Any(r => Paths.All(p => !Text600.Same(p.PathId, r) || !p.PreviewOnly)) ? GestureClarityVerdict.MissingPath : Paths.Any(p => string.IsNullOrWhiteSpace(p.Feedback)) || RailRules.Any(r => !r.Passes) ? GestureClarityVerdict.MissingFeedback : GestureClarityVerdict.Ready; } public IReadOnlyList<GesturePath> Paths { get; } public IReadOnlyList<RailCoherenceRule> RailRules { get; } public GestureClarityVerdict Verdict { get; } }

    public sealed class LightingTreatment { public LightingTreatment(string treatmentId, bool supportsReadability) { TreatmentId = treatmentId ?? string.Empty; SupportsReadability = supportsReadability; } public string TreatmentId { get; } public bool SupportsReadability { get; } }
    public sealed class MotionTreatment { public MotionTreatment(string motionId, bool optional, bool gameplayAnimation) { MotionId = motionId ?? string.Empty; Optional = optional; GameplayAnimation = gameplayAnimation; } public string MotionId { get; } public bool Optional { get; } public bool GameplayAnimation { get; } }
    public sealed class PerformanceGuard { public PerformanceGuard(string budgetId, bool lightWeight, bool canDisableMotion) { BudgetId = budgetId ?? string.Empty; LightWeight = lightWeight; CanDisableMotion = canDisableMotion; } public string BudgetId { get; } public bool LightWeight { get; } public bool CanDisableMotion { get; } }
    public sealed class HiveAtmosphereMotionLighting { public HiveAtmosphereMotionLighting(LightingTreatment waxLight, MotionTreatment ambientMotion, PerformanceGuard motionBudget) { WaxLight = waxLight; AmbientMotion = ambientMotion; MotionBudget = motionBudget; Verdict = waxLight == null || !waxLight.SupportsReadability ? AtmosphereVerdict.ReadabilityRisk : ambientMotion == null || ambientMotion.GameplayAnimation ? AtmosphereVerdict.ReadabilityRisk : motionBudget == null || !motionBudget.LightWeight || !motionBudget.CanDisableMotion ? AtmosphereVerdict.TooHeavy : AtmosphereVerdict.Ready; } public LightingTreatment WaxLight { get; } public MotionTreatment AmbientMotion { get; } public PerformanceGuard MotionBudget { get; } public AtmosphereVerdict Verdict { get; } }

    public sealed class ZoneIconRecognitionRule { public ZoneIconRecognitionRule(string zoneId, bool distinguishable) { ZoneId = zoneId ?? string.Empty; Distinguishable = distinguishable; } public string ZoneId { get; } public bool Distinguishable { get; } }
    public sealed class ZoneIconVariant { public ZoneIconVariant(string zoneId, string variantId, bool readableCompact) { ZoneId = zoneId ?? string.Empty; VariantId = variantId ?? string.Empty; ReadableCompact = readableCompact; } public string ZoneId { get; } public string VariantId { get; } public bool ReadableCompact { get; } }
    public sealed class ZoneIconRecognitionSet { private static readonly string[] Zones = { "Nursery", "Storage", "Defense", "Research", "Future" }; private static readonly string[] RequiredVariants = { "Normal", "Selected", "Locked", "Inactive", "Compact" }; public ZoneIconRecognitionSet(IReadOnlyList<ZoneIconRecognitionRule> recognitionRules, IReadOnlyList<ZoneIconVariant> variants) { RecognitionRules = recognitionRules ?? Array.Empty<ZoneIconRecognitionRule>(); Variants = variants ?? Array.Empty<ZoneIconVariant>(); Verdict = Zones.Any(z => RecognitionRules.All(r => !Text600.Same(r.ZoneId, z) || !r.Distinguishable)) ? ZoneIconRecognitionVerdict.MissingZone : Zones.Any(z => RequiredVariants.Any(rv => Variants.All(v => !Text600.Same(v.ZoneId, z) || !Text600.Same(v.VariantId, rv) || !v.ReadableCompact))) ? ZoneIconRecognitionVerdict.MissingVariant : Variants.Any(v => Variants.Count(x => Text600.Same(x.ZoneId, v.ZoneId) && Text600.Same(x.VariantId, v.VariantId)) > 1) ? ZoneIconRecognitionVerdict.Ambiguous : ZoneIconRecognitionVerdict.Ready; } public IReadOnlyList<ZoneIconRecognitionRule> RecognitionRules { get; } public IReadOnlyList<ZoneIconVariant> Variants { get; } public ZoneIconRecognitionVerdict Verdict { get; } }

    public sealed class DeviceAccessibilityCheck { public DeviceAccessibilityCheck(string checkId, bool passes) { CheckId = checkId ?? string.Empty; Passes = passes; } public string CheckId { get; } public bool Passes { get; } }
    public sealed class DeviceAccessibilityReserve { public DeviceAccessibilityReserve(string reserveId, bool acceptable) { ReserveId = reserveId ?? string.Empty; Acceptable = acceptable; } public string ReserveId { get; } public bool Acceptable { get; } }
    public sealed class DeviceAccessibilityAudit { private static readonly string[] Required = { "HudContrast", "SelectionContrast", "TargetSize", "TextFit", "NonColorOnlyStates", "ReducedScreenshotReadability" }; public DeviceAccessibilityAudit(IReadOnlyList<DeviceAccessibilityCheck> checks, IReadOnlyList<DeviceAccessibilityReserve> reserves) { Checks = checks ?? Array.Empty<DeviceAccessibilityCheck>(); Reserves = reserves ?? Array.Empty<DeviceAccessibilityReserve>(); Verdict = Required.Any(r => Checks.All(c => !Text600.Same(c.CheckId, r) || !c.Passes)) ? DeviceAccessibilityVerdict.Failed : Reserves.Count > 0 && Reserves.All(r => r.Acceptable) ? DeviceAccessibilityVerdict.ReadyWithDeviceReserve : DeviceAccessibilityVerdict.Ready; } public IReadOnlyList<DeviceAccessibilityCheck> Checks { get; } public IReadOnlyList<DeviceAccessibilityReserve> Reserves { get; } public DeviceAccessibilityVerdict Verdict { get; } }

    public sealed class VisualPathStep { public VisualPathStep(string stepId, int order) { StepId = stepId ?? string.Empty; Order = order; } public string StepId { get; } public int Order { get; } }
    public sealed class ComprehensionCheckpoint { public ComprehensionCheckpoint(string checkpointId, bool passes) { CheckpointId = checkpointId ?? string.Empty; Passes = passes; } public string CheckpointId { get; } public bool Passes { get; } }
    public sealed class FirstSessionHiveVisualPath { private static readonly string[] Required = { "RecognizeHive", "ReadHud", "SeeSelectedCell", "OpenDetail", "ReadPreviewLimit", "ReturnHome" }; public FirstSessionHiveVisualPath(IReadOnlyList<VisualPathStep> steps, IReadOnlyList<ComprehensionCheckpoint> checkpoints) { Steps = steps ?? Array.Empty<VisualPathStep>(); Checkpoints = checkpoints ?? Array.Empty<ComprehensionCheckpoint>(); Verdict = Required.Any(r => Steps.All(s => !Text600.Same(s.StepId, r))) ? FirstSessionVerdict.MissingStep : Checkpoints.Any(c => !c.Passes) || Checkpoints.Count == 0 ? FirstSessionVerdict.MissingCheckpoint : FirstSessionVerdict.Ready; } public IReadOnlyList<VisualPathStep> Steps { get; } public IReadOnlyList<ComprehensionCheckpoint> Checkpoints { get; } public FirstSessionVerdict Verdict { get; } }

    public sealed class DisclosureRow { public DisclosureRow(string rowId, string surface, bool visible) { RowId = rowId ?? string.Empty; Surface = surface ?? string.Empty; Visible = visible; } public string RowId { get; } public string Surface { get; } public bool Visible { get; } }
    public sealed class ForbiddenOfficialClaim { public ForbiddenOfficialClaim(string claimId, bool detected) { ClaimId = claimId ?? string.Empty; Detected = detected; } public string ClaimId { get; } public bool Detected { get; } }
    public sealed class FinalNonClaimDisclosureMatrix { private static readonly string[] Required = { "ResourceValue", "Capacity", "FutureRoom", "LockedState", "ServerRequired", "PreviewGesture", "DetailAction" }; public FinalNonClaimDisclosureMatrix(IReadOnlyList<DisclosureRow> rows, IReadOnlyList<ForbiddenOfficialClaim> forbiddenClaims) { Rows = rows ?? Array.Empty<DisclosureRow>(); ForbiddenClaims = forbiddenClaims ?? Array.Empty<ForbiddenOfficialClaim>(); Verdict = Required.Any(r => Rows.All(x => !Text600.Same(x.RowId, r) || !x.Visible)) ? NonClaimDisclosureVerdict.MissingRow : ForbiddenClaims.Any(c => c.Detected) ? NonClaimDisclosureVerdict.ForbiddenClaim : NonClaimDisclosureVerdict.Ready; } public IReadOnlyList<DisclosureRow> Rows { get; } public IReadOnlyList<ForbiddenOfficialClaim> ForbiddenClaims { get; } public NonClaimDisclosureVerdict Verdict { get; } }

    public sealed class CapturePipelineStep { public CapturePipelineStep(string stepId, int order, bool preservesOfficialScene) { StepId = stepId ?? string.Empty; Order = order; PreservesOfficialScene = preservesOfficialScene; } public string StepId { get; } public int Order { get; } public bool PreservesOfficialScene { get; } }
    public sealed class CaptureManifest { public CaptureManifest(string sceneName, bool includesLimits, bool includesReserves) { SceneName = sceneName ?? string.Empty; IncludesLimits = includesLimits; IncludesReserves = includesReserves; } public string SceneName { get; } public bool IncludesLimits { get; } public bool IncludesReserves { get; } public bool IsReady => Text600.Same(SceneName, "SandboxPlayground") && IncludesLimits && IncludesReserves; }
    public sealed class Bee600DemoCapturePipeline { private static readonly string[] Required = { "PrepareScene", "CaptureDesktop", "CapturePortrait", "CaptureDetail", "CaptureReducedView", "WriteManifest", "FileReserves" }; public Bee600DemoCapturePipeline(IReadOnlyList<CapturePipelineStep> steps, CaptureManifest manifest) { Steps = steps ?? Array.Empty<CapturePipelineStep>(); Manifest = manifest; Verdict = Required.Any(r => Steps.All(s => !Text600.Same(s.StepId, r) || !s.PreservesOfficialScene)) ? DemoEvidenceVerdict.MissingStep : manifest == null || !manifest.IsReady ? DemoEvidenceVerdict.MissingManifest : DemoEvidenceVerdict.ReadyForDemo; } public IReadOnlyList<CapturePipelineStep> Steps { get; } public CaptureManifest Manifest { get; } public DemoEvidenceVerdict Verdict { get; } }

    public sealed class UiScoreAxis { public UiScoreAxis(string axisId, int score, bool critical) { AxisId = axisId ?? string.Empty; Score = score; Critical = critical; } public string AxisId { get; } public int Score { get; } public bool Critical { get; } public bool Passes => Score >= 3 && Score <= 5; }
    public sealed class UiPriorityReserve { public UiPriorityReserve(string reserveId, int priority) { ReserveId = reserveId ?? string.Empty; Priority = priority; } public string ReserveId { get; } public int Priority { get; } }
    public sealed class Bee600UiScorecard { private static readonly string[] Required = { "HiveIdentity", "AssetFinish", "HudReadability", "PortraitFit", "DetailPanel", "GestureClarity", "StateLanguage", "Accessibility", "NonClaimClarity" }; public Bee600UiScorecard(IReadOnlyList<UiScoreAxis> axes, IReadOnlyList<UiPriorityReserve> priorityReserves) { Axes = axes ?? Array.Empty<UiScoreAxis>(); PriorityReserves = priorityReserves ?? Array.Empty<UiPriorityReserve>(); Verdict = Required.Any(r => Axes.All(a => !Text600.Same(a.AxisId, r))) || PriorityReserves.Count < 3 ? UiScorecardVerdict.NeedsReview : Axes.Any(a => a.Critical && !a.Passes) ? UiScorecardVerdict.Blocked : UiScorecardVerdict.Ready; } public IReadOnlyList<UiScoreAxis> Axes { get; } public IReadOnlyList<UiPriorityReserve> PriorityReserves { get; } public UiScorecardVerdict Verdict { get; } }

    public sealed class QaPlayerPrompt { public QaPlayerPrompt(string promptId, bool runnable) { PromptId = promptId ?? string.Empty; Runnable = runnable; } public string PromptId { get; } public bool Runnable { get; } }
    public sealed class QaExpectedAnswer { public QaExpectedAnswer(string promptId, string answer) { PromptId = promptId ?? string.Empty; Answer = answer ?? string.Empty; } public string PromptId { get; } public string Answer { get; } }
    public sealed class QaBlockingFailure { public QaBlockingFailure(string failureId, bool active) { FailureId = failureId ?? string.Empty; Active = active; } public string FailureId { get; } public bool Active { get; } }
    public sealed class Bee600QaReadabilityProtocol { private static readonly string[] Required = { "RecognizeHive", "ReadHud", "IdentifyTwoZones", "FindSelection", "CloseDetail", "ExplainPreview", "ConfirmMobilePortrait" }; public Bee600QaReadabilityProtocol(IReadOnlyList<QaPlayerPrompt> prompts, IReadOnlyList<QaExpectedAnswer> expectedAnswers, IReadOnlyList<QaBlockingFailure> blockingFailures) { Prompts = prompts ?? Array.Empty<QaPlayerPrompt>(); ExpectedAnswers = expectedAnswers ?? Array.Empty<QaExpectedAnswer>(); BlockingFailures = blockingFailures ?? Array.Empty<QaBlockingFailure>(); IsReady = Required.All(r => Prompts.Any(p => Text600.Same(p.PromptId, r) && p.Runnable) && ExpectedAnswers.Any(a => Text600.Same(a.PromptId, r))) && BlockingFailures.All(f => !f.Active); } public IReadOnlyList<QaPlayerPrompt> Prompts { get; } public IReadOnlyList<QaExpectedAnswer> ExpectedAnswers { get; } public IReadOnlyList<QaBlockingFailure> BlockingFailures { get; } public bool IsReady { get; } }

    public sealed class AuthorityClaimCheck { public AuthorityClaimCheck(string checkId, bool reviewed) { CheckId = checkId ?? string.Empty; Reviewed = reviewed; } public string CheckId { get; } public bool Reviewed { get; } }
    public sealed class ForbiddenAuthoritySignal { public ForbiddenAuthoritySignal(string signalId, bool detected) { SignalId = signalId ?? string.Empty; Detected = detected; } public string SignalId { get; } public bool Detected { get; } }
    public sealed class Bee600ServerAuthorityClaimAudit { private static readonly string[] Required = { "ResourceBalance", "ConstructionAction", "FutureRoomUnlock", "ProgressionLayer", "SavedSelection", "SyncStatus", "RewardClaim" }; public Bee600ServerAuthorityClaimAudit(IReadOnlyList<AuthorityClaimCheck> checks, IReadOnlyList<ForbiddenAuthoritySignal> forbiddenSignals) { Checks = checks ?? Array.Empty<AuthorityClaimCheck>(); ForbiddenSignals = forbiddenSignals ?? Array.Empty<ForbiddenAuthoritySignal>(); Verdict = Required.Any(r => Checks.All(c => !Text600.Same(c.CheckId, r) || !c.Reviewed)) ? ServerClaimAuditVerdict.MissingCheck : ForbiddenSignals.Any(s => s.Detected) ? ServerClaimAuditVerdict.ForbiddenSignal : ServerClaimAuditVerdict.SafeForVisualEvidence; } public IReadOnlyList<AuthorityClaimCheck> Checks { get; } public IReadOnlyList<ForbiddenAuthoritySignal> ForbiddenSignals { get; } public ServerClaimAuditVerdict Verdict { get; } }

    public sealed class BuilderEvidenceArtifact { public BuilderEvidenceArtifact(string artifactId, bool available) { ArtifactId = artifactId ?? string.Empty; Available = available; } public string ArtifactId { get; } public bool Available { get; } }
    public sealed class BuilderReserve { public BuilderReserve(string reserveId, bool blocksDemo) { ReserveId = reserveId ?? string.Empty; BlocksDemo = blocksDemo; } public string ReserveId { get; } public bool BlocksDemo { get; } }
    public sealed class BuilderBee600VisualEvidenceBundle { private static readonly string[] Required = { "CodeTouchpoints", "AssetManifest", "FocusedTests", "CompileLog", "SceneValidation", "CaptureReadinessNote", "KnownReserves" }; public BuilderBee600VisualEvidenceBundle(IReadOnlyList<BuilderEvidenceArtifact> artifacts, IReadOnlyList<BuilderReserve> reserves) { Artifacts = artifacts ?? Array.Empty<BuilderEvidenceArtifact>(); Reserves = reserves ?? Array.Empty<BuilderReserve>(); Verdict = Required.Any(r => Artifacts.All(a => !Text600.Same(a.ArtifactId, r) || !a.Available)) ? BuilderEvidenceVerdict.MissingArtifact : Reserves.Any(r => r.BlocksDemo) ? BuilderEvidenceVerdict.ReserveOnly : BuilderEvidenceVerdict.ReadyForDemo; } public IReadOnlyList<BuilderEvidenceArtifact> Artifacts { get; } public IReadOnlyList<BuilderReserve> Reserves { get; } public BuilderEvidenceVerdict Verdict { get; } }

    public sealed class VisualRegressionBlocker { public VisualRegressionBlocker(string blockerId, bool active) { BlockerId = blockerId ?? string.Empty; Active = active; } public string BlockerId { get; } public bool Active { get; } }
    public sealed class VisualRegressionReserve { public VisualRegressionReserve(string reserveId, bool acceptable) { ReserveId = reserveId ?? string.Empty; Acceptable = acceptable; } public string ReserveId { get; } public bool Acceptable { get; } }
    public sealed class HiveProductVisualRegressionLock { private static readonly string[] Required = { "BlankScene", "DebugOnlySurface", "MissingHud", "MissingHiveCells", "MissingDetailPanel", "BrokenPortrait", "OfficialClaimVisible" }; public HiveProductVisualRegressionLock(IReadOnlyList<VisualRegressionBlocker> blockers, IReadOnlyList<VisualRegressionReserve> reserves) { Blockers = blockers ?? Array.Empty<VisualRegressionBlocker>(); Reserves = reserves ?? Array.Empty<VisualRegressionReserve>(); Verdict = Blockers.Any(b => b.Active) || Required.Any(r => Blockers.All(b => !Text600.Same(b.BlockerId, r))) ? RegressionLockVerdict.Blocked : Reserves.Count > 0 && Reserves.All(r => r.Acceptable) ? RegressionLockVerdict.ClearWithReserves : RegressionLockVerdict.Clear; } public IReadOnlyList<VisualRegressionBlocker> Blockers { get; } public IReadOnlyList<VisualRegressionReserve> Reserves { get; } public RegressionLockVerdict Verdict { get; } }

    public sealed class CrossTeamReviewRow { public CrossTeamReviewRow(string rowId, bool available, string owner) { RowId = rowId ?? string.Empty; Available = available; Owner = owner ?? string.Empty; } public string RowId { get; } public bool Available { get; } public string Owner { get; } }
    public sealed class CrossTeamReserve { public CrossTeamReserve(string reserveId, bool blocking) { ReserveId = reserveId ?? string.Empty; Blocking = blocking; } public string ReserveId { get; } public bool Blocking { get; } }
    public sealed class Bee600CrossTeamVisualReviewLedger { private static readonly string[] Required = { "BuilderBundle", "DemoShots", "UiScorecard", "QaReadability", "ServerClaims", "AccessibilityAudit", "RegressionLocks" }; public Bee600CrossTeamVisualReviewLedger(IReadOnlyList<CrossTeamReviewRow> rows, IReadOnlyList<CrossTeamReserve> reserves) { Rows = rows ?? Array.Empty<CrossTeamReviewRow>(); Reserves = reserves ?? Array.Empty<CrossTeamReserve>(); Verdict = Required.Any(r => Rows.All(x => !Text600.Same(x.RowId, r) || !x.Available)) ? CrossTeamVisualVerdict.WaitingForTeams : Reserves.Any(r => r.Blocking) ? CrossTeamVisualVerdict.Blocked : CrossTeamVisualVerdict.ReadyForGate; } public IReadOnlyList<CrossTeamReviewRow> Rows { get; } public IReadOnlyList<CrossTeamReserve> Reserves { get; } public CrossTeamVisualVerdict Verdict { get; } }

    public sealed class MilestoneDecisionInput { public MilestoneDecisionInput(string inputId, bool present) { InputId = inputId ?? string.Empty; Present = present; } public string InputId { get; } public bool Present { get; } }
    public sealed class MilestoneStopCondition { public MilestoneStopCondition(string conditionId, bool active) { ConditionId = conditionId ?? string.Empty; Active = active; } public string ConditionId { get; } public bool Active { get; } }
    public sealed class MilestoneCarryForwardReserve { public MilestoneCarryForwardReserve(string reserveId, bool acceptable) { ReserveId = reserveId ?? string.Empty; Acceptable = acceptable; } public string ReserveId { get; } public bool Acceptable { get; } }
    public sealed class Bee600VisualMilestoneDecisionBoard { private static readonly string[] Required = { "CapturePack", "MobilePortraitProof", "HudRead", "DetailProof", "GestureProof", "AssetManifest", "AccessibilityResult", "UiScore", "QaVerdict", "ServerClaimAudit", "BuilderBundle", "RegressionLock", "CrossTeamLedger" }; public Bee600VisualMilestoneDecisionBoard(IReadOnlyList<MilestoneDecisionInput> inputs, IReadOnlyList<MilestoneStopCondition> stopConditions, IReadOnlyList<MilestoneCarryForwardReserve> carryForwardReserves, Bee601BlockerStatus bee601Status) { Inputs = inputs ?? Array.Empty<MilestoneDecisionInput>(); StopConditions = stopConditions ?? Array.Empty<MilestoneStopCondition>(); CarryForwardReserves = carryForwardReserves ?? Array.Empty<MilestoneCarryForwardReserve>(); Bee601Status = bee601Status; Decision = StopConditions.Any(s => s.Active) || Required.Any(r => Inputs.All(i => !Text600.Same(i.InputId, r) || !i.Present)) ? VisualMilestoneDecision.Blocked : CarryForwardReserves.Count > 0 && CarryForwardReserves.All(r => r.Acceptable) ? VisualMilestoneDecision.PassWithReserves : VisualMilestoneDecision.AwaitingArchitectReview; } public IReadOnlyList<MilestoneDecisionInput> Inputs { get; } public IReadOnlyList<MilestoneStopCondition> StopConditions { get; } public IReadOnlyList<MilestoneCarryForwardReserve> CarryForwardReserves { get; } public VisualMilestoneDecision Decision { get; } public Bee601BlockerStatus Bee601Status { get; } }

    public static class HiveProductUiArtPass2Events { public const string HiveArtPass2Opened = "HiveArtPass2Opened"; public const string Bee600EvidenceTargetRegistered = "Bee600EvidenceTargetRegistered"; public const string Bee600MilestoneDecisionSealed = "Bee600MilestoneDecisionSealed"; public const string Bee601BlockerConfirmed = "Bee601BlockerConfirmed"; }
    internal static class Text600 { public static bool Same(string left, string right) => string.Equals(left, right, StringComparison.OrdinalIgnoreCase); }
}
