using System;
using System.Collections.Generic;
using System.Linq;

namespace BeeKingdom.Colony
{
    public enum VisibleHomeUiState { VisibleOnLaunch, MissingRequiredElement, DiagnosticOnlyLaunchRejected, BlankOrBlueRejected }
    public enum PlayerNavigationVisibilityVerdict { Visible, MissingRequiredEntry, MissingIconOrLabel, LockedWithoutExplanation }
    public enum VisibleUiRecoveryVerdict { ReadyForBee541Review, ReadyWithReserves, BlockedByMissingSurface, BlockedByServerClaim, BlockedByDemoOrQaProof, BlockedByBee541Premature }
    public enum Bee541BlockerStatus { BlockedUntilVisibleUiProof, ReadyForArchitectReview, ReleasedByFutureArchitectDecision }

    public sealed class VisibleHomeUiElement { public VisibleHomeUiElement(string elementId, string playerFacingPurpose, string minimumVisibleText, bool mustBeVisibleOnLaunch) { ElementId = elementId ?? string.Empty; PlayerFacingPurpose = playerFacingPurpose ?? string.Empty; MinimumVisibleText = minimumVisibleText ?? string.Empty; MustBeVisibleOnLaunch = mustBeVisibleOnLaunch; } public string ElementId { get; } public string PlayerFacingPurpose { get; } public string MinimumVisibleText { get; } public bool MustBeVisibleOnLaunch { get; } }
    public sealed class VisiblePlayerHomeUiBootstrap
    {
        private static readonly string[] Required = { "BeeKingdomTitle", "HiveNamePreview", "MainResource", "HiveEntry", "WorldEntry", "PreviewStatusMessage", "BackCloseAffordance" };
        public VisiblePlayerHomeUiBootstrap(string sceneName, string bootstrapObjectName, IReadOnlyList<VisibleHomeUiElement> requiredElements) { SceneName = sceneName ?? string.Empty; BootstrapObjectName = bootstrapObjectName ?? string.Empty; RequiredElements = requiredElements ?? Array.Empty<VisibleHomeUiElement>(); VisibleState = Evaluate(); }
        public string SceneName { get; } public string BootstrapObjectName { get; } public VisibleHomeUiState VisibleState { get; } public IReadOnlyList<VisibleHomeUiElement> RequiredElements { get; }
        private VisibleHomeUiState Evaluate() { if (VisibleUiText.Contains(SceneName, "diagnostic") || VisibleUiText.Contains(BootstrapObjectName, "diagnostic")) return VisibleHomeUiState.DiagnosticOnlyLaunchRejected; if (string.IsNullOrWhiteSpace(SceneName) || string.IsNullOrWhiteSpace(BootstrapObjectName)) return VisibleHomeUiState.BlankOrBlueRejected; if (Required.Any(r => RequiredElements.All(e => !VisibleUiText.Same(e.ElementId, r) || !e.MustBeVisibleOnLaunch || string.IsNullOrWhiteSpace(e.MinimumVisibleText)))) return VisibleHomeUiState.MissingRequiredElement; return VisibleHomeUiState.VisibleOnLaunch; }
    }

    public sealed class HomeHudHeader { public HomeHudHeader(string title, string hiveName, string statusText) { Title = title ?? string.Empty; HiveName = hiveName ?? string.Empty; StatusText = statusText ?? string.Empty; } public string Title { get; } public string HiveName { get; } public string StatusText { get; } }
    public sealed class HomeHudResourceChip { public HomeHudResourceChip(string resourceId, string label, string displayValue, string iconId) { ResourceId = resourceId ?? string.Empty; Label = label ?? string.Empty; DisplayValue = displayValue ?? string.Empty; IconId = iconId ?? string.Empty; } public string ResourceId { get; } public string Label { get; } public string DisplayValue { get; } public string IconId { get; } }
    public sealed class HomeHudNavEntry { public HomeHudNavEntry(string entryId, string label, string iconId, string lockedExplanation) { EntryId = entryId ?? string.Empty; Label = label ?? string.Empty; IconId = iconId ?? string.Empty; LockedExplanation = lockedExplanation ?? string.Empty; } public string EntryId { get; } public string Label { get; } public string IconId { get; } public string LockedExplanation { get; } }
    public sealed class HomeHudPreviewStatus { public HomeHudPreviewStatus(string statusText, bool nonAuthoritative) { StatusText = statusText ?? string.Empty; NonAuthoritative = nonAuthoritative; } public string StatusText { get; } public bool NonAuthoritative { get; } }
    public sealed class MobileHomeHudShell
    {
        public MobileHomeHudShell(HomeHudHeader header, IReadOnlyList<HomeHudResourceChip> resourceChips, IReadOnlyList<HomeHudNavEntry> navigationEntries, HomeHudPreviewStatus previewStatus) { Header = header; ResourceChips = resourceChips ?? Array.Empty<HomeHudResourceChip>(); NavigationEntries = navigationEntries ?? Array.Empty<HomeHudNavEntry>(); PreviewStatus = previewStatus; IsMobileHomeReady = header != null && !string.IsNullOrWhiteSpace(header.Title) && !string.IsNullOrWhiteSpace(header.HiveName) && ResourceChips.Count >= 3 && NavigationEntries.Count >= 4 && previewStatus != null && previewStatus.NonAuthoritative; }
        public HomeHudHeader Header { get; } public IReadOnlyList<HomeHudResourceChip> ResourceChips { get; } public IReadOnlyList<HomeHudNavEntry> NavigationEntries { get; } public HomeHudPreviewStatus PreviewStatus { get; } public bool IsMobileHomeReady { get; }
    }

    public sealed class HiveSafeFramePortrait { public HiveSafeFramePortrait(float xMin, float yMin, float xMax, float yMax) { XMin = xMin; YMin = yMin; XMax = xMax; YMax = yMax; } public float XMin { get; } public float YMin { get; } public float XMax { get; } public float YMax { get; } public bool IsValid => XMax > XMin && YMax > YMin && XMin >= 0f && YMin >= 0f && XMax <= 1f && YMax <= 1f; }
    public sealed class HiveVisualAnchor { public HiveVisualAnchor(string anchorId, string playerMeaning, bool protectedFromText) { AnchorId = anchorId ?? string.Empty; PlayerMeaning = playerMeaning ?? string.Empty; ProtectedFromText = protectedFromText; } public string AnchorId { get; } public string PlayerMeaning { get; } public bool ProtectedFromText { get; } }
    public sealed class HiveViewBackgroundSafeFraming { public HiveViewBackgroundSafeFraming(string backgroundAssetId, HiveSafeFramePortrait safeFrame, IReadOnlyList<HiveVisualAnchor> visualAnchors) { BackgroundAssetId = backgroundAssetId ?? string.Empty; SafeFrame = safeFrame; VisualAnchors = visualAnchors ?? Array.Empty<HiveVisualAnchor>(); IsSafeForPortrait = !string.IsNullOrWhiteSpace(BackgroundAssetId) && safeFrame != null && safeFrame.IsValid && RequiredAnchors.All(r => VisualAnchors.Any(a => VisibleUiText.Same(a.AnchorId, r))); } private static readonly string[] RequiredAnchors = { "HiveCore", "ResourceZone", "ActionZone", "LowerNavLimit", "NoTextZone" }; public string BackgroundAssetId { get; } public HiveSafeFramePortrait SafeFrame { get; } public IReadOnlyList<HiveVisualAnchor> VisualAnchors { get; } public bool IsSafeForPortrait { get; } }

    public sealed class PlayerNavEntryPoint { public PlayerNavEntryPoint(string entryId, string label, string visibleIconId, string lockedExplanation) { EntryId = entryId ?? string.Empty; Label = label ?? string.Empty; VisibleIconId = visibleIconId ?? string.Empty; LockedExplanation = lockedExplanation ?? string.Empty; } public string EntryId { get; } public string Label { get; } public string VisibleIconId { get; } public string LockedExplanation { get; } }
    public sealed class PrimaryNavigationEntryPoints { public PrimaryNavigationEntryPoints(IReadOnlyList<PlayerNavEntryPoint> entries) { Entries = entries ?? Array.Empty<PlayerNavEntryPoint>(); Verdict = Evaluate(); } private static readonly string[] Required = { "Hive", "World", "Alliance", "Messages", "Army", "Research" }; public IReadOnlyList<PlayerNavEntryPoint> Entries { get; } public PlayerNavigationVisibilityVerdict Verdict { get; } private PlayerNavigationVisibilityVerdict Evaluate() { if (Required.Any(r => Entries.All(e => !VisibleUiText.Same(e.EntryId, r)))) return PlayerNavigationVisibilityVerdict.MissingRequiredEntry; if (Entries.Any(e => string.IsNullOrWhiteSpace(e.Label) || string.IsNullOrWhiteSpace(e.VisibleIconId))) return PlayerNavigationVisibilityVerdict.MissingIconOrLabel; if (Entries.Any(e => VisibleUiText.Contains(e.Label, "locked") && string.IsNullOrWhiteSpace(e.LockedExplanation))) return PlayerNavigationVisibilityVerdict.LockedWithoutExplanation; return PlayerNavigationVisibilityVerdict.Visible; } }

    public sealed class ActionPreviewRequirement { public ActionPreviewRequirement(string requirementId, string displayText, bool satisfied) { RequirementId = requirementId ?? string.Empty; DisplayText = displayText ?? string.Empty; Satisfied = satisfied; } public string RequirementId { get; } public string DisplayText { get; } public bool Satisfied { get; } }
    public sealed class HiveActionPreviewPanel { public HiveActionPreviewPanel(string actionTitle, string previewBenefit, IReadOnlyList<ActionPreviewRequirement> requirements, string lockedActionExplanation) { ActionTitle = actionTitle ?? string.Empty; PreviewBenefit = previewBenefit ?? string.Empty; Requirements = requirements ?? Array.Empty<ActionPreviewRequirement>(); LockedActionExplanation = lockedActionExplanation ?? string.Empty; IsReadablePreview = !string.IsNullOrWhiteSpace(ActionTitle) && !string.IsNullOrWhiteSpace(PreviewBenefit) && Requirements.Count > 0 && !string.IsNullOrWhiteSpace(LockedActionExplanation); } public string ActionTitle { get; } public string PreviewBenefit { get; } public IReadOnlyList<ActionPreviewRequirement> Requirements { get; } public string LockedActionExplanation { get; } public bool IsReadablePreview { get; } }
    public sealed class VisibleResourceValue { public VisibleResourceValue(string resourceId, string displayValue, string sourceLabel) { ResourceId = resourceId ?? string.Empty; DisplayValue = displayValue ?? string.Empty; SourceLabel = sourceLabel ?? string.Empty; } public string ResourceId { get; } public string DisplayValue { get; } public string SourceLabel { get; } }
    public sealed class VisibleProgressionValue { public VisibleProgressionValue(string label, string displayValue, string previewMeaning) { Label = label ?? string.Empty; DisplayValue = displayValue ?? string.Empty; PreviewMeaning = previewMeaning ?? string.Empty; } public string Label { get; } public string DisplayValue { get; } public string PreviewMeaning { get; } }
    public sealed class ResourceAndProgressionReadout { public ResourceAndProgressionReadout(IReadOnlyList<VisibleResourceValue> resources, VisibleProgressionValue progression, string nonAuthoritativeDisclosure) { Resources = resources ?? Array.Empty<VisibleResourceValue>(); Progression = progression; NonAuthoritativeDisclosure = nonAuthoritativeDisclosure ?? string.Empty; IsComplete = Resources.Count >= 4 && progression != null && VisibleUiText.Contains(nonAuthoritativeDisclosure, "preview"); } public IReadOnlyList<VisibleResourceValue> Resources { get; } public VisibleProgressionValue Progression { get; } public string NonAuthoritativeDisclosure { get; } public bool IsComplete { get; } }

    public sealed class ArmyPreviewSignal { public ArmyPreviewSignal(string signalId, string displayText, bool combatLocked) { SignalId = signalId ?? string.Empty; DisplayText = displayText ?? string.Empty; CombatLocked = combatLocked; } public string SignalId { get; } public string DisplayText { get; } public bool CombatLocked { get; } }
    public sealed class ArmyDefenseAccessPreview { public ArmyDefenseAccessPreview(string entryLabel, string defenseStatusText, string lockedCombatExplanation, IReadOnlyList<ArmyPreviewSignal> signals) { EntryLabel = entryLabel ?? string.Empty; DefenseStatusText = defenseStatusText ?? string.Empty; LockedCombatExplanation = lockedCombatExplanation ?? string.Empty; Signals = signals ?? Array.Empty<ArmyPreviewSignal>(); IsPreviewOnly = Signals.Count >= 4 && Signals.Any(s => s.CombatLocked) && !string.IsNullOrWhiteSpace(LockedCombatExplanation); } public string EntryLabel { get; } public string DefenseStatusText { get; } public string LockedCombatExplanation { get; } public IReadOnlyList<ArmyPreviewSignal> Signals { get; } public bool IsPreviewOnly { get; } }
    public sealed class SocialNotebookRow { public SocialNotebookRow(string rowId, string playerMeaning, string previewOnlyReason) { RowId = rowId ?? string.Empty; PlayerMeaning = playerMeaning ?? string.Empty; PreviewOnlyReason = previewOnlyReason ?? string.Empty; } public string RowId { get; } public string PlayerMeaning { get; } public string PreviewOnlyReason { get; } }
    public sealed class AllianceSocialPreviewNotebook { public AllianceSocialPreviewNotebook(string notebookTitle, string trustStatusText, IReadOnlyList<SocialNotebookRow> rows, string communityEtiquetteNote) { NotebookTitle = notebookTitle ?? string.Empty; TrustStatusText = trustStatusText ?? string.Empty; Rows = rows ?? Array.Empty<SocialNotebookRow>(); CommunityEtiquetteNote = communityEtiquetteNote ?? string.Empty; IsPreviewOnly = Rows.Count >= 5 && Rows.All(r => !string.IsNullOrWhiteSpace(r.PreviewOnlyReason)) && !string.IsNullOrWhiteSpace(CommunityEtiquetteNote); } public string NotebookTitle { get; } public string TrustStatusText { get; } public IReadOnlyList<SocialNotebookRow> Rows { get; } public string CommunityEtiquetteNote { get; } public bool IsPreviewOnly { get; } }

    public sealed class LockedStateMessage { public LockedStateMessage(string messageId, string playerText, string reason) { MessageId = messageId ?? string.Empty; PlayerText = playerText ?? string.Empty; Reason = reason ?? string.Empty; } public string MessageId { get; } public string PlayerText { get; } public string Reason { get; } }
    public sealed class ForbiddenFeedbackPhrase { public ForbiddenFeedbackPhrase(string phrase, string reason) { Phrase = phrase ?? string.Empty; Reason = reason ?? string.Empty; } public string Phrase { get; } public string Reason { get; } }
    public enum LockedStateLanguageVerdict { Ready, MissingRequiredMessage, ContainsForbiddenPhrase }
    public sealed class PlayerFeedbackLockedStateLanguage { public PlayerFeedbackLockedStateLanguage(IReadOnlyList<LockedStateMessage> messages, IReadOnlyList<ForbiddenFeedbackPhrase> forbiddenPhrases) { Messages = messages ?? Array.Empty<LockedStateMessage>(); ForbiddenPhrases = forbiddenPhrases ?? Array.Empty<ForbiddenFeedbackPhrase>(); Verdict = Evaluate(); } private static readonly string[] Required = { "ActionPreview", "ServerNotConnected", "SocialNotLive", "CombatLocked", "LocalResources", "DemoRecovery" }; public IReadOnlyList<LockedStateMessage> Messages { get; } public IReadOnlyList<ForbiddenFeedbackPhrase> ForbiddenPhrases { get; } public LockedStateLanguageVerdict Verdict { get; } private LockedStateLanguageVerdict Evaluate() { if (Required.Any(r => Messages.All(m => !VisibleUiText.Same(m.MessageId, r)))) return LockedStateLanguageVerdict.MissingRequiredMessage; if (ForbiddenPhrases.Any(f => Messages.Any(m => VisibleUiText.Contains(m.PlayerText, f.Phrase)))) return LockedStateLanguageVerdict.ContainsForbiddenPhrase; return LockedStateLanguageVerdict.Ready; } }

    public sealed class MobilePortraitRule { public MobilePortraitRule(string ruleId, string requirement, bool satisfied) { RuleId = ruleId ?? string.Empty; Requirement = requirement ?? string.Empty; Satisfied = satisfied; } public string RuleId { get; } public string Requirement { get; } public bool Satisfied { get; } }
    public sealed class MobileLayoutFailure { public MobileLayoutFailure(string failureId, string description) { FailureId = failureId ?? string.Empty; Description = description ?? string.Empty; } public string FailureId { get; } public string Description { get; } }
    public enum MobilePortraitVerdict { Ready, MissingRule, HasLayoutFailure }
    public sealed class MobilePortraitInteractionConstraints { public MobilePortraitInteractionConstraints(IReadOnlyList<MobilePortraitRule> rules, IReadOnlyList<MobileLayoutFailure> failures) { Rules = rules ?? Array.Empty<MobilePortraitRule>(); Failures = failures ?? Array.Empty<MobileLayoutFailure>(); Verdict = Rules.Count >= 8 && Rules.All(r => r.Satisfied) ? failures != null && failures.Count > 0 ? MobilePortraitVerdict.HasLayoutFailure : MobilePortraitVerdict.Ready : MobilePortraitVerdict.MissingRule; } public IReadOnlyList<MobilePortraitRule> Rules { get; } public IReadOnlyList<MobileLayoutFailure> Failures { get; } public MobilePortraitVerdict Verdict { get; } }

    public sealed class UiAssetRequirement { public UiAssetRequirement(string assetId, string usage, bool acceptablePlaceholder) { AssetId = assetId ?? string.Empty; Usage = usage ?? string.Empty; AcceptablePlaceholder = acceptablePlaceholder; } public string AssetId { get; } public string Usage { get; } public bool AcceptablePlaceholder { get; } }
    public sealed class AllowedPlaceholderAsset { public AllowedPlaceholderAsset(string assetId, string visibleDisclosure) { AssetId = assetId ?? string.Empty; VisibleDisclosure = visibleDisclosure ?? string.Empty; } public string AssetId { get; } public string VisibleDisclosure { get; } }
    public enum UiAssetGuardrailVerdict { ReadyForPreview, MissingRequiredAsset, PlaceholderNotDisclosed }
    public sealed class UiAssetIntegrationGuardrail { public UiAssetIntegrationGuardrail(IReadOnlyList<UiAssetRequirement> requirements, IReadOnlyList<AllowedPlaceholderAsset> allowedPlaceholders) { Requirements = requirements ?? Array.Empty<UiAssetRequirement>(); AllowedPlaceholders = allowedPlaceholders ?? Array.Empty<AllowedPlaceholderAsset>(); Verdict = Evaluate(); } private static readonly string[] Required = { "HiveBackground", "ResourceIcon", "NavIcon", "LockIcon", "HomePanel", "BeeKingdomAccent" }; public IReadOnlyList<UiAssetRequirement> Requirements { get; } public IReadOnlyList<AllowedPlaceholderAsset> AllowedPlaceholders { get; } public UiAssetGuardrailVerdict Verdict { get; } private UiAssetGuardrailVerdict Evaluate() { if (Required.Any(r => Requirements.All(a => !VisibleUiText.Same(a.AssetId, r)))) return UiAssetGuardrailVerdict.MissingRequiredAsset; if (Requirements.Any(r => r.AcceptablePlaceholder && AllowedPlaceholders.All(p => !VisibleUiText.Same(p.AssetId, r.AssetId) || string.IsNullOrWhiteSpace(p.VisibleDisclosure)))) return UiAssetGuardrailVerdict.PlaceholderNotDisclosed; return UiAssetGuardrailVerdict.ReadyForPreview; } }

    public enum SceneBindingVerdict { Bound, MissingScene, MissingBootstrap, MissingVisibleRoot, DiagnosticOnlyRejected }
    public sealed class SceneBindingBootstrapGuard { public SceneBindingBootstrapGuard(string officialLaunchScene, string requiredBootstrapComponent, string visibleUiRootName) { OfficialLaunchScene = officialLaunchScene ?? string.Empty; RequiredBootstrapComponent = requiredBootstrapComponent ?? string.Empty; VisibleUiRootName = visibleUiRootName ?? string.Empty; Verdict = string.IsNullOrWhiteSpace(OfficialLaunchScene) ? SceneBindingVerdict.MissingScene : string.IsNullOrWhiteSpace(RequiredBootstrapComponent) ? SceneBindingVerdict.MissingBootstrap : VisibleUiText.Contains(VisibleUiRootName, "diagnostic") ? SceneBindingVerdict.DiagnosticOnlyRejected : string.IsNullOrWhiteSpace(VisibleUiRootName) ? SceneBindingVerdict.MissingVisibleRoot : SceneBindingVerdict.Bound; } public string OfficialLaunchScene { get; } public string RequiredBootstrapComponent { get; } public string VisibleUiRootName { get; } public SceneBindingVerdict Verdict { get; } }
    public enum DemoImmediateVerdict { ReadyForProofCapture, MissingRequiredScene, MissingVisualProof, ClaimsFinalProduction }
    public sealed class DemoImmediateVisualException { public DemoImmediateVisualException(string exceptionReason, string requiredScene, string requiredVisualProof) { ExceptionReason = exceptionReason ?? string.Empty; RequiredScene = requiredScene ?? string.Empty; RequiredVisualProof = requiredVisualProof ?? string.Empty; Verdict = string.IsNullOrWhiteSpace(requiredScene) ? DemoImmediateVerdict.MissingRequiredScene : string.IsNullOrWhiteSpace(requiredVisualProof) ? DemoImmediateVerdict.MissingVisualProof : VisibleUiText.Contains(requiredVisualProof, "production finale") ? DemoImmediateVerdict.ClaimsFinalProduction : DemoImmediateVerdict.ReadyForProofCapture; } public string ExceptionReason { get; } public string RequiredScene { get; } public string RequiredVisualProof { get; } public DemoImmediateVerdict Verdict { get; } }
    public sealed class QaLaunchCheck { public QaLaunchCheck(string checkId, string expectedResult, bool passed) { CheckId = checkId ?? string.Empty; ExpectedResult = expectedResult ?? string.Empty; Passed = passed; } public string CheckId { get; } public string ExpectedResult { get; } public bool Passed { get; } }
    public enum QaLaunchSmokeVerdict { Passed, MissingCheck, FailedCheck }
    public sealed class QaUnityLaunchSmokeTest { public QaUnityLaunchSmokeTest(string sceneUnderTest, IReadOnlyList<QaLaunchCheck> checks) { SceneUnderTest = sceneUnderTest ?? string.Empty; Checks = checks ?? Array.Empty<QaLaunchCheck>(); Verdict = Checks.Count >= 7 ? Checks.Any(c => !c.Passed) ? QaLaunchSmokeVerdict.FailedCheck : QaLaunchSmokeVerdict.Passed : QaLaunchSmokeVerdict.MissingCheck; } public string SceneUnderTest { get; } public IReadOnlyList<QaLaunchCheck> Checks { get; } public QaLaunchSmokeVerdict Verdict { get; } }

    public sealed class DisplayedDataAuthorityRow { public DisplayedDataAuthorityRow(string dataId, string displayedMeaning, bool claimsServerTruth) { DataId = dataId ?? string.Empty; DisplayedMeaning = displayedMeaning ?? string.Empty; ClaimsServerTruth = claimsServerTruth; } public string DataId { get; } public string DisplayedMeaning { get; } public bool ClaimsServerTruth { get; } }
    public sealed class ServerClaimViolation { public ServerClaimViolation(string violationId, string description) { ViolationId = violationId ?? string.Empty; Description = description ?? string.Empty; } public string ViolationId { get; } public string Description { get; } }
    public enum ServerNonClaimVerdict { SafeForPreview, MissingAuthorityRow, ServerClaimViolation }
    public sealed class ServerNonClaimGuard { public ServerNonClaimGuard(IReadOnlyList<DisplayedDataAuthorityRow> rows, IReadOnlyList<ServerClaimViolation> violations) { Rows = rows ?? Array.Empty<DisplayedDataAuthorityRow>(); Violations = violations ?? Array.Empty<ServerClaimViolation>(); Verdict = Rows.Count < 8 ? ServerNonClaimVerdict.MissingAuthorityRow : Rows.Any(r => r.ClaimsServerTruth) || Violations.Count > 0 ? ServerNonClaimVerdict.ServerClaimViolation : ServerNonClaimVerdict.SafeForPreview; } public IReadOnlyList<DisplayedDataAuthorityRow> Rows { get; } public IReadOnlyList<ServerClaimViolation> Violations { get; } public ServerNonClaimVerdict Verdict { get; } }
    public sealed class UiAcceptanceCheck { public UiAcceptanceCheck(string checkId, bool accepted) { CheckId = checkId ?? string.Empty; Accepted = accepted; } public string CheckId { get; } public bool Accepted { get; } }
    public sealed class UiAcceptanceReserve { public UiAcceptanceReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public enum UiAcceptanceVerdict { Accepted, AcceptedWithReserves, MissingAcceptance }
    public sealed class UiTeamAcceptanceChecklist { public UiTeamAcceptanceChecklist(IReadOnlyList<UiAcceptanceCheck> checks, IReadOnlyList<UiAcceptanceReserve> reserves) { Checks = checks ?? Array.Empty<UiAcceptanceCheck>(); Reserves = reserves ?? Array.Empty<UiAcceptanceReserve>(); Verdict = Checks.Count >= 8 && Checks.All(c => c.Accepted) ? Reserves.Count > 0 ? UiAcceptanceVerdict.AcceptedWithReserves : UiAcceptanceVerdict.Accepted : UiAcceptanceVerdict.MissingAcceptance; } public IReadOnlyList<UiAcceptanceCheck> Checks { get; } public IReadOnlyList<UiAcceptanceReserve> Reserves { get; } public UiAcceptanceVerdict Verdict { get; } }
    public sealed class BuilderRuntimeProofPackage { public BuilderRuntimeProofPackage(string sceneName, string bootstrapName, IReadOnlyList<string> uiObjects, IReadOnlyList<string> modifiedFiles, string playModeProofReference) { SceneName = sceneName ?? string.Empty; BootstrapName = bootstrapName ?? string.Empty; UiObjects = uiObjects ?? Array.Empty<string>(); ModifiedFiles = modifiedFiles ?? Array.Empty<string>(); PlayModeProofReference = playModeProofReference ?? string.Empty; IsComplete = !string.IsNullOrWhiteSpace(SceneName) && !string.IsNullOrWhiteSpace(BootstrapName) && UiObjects.Count >= 3 && ModifiedFiles.Count > 0 && !string.IsNullOrWhiteSpace(PlayModeProofReference); } public string SceneName { get; } public string BootstrapName { get; } public IReadOnlyList<string> UiObjects { get; } public IReadOnlyList<string> ModifiedFiles { get; } public string PlayModeProofReference { get; } public bool IsComplete { get; } }
    public sealed class SurfaceMisclassificationRisk { public SurfaceMisclassificationRisk(string riskId, string description) { RiskId = riskId ?? string.Empty; Description = description ?? string.Empty; } public string RiskId { get; } public string Description { get; } }
    public enum SurfaceSeparationVerdict { Separated, MissingClassification, DiagnosticOnlyLandingRisk }
    public sealed class ProductionDemoSurfaceSeparation { public ProductionDemoSurfaceSeparation(IReadOnlyList<SurfaceClassification> surfaces, IReadOnlyList<SurfaceMisclassificationRisk> risks) { Surfaces = surfaces ?? Array.Empty<SurfaceClassification>(); Risks = risks ?? Array.Empty<SurfaceMisclassificationRisk>(); Verdict = Surfaces.Any(s => s.SurfaceClass == SurfaceClass.DebugQa && s.Audience == SurfaceAudience.Player && VisibleUiText.Contains(s.SurfaceId, "Launch")) ? SurfaceSeparationVerdict.DiagnosticOnlyLandingRisk : Surfaces.Count < 4 ? SurfaceSeparationVerdict.MissingClassification : SurfaceSeparationVerdict.Separated; } public IReadOnlyList<SurfaceClassification> Surfaces { get; } public IReadOnlyList<SurfaceMisclassificationRisk> Risks { get; } public SurfaceSeparationVerdict Verdict { get; } }
    public sealed class VisibleRegressionCondition { public VisibleRegressionCondition(string conditionId, bool blocking) { ConditionId = conditionId ?? string.Empty; Blocking = blocking; } public string ConditionId { get; } public bool Blocking { get; } }
    public sealed class VisibleRegressionEvidence { public VisibleRegressionEvidence(string evidenceId, bool present) { EvidenceId = evidenceId ?? string.Empty; Present = present; } public string EvidenceId { get; } public bool Present { get; } }
    public enum VisibleRegressionVerdict { Protected, MissingEvidence, BlockingRegressionPresent }
    public sealed class VisibleProductRegressionRule { public VisibleProductRegressionRule(IReadOnlyList<VisibleRegressionCondition> blockingConditions, IReadOnlyList<VisibleRegressionEvidence> requiredEvidence) { BlockingConditions = blockingConditions ?? Array.Empty<VisibleRegressionCondition>(); RequiredEvidence = requiredEvidence ?? Array.Empty<VisibleRegressionEvidence>(); Verdict = BlockingConditions.Any(c => c.Blocking) ? VisibleRegressionVerdict.BlockingRegressionPresent : RequiredEvidence.Count < 7 || RequiredEvidence.Any(e => !e.Present) ? VisibleRegressionVerdict.MissingEvidence : VisibleRegressionVerdict.Protected; } public IReadOnlyList<VisibleRegressionCondition> BlockingConditions { get; } public IReadOnlyList<VisibleRegressionEvidence> RequiredEvidence { get; } public VisibleRegressionVerdict Verdict { get; } }
    public sealed class VisibleUiGateRow { public VisibleUiGateRow(string rowId, bool passed, string evidence) { RowId = rowId ?? string.Empty; Passed = passed; Evidence = evidence ?? string.Empty; } public string RowId { get; } public bool Passed { get; } public string Evidence { get; } }
    public sealed class VisibleUiRecoveryReserve { public VisibleUiRecoveryReserve(string reserveId, string description) { ReserveId = reserveId ?? string.Empty; Description = description ?? string.Empty; } public string ReserveId { get; } public string Description { get; } }
    public sealed class VisibleUiRecoveryGate { public VisibleUiRecoveryGate(IReadOnlyList<VisibleUiGateRow> rows, IReadOnlyList<VisibleUiRecoveryReserve> reserves, Bee541BlockerStatus bee541Status) { Rows = rows ?? Array.Empty<VisibleUiGateRow>(); Reserves = reserves ?? Array.Empty<VisibleUiRecoveryReserve>(); Bee541Status = bee541Status; Verdict = Evaluate(); } public IReadOnlyList<VisibleUiGateRow> Rows { get; } public IReadOnlyList<VisibleUiRecoveryReserve> Reserves { get; } public VisibleUiRecoveryVerdict Verdict { get; } public Bee541BlockerStatus Bee541Status { get; } private VisibleUiRecoveryVerdict Evaluate() { if (Bee541Status == Bee541BlockerStatus.ReleasedByFutureArchitectDecision) return VisibleUiRecoveryVerdict.BlockedByBee541Premature; if (Rows.Count < 20 || Rows.Any(r => !r.Passed)) return VisibleUiRecoveryVerdict.BlockedByMissingSurface; if (Rows.Any(r => VisibleUiText.Contains(r.Evidence, "server official"))) return VisibleUiRecoveryVerdict.BlockedByServerClaim; if (Rows.Any(r => (VisibleUiText.Same(r.RowId, "DemoProof") || VisibleUiText.Same(r.RowId, "QaSmoke")) && string.IsNullOrWhiteSpace(r.Evidence))) return VisibleUiRecoveryVerdict.BlockedByDemoOrQaProof; return Reserves.Count > 0 ? VisibleUiRecoveryVerdict.ReadyWithReserves : VisibleUiRecoveryVerdict.ReadyForBee541Review; } }

    public static class VisibleUiRecoveryEvents { public const string VisiblePlayerHomeBootstrapped = "VisiblePlayerHomeBootstrapped"; public const string PlayerHomeUiShownOnLaunch = "PlayerHomeUiShownOnLaunch"; public const string DiagnosticOnlyLaunchRejected = "DiagnosticOnlyLaunchRejected"; public const string VisibleUiRecoveryGateEvaluated = "VisibleUiRecoveryGateEvaluated"; public const string VisibleUiRecoveryReserveRecorded = "VisibleUiRecoveryReserveRecorded"; public const string Bee541BlockerConfirmed = "Bee541BlockerConfirmed"; }

    internal static class VisibleUiText { public static bool Contains(string source, string token) => !string.IsNullOrEmpty(source) && !string.IsNullOrEmpty(token) && source.IndexOf(token, StringComparison.OrdinalIgnoreCase) >= 0; public static bool Same(string left, string right) => string.Equals(left, right, StringComparison.OrdinalIgnoreCase); }
}
