using System;
using System.Collections.Generic;
using System.Linq;

namespace BeeKingdom.Save
{
    public enum PersistenceServerAnalysisStatus { ServerAnalysisRequired, AnalysisQueued, AnalysisReady, Blocked, OutOfScope }
    public enum PersistenceServerAnalysisDiagnostics { ServerAnalysisMissing, BeeSourceMissing, RuntimeImplementationRequested, SqlScopeRequested, EvidenceLinkMissing }
    public sealed class PersistenceServerAnalysisItem { public PersistenceServerAnalysisItem(string beeSource, string contractFamily, bool serverImpact, bool demoImpact, bool qaEvidenceNeed, string decision, string blockingReason, PersistenceServerAnalysisStatus status) { BeeSource = beeSource ?? string.Empty; ContractFamily = contractFamily ?? string.Empty; ServerImpact = serverImpact; DemoImpact = demoImpact; QaEvidenceNeed = qaEvidenceNeed; RequiredServerDecision = decision ?? string.Empty; BlockingReason = blockingReason ?? string.Empty; Status = status; } public string BeeSource { get; } public string ContractFamily { get; } public bool ServerImpact { get; } public bool DemoImpact { get; } public bool QaEvidenceNeed { get; } public string RequiredServerDecision { get; } public string BlockingReason { get; } public PersistenceServerAnalysisStatus Status { get; } }
    public sealed class PersistenceServerAnalysisIntake { public PersistenceServerAnalysisIntake(IEnumerable<PersistenceServerAnalysisItem> items, int serverProgressBee, bool sqlRequested, bool runtimeRequested) { Items = (items ?? Array.Empty<PersistenceServerAnalysisItem>()).OrderBy(i => i.BeeSource, StringComparer.Ordinal).ToList(); Diagnostics = Detect(Items, serverProgressBee, sqlRequested, runtimeRequested); } public IReadOnlyList<PersistenceServerAnalysisItem> Items { get; } public IReadOnlyList<PersistenceServerAnalysisDiagnostics> Diagnostics { get; } private static IReadOnlyList<PersistenceServerAnalysisDiagnostics> Detect(IReadOnlyList<PersistenceServerAnalysisItem> items, int progress, bool sql, bool runtime) { var d = new List<PersistenceServerAnalysisDiagnostics>(); if (items.Any(i => string.IsNullOrWhiteSpace(i.BeeSource))) d.Add(PersistenceServerAnalysisDiagnostics.BeeSourceMissing); if (progress <= 230 && items.Any(i => string.CompareOrdinal(i.BeeSource, "BEE-231") >= 0)) d.Add(PersistenceServerAnalysisDiagnostics.ServerAnalysisMissing); if (sql) d.Add(PersistenceServerAnalysisDiagnostics.SqlScopeRequested); if (runtime) d.Add(PersistenceServerAnalysisDiagnostics.RuntimeImplementationRequested); if (items.Any(i => i.QaEvidenceNeed && string.IsNullOrWhiteSpace(i.BlockingReason))) d.Add(PersistenceServerAnalysisDiagnostics.EvidenceLinkMissing); return d.Distinct().OrderBy(x => x).ToList(); } }

    public enum PersistenceReadinessBadge { Ready, ReadyWithWarnings, Blocked, NotImplemented, ServerAnalysisRequired, OutOfScope }
    public enum PersistenceVisualReadinessSection { RuntimeBoundary, FixtureCatalog, MigrationDryRun, SnapshotHarness, RedactionPreview, Observability, RegressionSuite, BackendAnalysis, GateSummary }
    public enum PersistencePanelWarning { PanelSourceMissing, BadgeConflict, RuntimeClaimDetected, VisualOrderUnstable, BlockerWithoutExplanation }
    public sealed class PersistencePanelBlocker { public PersistencePanelBlocker(string code, string explanation) { Code = code ?? string.Empty; Explanation = explanation ?? string.Empty; } public string Code { get; } public string Explanation { get; } }
    public sealed class PersistenceVisualReadinessPanel { public PersistenceVisualReadinessPanel(IEnumerable<PersistenceVisualReadinessSection> sections, PersistenceReadinessBadge badge, IEnumerable<PersistencePanelBlocker> blockers, bool runtimeClaim) { Sections = (sections ?? Array.Empty<PersistenceVisualReadinessSection>()).OrderBy(s => s).ToList(); Badge = badge; Blockers = (blockers ?? Array.Empty<PersistencePanelBlocker>()).OrderBy(b => b.Code, StringComparer.Ordinal).ToList(); Diagnostics = Detect(runtimeClaim); } public IReadOnlyList<PersistenceVisualReadinessSection> Sections { get; } public PersistenceReadinessBadge Badge { get; } public IReadOnlyList<PersistencePanelBlocker> Blockers { get; } public IReadOnlyList<PersistencePanelWarning> Diagnostics { get; } private IReadOnlyList<PersistencePanelWarning> Detect(bool runtimeClaim) { var d = new List<PersistencePanelWarning>(); foreach (PersistenceVisualReadinessSection section in Enum.GetValues(typeof(PersistenceVisualReadinessSection))) if (!Sections.Contains(section)) d.Add(PersistencePanelWarning.PanelSourceMissing); if (Badge == PersistenceReadinessBadge.Ready && Blockers.Any()) d.Add(PersistencePanelWarning.BadgeConflict); if (runtimeClaim) d.Add(PersistencePanelWarning.RuntimeClaimDetected); if (Blockers.Any(b => string.IsNullOrWhiteSpace(b.Explanation))) d.Add(PersistencePanelWarning.BlockerWithoutExplanation); return d.Distinct().OrderBy(x => x).ToList(); } }

    public enum PersistenceDemoBlockerCode { RuntimeAbsent, FixtureMissing, DryRunBlocked, HarnessInvalid, SecretUnclassified, HookIncomplete, ServerNotAnalyzed, Bee251Premature }
    public enum PersistenceDemoBlockerSeverity { Info, Warning, Blocking, Forbidden }
    public enum PersistenceDemoNextAction { WaitServerAnalysis, ProvideEvidence, ClarifyContract, ReviewArchitecture, KeepOutOfScope }
    public enum PersistenceDemoBlockerDiagnostics { OpaqueBlockerCode, MissingNextAction, UnsafeBlockerText, AutoFixSuggested, BeeSourceMissing }
    public sealed class PersistenceDemoBlockerExplanation { public PersistenceDemoBlockerExplanation(PersistenceDemoBlockerCode code, string beeSource, string cause, string risk, PersistenceDemoNextAction? nextAction, string clientSafeText) { Code = code; BeeSource = beeSource ?? string.Empty; Cause = cause ?? string.Empty; Risk = risk ?? string.Empty; NextAction = nextAction; ClientSafeText = clientSafeText ?? string.Empty; Diagnostics = Detect(); } public PersistenceDemoBlockerCode Code { get; } public string BeeSource { get; } public string Cause { get; } public string Risk { get; } public PersistenceDemoNextAction? NextAction { get; } public string ClientSafeText { get; } public IReadOnlyList<PersistenceDemoBlockerDiagnostics> Diagnostics { get; } private IReadOnlyList<PersistenceDemoBlockerDiagnostics> Detect() { var d = new List<PersistenceDemoBlockerDiagnostics>(); if (string.IsNullOrWhiteSpace(BeeSource)) d.Add(PersistenceDemoBlockerDiagnostics.BeeSourceMissing); if (!NextAction.HasValue) d.Add(PersistenceDemoBlockerDiagnostics.MissingNextAction); if (ClientSafeText.IndexOf("secret", StringComparison.OrdinalIgnoreCase) >= 0) d.Add(PersistenceDemoBlockerDiagnostics.UnsafeBlockerText); if (ClientSafeText.IndexOf("auto-fix", StringComparison.OrdinalIgnoreCase) >= 0) d.Add(PersistenceDemoBlockerDiagnostics.AutoFixSuggested); return d.OrderBy(x => x).ToList(); } }

    public enum PersistenceEvidenceSource { BeeSpecification, WorkerReport, ServerProgress, ServerReport, QaReport, DemoObservation, RuntimeGap }
    public enum PersistenceEvidenceStatus { Confirmed, Missing, Contradictory, OutOfScope, FutureRuntime }
    public enum PersistenceEvidenceLimit { ContractOnly, DemoObservationOnly, ServerNotAnalyzed, QaNotFinal, RuntimeNotExecuted }
    public enum PersistenceEvidenceDiagnostics { EvidenceSourceMissing, EvidenceContradiction, EvidenceLimitMissing, UnsafeEvidenceDetail, UnlinkedVerdict }
    public sealed class PersistenceEvidenceLink { public PersistenceEvidenceLink(string verdictId, PersistenceEvidenceSource? source, PersistenceEvidenceStatus status, PersistenceEvidenceLimit? limit, string detail) { VerdictId = verdictId ?? string.Empty; Source = source; Status = status; Limit = limit; Detail = detail ?? string.Empty; } public string VerdictId { get; } public PersistenceEvidenceSource? Source { get; } public PersistenceEvidenceStatus Status { get; } public PersistenceEvidenceLimit? Limit { get; } public string Detail { get; } }
    public sealed class PersistenceEvidenceDrilldown { public PersistenceEvidenceDrilldown(IEnumerable<PersistenceEvidenceLink> links) { Links = (links ?? Array.Empty<PersistenceEvidenceLink>()).OrderBy(l => l.VerdictId, StringComparer.Ordinal).ToList(); Diagnostics = Detect(); } public IReadOnlyList<PersistenceEvidenceLink> Links { get; } public IReadOnlyList<PersistenceEvidenceDiagnostics> Diagnostics { get; } private IReadOnlyList<PersistenceEvidenceDiagnostics> Detect() { var d = new List<PersistenceEvidenceDiagnostics>(); if (Links.Any(l => !l.Source.HasValue)) d.Add(PersistenceEvidenceDiagnostics.EvidenceSourceMissing); if (Links.GroupBy(l => l.VerdictId).Any(g => g.Select(l => l.Status).Distinct().Count() > 1)) d.Add(PersistenceEvidenceDiagnostics.EvidenceContradiction); if (Links.Any(l => !l.Limit.HasValue)) d.Add(PersistenceEvidenceDiagnostics.EvidenceLimitMissing); if (Links.Any(l => l.Detail.IndexOf("secret", StringComparison.OrdinalIgnoreCase) >= 0)) d.Add(PersistenceEvidenceDiagnostics.UnsafeEvidenceDetail); if (Links.Any(l => string.IsNullOrWhiteSpace(l.VerdictId))) d.Add(PersistenceEvidenceDiagnostics.UnlinkedVerdict); return d.Distinct().OrderBy(x => x).ToList(); } }

    public enum PersistenceRuntimeGapCategory { MissingContract, MissingFixture, MissingServerAnalysis, MissingQaEvidence, RuntimeOutOfScope, DemoOnlyObservation, ForbiddenRuntimeClaim }
    public enum PersistenceRuntimeGapSeverity { Low, Medium, High, Blocking, Forbidden }
    public enum PersistenceRuntimeGapOwner { Planner, Worker, Architect, BeeServer, QA, Demo }
    public enum PersistenceRuntimeGapAction { ClarifyContract, ProvideFixture, RunServerAnalysis, ProvideQaEvidence, KeepOutOfScope, RemoveRuntimeClaim, DestructiveAction }
    public enum PersistenceRuntimeGapDiagnostics { GapCategoryMissing, GapOwnerMissing, DestructiveActionSuggested, GapEvidenceMissing, GapSeverityConflict }
    public sealed class PersistenceRuntimeGap { public PersistenceRuntimeGap(PersistenceRuntimeGapCategory? category, PersistenceRuntimeGapSeverity? severity, PersistenceRuntimeGapOwner? owner, PersistenceRuntimeGapAction action, string beeSource, string evidence) { Category = category; Severity = severity; Owner = owner; Action = action; BeeSource = beeSource ?? string.Empty; Evidence = evidence ?? string.Empty; } public PersistenceRuntimeGapCategory? Category { get; } public PersistenceRuntimeGapSeverity? Severity { get; } public PersistenceRuntimeGapOwner? Owner { get; } public PersistenceRuntimeGapAction Action { get; } public string BeeSource { get; } public string Evidence { get; } }
    public sealed class PersistenceRuntimeGapTriageReport { public PersistenceRuntimeGapTriageReport(IEnumerable<PersistenceRuntimeGap> gaps) { Gaps = (gaps ?? Array.Empty<PersistenceRuntimeGap>()).OrderByDescending(g => g.Severity).ThenBy(g => g.Category).ToList(); Diagnostics = Detect(); } public IReadOnlyList<PersistenceRuntimeGap> Gaps { get; } public IReadOnlyList<PersistenceRuntimeGapDiagnostics> Diagnostics { get; } private IReadOnlyList<PersistenceRuntimeGapDiagnostics> Detect() { var d = new List<PersistenceRuntimeGapDiagnostics>(); if (Gaps.Any(g => !g.Category.HasValue)) d.Add(PersistenceRuntimeGapDiagnostics.GapCategoryMissing); if (Gaps.Any(g => !g.Owner.HasValue)) d.Add(PersistenceRuntimeGapDiagnostics.GapOwnerMissing); if (Gaps.Any(g => g.Action == PersistenceRuntimeGapAction.DestructiveAction)) d.Add(PersistenceRuntimeGapDiagnostics.DestructiveActionSuggested); if (Gaps.Any(g => string.IsNullOrWhiteSpace(g.Evidence))) d.Add(PersistenceRuntimeGapDiagnostics.GapEvidenceMissing); if (Gaps.Any(g => !g.Severity.HasValue)) d.Add(PersistenceRuntimeGapDiagnostics.GapSeverityConflict); return d.Distinct().OrderBy(x => x).ToList(); } }

    public enum PersistenceHandoffParticipant { Worker, Architect, BeeServer, QA, Demo }
    public enum PersistenceHandoffStatus { ReadyForServerAnalysis, NeedsWorkerEvidence, BlockedByArchitecture, BlockedByQA, BlockedByDemoGap, OutOfScope }
    public enum PersistenceHandoffDecision { Approve, NeedsEvidence, Block, OutOfScope }
    public enum PersistenceHandoffDiagnostics { HandoffOwnerAmbiguous, WorkerEvidenceMissing, ArchitectureValidationMissing, QaRiskUnresolved, ServerScopePremature }
    public sealed class PersistenceBackendHandoffReview { public PersistenceBackendHandoffReview(IEnumerable<PersistenceHandoffParticipant> owners, bool workerEvidence, bool architectureValid, bool qaRiskOpen, bool serverPremature) { Owners = (owners ?? Array.Empty<PersistenceHandoffParticipant>()).Distinct().OrderBy(o => o).ToList(); Diagnostics = Detect(workerEvidence, architectureValid, qaRiskOpen, serverPremature); Status = Diagnostics.Contains(PersistenceHandoffDiagnostics.ArchitectureValidationMissing) ? PersistenceHandoffStatus.BlockedByArchitecture : Diagnostics.Contains(PersistenceHandoffDiagnostics.QaRiskUnresolved) ? PersistenceHandoffStatus.BlockedByQA : Diagnostics.Contains(PersistenceHandoffDiagnostics.WorkerEvidenceMissing) ? PersistenceHandoffStatus.NeedsWorkerEvidence : PersistenceHandoffStatus.ReadyForServerAnalysis; } public IReadOnlyList<PersistenceHandoffParticipant> Owners { get; } public IReadOnlyList<PersistenceHandoffDiagnostics> Diagnostics { get; } public PersistenceHandoffStatus Status { get; } private IReadOnlyList<PersistenceHandoffDiagnostics> Detect(bool workerEvidence, bool arch, bool qa, bool serverPremature) { var d = new List<PersistenceHandoffDiagnostics>(); if (Owners.Count > 1) d.Add(PersistenceHandoffDiagnostics.HandoffOwnerAmbiguous); if (!workerEvidence) d.Add(PersistenceHandoffDiagnostics.WorkerEvidenceMissing); if (!arch) d.Add(PersistenceHandoffDiagnostics.ArchitectureValidationMissing); if (qa) d.Add(PersistenceHandoffDiagnostics.QaRiskUnresolved); if (serverPremature) d.Add(PersistenceHandoffDiagnostics.ServerScopePremature); return d.OrderBy(x => x).ToList(); } }

    public enum PersistenceEvidenceAxis { BeeContract, WorkerReport, QaReport, ServerProgress, ServerReport, DemoReadModel, RuntimeGap }
    public enum PersistenceEvidenceAlignmentVerdict { Confirmed, MissingEvidence, Contradiction, OutOfScope, NeedsReview }
    public enum PersistenceEvidenceAlignmentDiagnostics { AlignmentSourceMissing, AlignmentContradiction, StaleEvidence, DemoQaConfusion, ServerEvidenceUnavailable }
    public sealed class PersistenceEvidenceAlignmentCell { public PersistenceEvidenceAlignmentCell(string bee, PersistenceEvidenceAxis axis, PersistenceEvidenceAlignmentVerdict verdict, long logicalDate, bool demoAsQa = false) { Bee = bee ?? string.Empty; Axis = axis; Verdict = verdict; LogicalDate = logicalDate; DemoAsQa = demoAsQa; } public string Bee { get; } public PersistenceEvidenceAxis Axis { get; } public PersistenceEvidenceAlignmentVerdict Verdict { get; } public long LogicalDate { get; } public bool DemoAsQa { get; } }
    public sealed class PersistenceEvidenceAlignmentMatrix { public PersistenceEvidenceAlignmentMatrix(IEnumerable<PersistenceEvidenceAlignmentCell> cells, long currentDate) { Cells = (cells ?? Array.Empty<PersistenceEvidenceAlignmentCell>()).OrderBy(c => c.Bee, StringComparer.Ordinal).ThenBy(c => c.Axis).ToList(); Diagnostics = Detect(currentDate); } public IReadOnlyList<PersistenceEvidenceAlignmentCell> Cells { get; } public IReadOnlyList<PersistenceEvidenceAlignmentDiagnostics> Diagnostics { get; } private IReadOnlyList<PersistenceEvidenceAlignmentDiagnostics> Detect(long current) { var d = new List<PersistenceEvidenceAlignmentDiagnostics>(); if (Cells.Any(c => c.Verdict == PersistenceEvidenceAlignmentVerdict.MissingEvidence)) d.Add(PersistenceEvidenceAlignmentDiagnostics.AlignmentSourceMissing); if (Cells.GroupBy(c => c.Bee).Any(g => g.Select(c => c.Verdict).Distinct().Count() > 1 && g.Any(c => c.Verdict == PersistenceEvidenceAlignmentVerdict.Contradiction))) d.Add(PersistenceEvidenceAlignmentDiagnostics.AlignmentContradiction); if (Cells.Any(c => current - c.LogicalDate > 100)) d.Add(PersistenceEvidenceAlignmentDiagnostics.StaleEvidence); if (Cells.Any(c => c.DemoAsQa)) d.Add(PersistenceEvidenceAlignmentDiagnostics.DemoQaConfusion); if (Cells.All(c => c.Axis != PersistenceEvidenceAxis.ServerReport)) d.Add(PersistenceEvidenceAlignmentDiagnostics.ServerEvidenceUnavailable); return d.Distinct().OrderBy(x => x).ToList(); } }

    public enum PersistenceDemoCaptureStatus { Observed, ObservedWithWarnings, Blocked, NotExecutable, InvalidCapture }
    public enum PersistenceDemoCaptureLimit { DemoObservationOnly, NoRuntimeExecution, NotQaFinal, ServerNotAnalyzed }
    public enum PersistenceDemoCaptureDiagnostics { CaptureScenarioMissing, CaptureLimitMissing, QaResultClaimed, RuntimeExecutionClaimed, CaptureSourceUntrusted }
    public sealed class PersistenceDemoCaptureScenario { public PersistenceDemoCaptureScenario(string id) { Id = id ?? string.Empty; } public string Id { get; } }
    public sealed class PersistenceDemoRegressionCapture { public PersistenceDemoRegressionCapture(long logicalDate, string sourceDemo, PersistenceDemoCaptureScenario scenario, PersistenceDemoCaptureStatus status, PersistenceDemoCaptureLimit? limit, string evidenceLink, bool claimsQaFinal, bool claimsRuntimeExecution) { LogicalDate = logicalDate; SourceDemo = sourceDemo ?? string.Empty; Scenario = scenario; Status = status; Limit = limit; EvidenceLink = evidenceLink ?? string.Empty; ClaimsQaFinal = claimsQaFinal; ClaimsRuntimeExecution = claimsRuntimeExecution; Diagnostics = Detect(); } public long LogicalDate { get; } public string SourceDemo { get; } public PersistenceDemoCaptureScenario Scenario { get; } public PersistenceDemoCaptureStatus Status { get; } public PersistenceDemoCaptureLimit? Limit { get; } public string EvidenceLink { get; } public bool ClaimsQaFinal { get; } public bool ClaimsRuntimeExecution { get; } public IReadOnlyList<PersistenceDemoCaptureDiagnostics> Diagnostics { get; } private IReadOnlyList<PersistenceDemoCaptureDiagnostics> Detect() { var d = new List<PersistenceDemoCaptureDiagnostics>(); if (Scenario == null || string.IsNullOrWhiteSpace(Scenario.Id)) d.Add(PersistenceDemoCaptureDiagnostics.CaptureScenarioMissing); if (!Limit.HasValue) d.Add(PersistenceDemoCaptureDiagnostics.CaptureLimitMissing); if (ClaimsQaFinal) d.Add(PersistenceDemoCaptureDiagnostics.QaResultClaimed); if (ClaimsRuntimeExecution) d.Add(PersistenceDemoCaptureDiagnostics.RuntimeExecutionClaimed); if (string.IsNullOrWhiteSpace(SourceDemo)) d.Add(PersistenceDemoCaptureDiagnostics.CaptureSourceUntrusted); return d.OrderBy(x => x).ToList(); } }

    public enum PersistenceMilestoneTarget { Alpha, Beta, EarlyAccess, PostEarlyAccess }
    public enum PersistenceMilestoneStatus { Informational, AtRisk, Blocked, OutOfScope, ReleaseDecisionForbidden }
    public enum PersistenceMilestoneProjectionDiagnostics { MilestoneGapMissing, ReleaseDecisionClaimed, ProjectionSourceMissing, ServerDependencyHidden, QaDependencyHidden }
    public sealed class PersistenceMilestoneGap { public PersistenceMilestoneGap(string reason) { Reason = reason ?? string.Empty; } public string Reason { get; } }
    public sealed class PersistenceMilestoneRisk { public PersistenceMilestoneRisk(string reason) { Reason = reason ?? string.Empty; } public string Reason { get; } }
    public sealed class PersistenceMilestoneProjection { public PersistenceMilestoneProjection(PersistenceMilestoneTarget target, IEnumerable<PersistenceMilestoneGap> gaps, bool releaseClaim, bool sourcePresent, bool serverVisible, bool qaVisible) { Target = target; Gaps = (gaps ?? Array.Empty<PersistenceMilestoneGap>()).ToList(); Status = releaseClaim ? PersistenceMilestoneStatus.ReleaseDecisionForbidden : Gaps.Any() ? PersistenceMilestoneStatus.AtRisk : PersistenceMilestoneStatus.Informational; Diagnostics = Detect(releaseClaim, sourcePresent, serverVisible, qaVisible); } public PersistenceMilestoneTarget Target { get; } public IReadOnlyList<PersistenceMilestoneGap> Gaps { get; } public PersistenceMilestoneStatus Status { get; } public IReadOnlyList<PersistenceMilestoneProjectionDiagnostics> Diagnostics { get; } private IReadOnlyList<PersistenceMilestoneProjectionDiagnostics> Detect(bool release, bool source, bool server, bool qa) { var d = new List<PersistenceMilestoneProjectionDiagnostics>(); if (!Gaps.Any()) d.Add(PersistenceMilestoneProjectionDiagnostics.MilestoneGapMissing); if (release) d.Add(PersistenceMilestoneProjectionDiagnostics.ReleaseDecisionClaimed); if (!source) d.Add(PersistenceMilestoneProjectionDiagnostics.ProjectionSourceMissing); if (!server) d.Add(PersistenceMilestoneProjectionDiagnostics.ServerDependencyHidden); if (!qa) d.Add(PersistenceMilestoneProjectionDiagnostics.QaDependencyHidden); return d.Distinct().OrderBy(x => x).ToList(); } }

    public enum PersistenceVisualVerificationVerdict { VisualVerificationReady, ReadyWithWarnings, NeedsRevision, BlockedByServerAnalysis, BlockedByEvidenceContradiction, BlockedByBee251Premature }
    public enum PersistenceVisualVerificationDiagnostics { Bee251Premature, DemoImpactMissing, ServerAnalysisStillRequired, EvidenceContradictionOpen, RuntimeClaimInvented }
    public sealed class PersistenceVisualVerificationCriterion { public PersistenceVisualVerificationCriterion(string bee, bool passed, bool warning, bool demoImpactPresent) { Bee = bee ?? string.Empty; Passed = passed; Warning = warning; DemoImpactPresent = demoImpactPresent; } public string Bee { get; } public bool Passed { get; } public bool Warning { get; } public bool DemoImpactPresent { get; } }
    public sealed class PersistenceVisualVerificationGate { public (PersistenceVisualVerificationVerdict Verdict, IReadOnlyList<PersistenceVisualVerificationDiagnostics> Diagnostics) Evaluate(IEnumerable<PersistenceVisualVerificationCriterion> criteria, bool serverAnalysisRequired, bool contradictionOpen, bool bee251, bool runtimeClaim) { var c = (criteria ?? Array.Empty<PersistenceVisualVerificationCriterion>()).ToList(); var d = new List<PersistenceVisualVerificationDiagnostics>(); if (bee251) d.Add(PersistenceVisualVerificationDiagnostics.Bee251Premature); if (c.Any(x => !x.DemoImpactPresent)) d.Add(PersistenceVisualVerificationDiagnostics.DemoImpactMissing); if (serverAnalysisRequired) d.Add(PersistenceVisualVerificationDiagnostics.ServerAnalysisStillRequired); if (contradictionOpen) d.Add(PersistenceVisualVerificationDiagnostics.EvidenceContradictionOpen); if (runtimeClaim) d.Add(PersistenceVisualVerificationDiagnostics.RuntimeClaimInvented); PersistenceVisualVerificationVerdict verdict = bee251 ? PersistenceVisualVerificationVerdict.BlockedByBee251Premature : contradictionOpen ? PersistenceVisualVerificationVerdict.BlockedByEvidenceContradiction : serverAnalysisRequired ? PersistenceVisualVerificationVerdict.BlockedByServerAnalysis : runtimeClaim || c.Any(x => !x.Passed) ? PersistenceVisualVerificationVerdict.NeedsRevision : c.Any(x => x.Warning) ? PersistenceVisualVerificationVerdict.ReadyWithWarnings : PersistenceVisualVerificationVerdict.VisualVerificationReady; return (verdict, d.OrderBy(x => x).ToList()); } }
}
